import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { Properties } from "lib/IntegratedDynamicsClasses/Properties";

export class OPERATOR_ITEMSTACK_WITH_NBT extends BaseOperator<
  Item,
  CompoundTag
> {
  static override internalName =
    "integrateddynamics:itemstack_withnbt" as const;
  static override numericID = 293;
  static override nicknames = [
    "itemstackItemwithtag",
    "itemstackWithNBT",
    "itemStackWithNbt",
    "itemStackWithNBT",
    "itemWithNBT",
    "itemwithtag",
    "item_stack_with_n_b_t",
    "item_stack_with_nbt",
    "item_with_n_b_t",
    "itemstack_itemwithtag",
    "itemstack_with_n_b_t",
  ];
  static override symbol = "with_nbt";
  static override interactName = "itemstackWithNBT";
  static override operatorName = "itemwithtag" as const;
  static override displayName = "Item With Tag" as const;
  static override fullDisplayName = "Item Item With Tag" as const;
  static override stringDisplayNames = [
    "item item with tag",
    "item item with Tag",
    "item item With tag",
    "item item With Tag",
    "item Item with tag",
    "item Item with Tag",
    "item Item With tag",
    "item Item With Tag",
    "Item item with tag",
    "Item item with Tag",
    "Item item With tag",
    "Item item With Tag",
    "Item Item with tag",
    "Item Item with Tag",
    "Item Item With tag",
    "Item Item With Tag",
    "item itemstack with tag",
    "item itemstack with Tag",
    "item itemstack With tag",
    "item itemstack With Tag",
    "item Itemstack with tag",
    "item Itemstack with Tag",
    "item Itemstack With tag",
    "item Itemstack With Tag",
    "item itemStack with tag",
    "item itemStack with Tag",
    "item itemStack With tag",
    "item itemStack With Tag",
    "item ItemStack with tag",
    "item ItemStack with Tag",
    "item ItemStack With tag",
    "item ItemStack With Tag",
    "Item itemstack with tag",
    "Item itemstack with Tag",
    "Item itemstack With tag",
    "Item itemstack With Tag",
    "Item Itemstack with tag",
    "Item Itemstack with Tag",
    "Item Itemstack With tag",
    "Item Itemstack With Tag",
    "Item itemStack with tag",
    "Item itemStack with Tag",
    "Item itemStack With tag",
    "Item itemStack With Tag",
    "Item ItemStack with tag",
    "Item ItemStack with Tag",
    "Item ItemStack With tag",
    "Item ItemStack With Tag",
    "itemstack item with tag",
    "itemstack item with Tag",
    "itemstack item With tag",
    "itemstack item With Tag",
    "itemstack Item with tag",
    "itemstack Item with Tag",
    "itemstack Item With tag",
    "itemstack Item With Tag",
    "Itemstack item with tag",
    "Itemstack item with Tag",
    "Itemstack item With tag",
    "Itemstack item With Tag",
    "Itemstack Item with tag",
    "Itemstack Item with Tag",
    "Itemstack Item With tag",
    "Itemstack Item With Tag",
    "itemStack item with tag",
    "itemStack item with Tag",
    "itemStack item With tag",
    "itemStack item With Tag",
    "itemStack Item with tag",
    "itemStack Item with Tag",
    "itemStack Item With tag",
    "itemStack Item With Tag",
    "ItemStack item with tag",
    "ItemStack item with Tag",
    "ItemStack item With tag",
    "ItemStack item With Tag",
    "ItemStack Item with tag",
    "ItemStack Item with Tag",
    "ItemStack Item With tag",
    "ItemStack Item With Tag",
    "itemstack itemstack with tag",
    "itemstack itemstack with Tag",
    "itemstack itemstack With tag",
    "itemstack itemstack With Tag",
    "itemstack Itemstack with tag",
    "itemstack Itemstack with Tag",
    "itemstack Itemstack With tag",
    "itemstack Itemstack With Tag",
    "itemstack itemStack with tag",
    "itemstack itemStack with Tag",
    "itemstack itemStack With tag",
    "itemstack itemStack With Tag",
    "itemstack ItemStack with tag",
    "itemstack ItemStack with Tag",
    "itemstack ItemStack With tag",
    "itemstack ItemStack With Tag",
    "Itemstack itemstack with tag",
    "Itemstack itemstack with Tag",
    "Itemstack itemstack With tag",
    "Itemstack itemstack With Tag",
    "Itemstack Itemstack with tag",
    "Itemstack Itemstack with Tag",
    "Itemstack Itemstack With tag",
    "Itemstack Itemstack With Tag",
    "Itemstack itemStack with tag",
    "Itemstack itemStack with Tag",
    "Itemstack itemStack With tag",
    "Itemstack itemStack With Tag",
    "Itemstack ItemStack with tag",
    "Itemstack ItemStack with Tag",
    "Itemstack ItemStack With tag",
    "Itemstack ItemStack With Tag",
    "itemStack itemstack with tag",
    "itemStack itemstack with Tag",
    "itemStack itemstack With tag",
    "itemStack itemstack With Tag",
    "itemStack Itemstack with tag",
    "itemStack Itemstack with Tag",
    "itemStack Itemstack With tag",
    "itemStack Itemstack With Tag",
    "itemStack itemStack with tag",
    "itemStack itemStack with Tag",
    "itemStack itemStack With tag",
    "itemStack itemStack With Tag",
    "itemStack ItemStack with tag",
    "itemStack ItemStack with Tag",
    "itemStack ItemStack With tag",
    "itemStack ItemStack With Tag",
    "ItemStack itemstack with tag",
    "ItemStack itemstack with Tag",
    "ItemStack itemstack With tag",
    "ItemStack itemstack With Tag",
    "ItemStack Itemstack with tag",
    "ItemStack Itemstack with Tag",
    "ItemStack Itemstack With tag",
    "ItemStack Itemstack With Tag",
    "ItemStack itemStack with tag",
    "ItemStack itemStack with Tag",
    "ItemStack itemStack With tag",
    "ItemStack itemStack With Tag",
    "ItemStack ItemStack with tag",
    "ItemStack ItemStack with Tag",
    "ItemStack ItemStack With tag",
    "ItemStack ItemStack With Tag",
    "item with tag",
    "item with Tag",
    "item With tag",
    "item With Tag",
    "Item with tag",
    "Item with Tag",
    "Item With tag",
    "Item With Tag",
    "itemstack with tag",
    "itemstack with Tag",
    "itemstack With tag",
    "itemstack With Tag",
    "Itemstack with tag",
    "Itemstack with Tag",
    "Itemstack With tag",
    "Itemstack With Tag",
    "itemStack with tag",
    "itemStack with Tag",
    "itemStack With tag",
    "itemStack With Tag",
    "ItemStack with tag",
    "ItemStack with Tag",
    "ItemStack With tag",
    "ItemStack With Tag",
  ];
  static override kind = "itemstack" as const;
  static override renderPattern = "INFIX_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Function",
            from: {
              type: "NBT",
            },
            to: {
              type: "Item",
            },
          },
        },
        normalizeSignature
      ),
      function: (item: Item): TypeLambda<CompoundTag, Item> => {
        return (nbt: CompoundTag): Item => {
          return new Item(new Properties({ NBT: nbt }), item);
        };
      },
    });
  }
}
