import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";

import { RegistryHub } from "lib/IntegratedDynamicsClasses/registries/registryHub";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { Properties } from "lib/IntegratedDynamicsClasses/Properties";

export class OPERATOR_ITEMSTACK_ITEMBYNAME extends BaseOperator<iString, Item> {
  static override internalName =
    "integrateddynamics:itemstack_itembyname" as const;
  static override numericID = 189;
  static override nicknames = [
    "itembyname",
    "itemByName",
    "itemstackByName",
    "ItemstackByName",
    "itemstackItembyname",
    "stringItemByName",
    "item_by_name",
    "itemstack_by_name",
    "itemstack_itembyname",
    "string_item_by_name",
  ];
  static override symbol = "item_by_name";
  static override interactName = "stringItemByName";
  static override operatorName = "itembyname" as const;
  static override displayName = "Item By Name" as const;
  static override fullDisplayName = "Item Item By Name" as const;
  static override stringDisplayNames = [
    "item item by name",
    "item item by Name",
    "item item By name",
    "item item By Name",
    "item Item by name",
    "item Item by Name",
    "item Item By name",
    "item Item By Name",
    "Item item by name",
    "Item item by Name",
    "Item item By name",
    "Item item By Name",
    "Item Item by name",
    "Item Item by Name",
    "Item Item By name",
    "Item Item By Name",
    "item itemstack by name",
    "item itemstack by Name",
    "item itemstack By name",
    "item itemstack By Name",
    "item Itemstack by name",
    "item Itemstack by Name",
    "item Itemstack By name",
    "item Itemstack By Name",
    "item itemStack by name",
    "item itemStack by Name",
    "item itemStack By name",
    "item itemStack By Name",
    "item ItemStack by name",
    "item ItemStack by Name",
    "item ItemStack By name",
    "item ItemStack By Name",
    "Item itemstack by name",
    "Item itemstack by Name",
    "Item itemstack By name",
    "Item itemstack By Name",
    "Item Itemstack by name",
    "Item Itemstack by Name",
    "Item Itemstack By name",
    "Item Itemstack By Name",
    "Item itemStack by name",
    "Item itemStack by Name",
    "Item itemStack By name",
    "Item itemStack By Name",
    "Item ItemStack by name",
    "Item ItemStack by Name",
    "Item ItemStack By name",
    "Item ItemStack By Name",
    "itemstack item by name",
    "itemstack item by Name",
    "itemstack item By name",
    "itemstack item By Name",
    "itemstack Item by name",
    "itemstack Item by Name",
    "itemstack Item By name",
    "itemstack Item By Name",
    "Itemstack item by name",
    "Itemstack item by Name",
    "Itemstack item By name",
    "Itemstack item By Name",
    "Itemstack Item by name",
    "Itemstack Item by Name",
    "Itemstack Item By name",
    "Itemstack Item By Name",
    "itemStack item by name",
    "itemStack item by Name",
    "itemStack item By name",
    "itemStack item By Name",
    "itemStack Item by name",
    "itemStack Item by Name",
    "itemStack Item By name",
    "itemStack Item By Name",
    "ItemStack item by name",
    "ItemStack item by Name",
    "ItemStack item By name",
    "ItemStack item By Name",
    "ItemStack Item by name",
    "ItemStack Item by Name",
    "ItemStack Item By name",
    "ItemStack Item By Name",
    "itemstack itemstack by name",
    "itemstack itemstack by Name",
    "itemstack itemstack By name",
    "itemstack itemstack By Name",
    "itemstack Itemstack by name",
    "itemstack Itemstack by Name",
    "itemstack Itemstack By name",
    "itemstack Itemstack By Name",
    "itemstack itemStack by name",
    "itemstack itemStack by Name",
    "itemstack itemStack By name",
    "itemstack itemStack By Name",
    "itemstack ItemStack by name",
    "itemstack ItemStack by Name",
    "itemstack ItemStack By name",
    "itemstack ItemStack By Name",
    "Itemstack itemstack by name",
    "Itemstack itemstack by Name",
    "Itemstack itemstack By name",
    "Itemstack itemstack By Name",
    "Itemstack Itemstack by name",
    "Itemstack Itemstack by Name",
    "Itemstack Itemstack By name",
    "Itemstack Itemstack By Name",
    "Itemstack itemStack by name",
    "Itemstack itemStack by Name",
    "Itemstack itemStack By name",
    "Itemstack itemStack By Name",
    "Itemstack ItemStack by name",
    "Itemstack ItemStack by Name",
    "Itemstack ItemStack By name",
    "Itemstack ItemStack By Name",
    "itemStack itemstack by name",
    "itemStack itemstack by Name",
    "itemStack itemstack By name",
    "itemStack itemstack By Name",
    "itemStack Itemstack by name",
    "itemStack Itemstack by Name",
    "itemStack Itemstack By name",
    "itemStack Itemstack By Name",
    "itemStack itemStack by name",
    "itemStack itemStack by Name",
    "itemStack itemStack By name",
    "itemStack itemStack By Name",
    "itemStack ItemStack by name",
    "itemStack ItemStack by Name",
    "itemStack ItemStack By name",
    "itemStack ItemStack By Name",
    "ItemStack itemstack by name",
    "ItemStack itemstack by Name",
    "ItemStack itemstack By name",
    "ItemStack itemstack By Name",
    "ItemStack Itemstack by name",
    "ItemStack Itemstack by Name",
    "ItemStack Itemstack By name",
    "ItemStack Itemstack By Name",
    "ItemStack itemStack by name",
    "ItemStack itemStack by Name",
    "ItemStack itemStack By name",
    "ItemStack itemStack By Name",
    "ItemStack ItemStack by name",
    "ItemStack ItemStack by Name",
    "ItemStack ItemStack By name",
    "ItemStack ItemStack By Name",
    "item by name",
    "item by Name",
    "item By name",
    "item By Name",
    "Item by name",
    "Item by Name",
    "Item By name",
    "Item By Name",
    "itemstack by name",
    "itemstack by Name",
    "itemstack By name",
    "itemstack By Name",
    "Itemstack by name",
    "Itemstack by Name",
    "Itemstack By name",
    "Itemstack By Name",
    "itemStack by name",
    "itemStack by Name",
    "itemStack By name",
    "itemStack By Name",
    "ItemStack by name",
    "ItemStack by Name",
    "ItemStack By name",
    "ItemStack By Name",
  ];
  static override tooltipInfo =
    "Get the item corresponding to the given unique name, add space+number for indicating the metadata." as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "PREFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "String",
          },
          to: {
            type: "Item",
          },
        },
        normalizeSignature
      ),
      function: (name: iString): Item => {
        const itemRegistry = RegistryHub.itemRegistry;
        let key = name.valueOf().toLowerCase();
        const ItemConstructor =
          itemRegistry.items[key as keyof typeof itemRegistry.items];
        if (ItemConstructor) {
          return new ItemConstructor();
        }
        return new Item(new Properties({}));
      },
    });
  }
}
