import { NullTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/NullTag";
import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { iBoolean } from "lib/IntegratedDynamicsClasses/typeWrappers/iBoolean";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";

export class OPERATOR_ITEMSTACK_DATAVALUE extends BaseOperator<Item, iBoolean> {
  static override internalName =
    "integrateddynamics:itemstack_datavalue" as const;
  static override numericID = 288;
  static override nicknames = [
    "itemDataValue",
    "itemNBTValue",
    "itemstackDatavalue",
    "itemstackDataValue",
    "ItemstackDataValue",
    "itemstackItemstackDatavalue",
    "item_data_value",
    "item_n_b_t_value",
    "itemstack_data_value",
    "itemstack_datavalue",
    "itemstackItemstack_datavalue",
  ];
  static override symbol = "data_value";
  static override interactName = "itemstackDataValue";
  static override operatorName = "itemstack_datavalue" as const;
  static override displayName = "Item Data Value" as const;
  static override fullDisplayName = "Item Item Data Value" as const;
  static override stringDisplayNames = [
    "item item data value",
    "item item data Value",
    "item item Data value",
    "item item Data Value",
    "item Item data value",
    "item Item data Value",
    "item Item Data value",
    "item Item Data Value",
    "Item item data value",
    "Item item data Value",
    "Item item Data value",
    "Item item Data Value",
    "Item Item data value",
    "Item Item data Value",
    "Item Item Data value",
    "Item Item Data Value",
    "item itemstack data value",
    "item itemstack data Value",
    "item itemstack Data value",
    "item itemstack Data Value",
    "item Itemstack data value",
    "item Itemstack data Value",
    "item Itemstack Data value",
    "item Itemstack Data Value",
    "item itemStack data value",
    "item itemStack data Value",
    "item itemStack Data value",
    "item itemStack Data Value",
    "item ItemStack data value",
    "item ItemStack data Value",
    "item ItemStack Data value",
    "item ItemStack Data Value",
    "Item itemstack data value",
    "Item itemstack data Value",
    "Item itemstack Data value",
    "Item itemstack Data Value",
    "Item Itemstack data value",
    "Item Itemstack data Value",
    "Item Itemstack Data value",
    "Item Itemstack Data Value",
    "Item itemStack data value",
    "Item itemStack data Value",
    "Item itemStack Data value",
    "Item itemStack Data Value",
    "Item ItemStack data value",
    "Item ItemStack data Value",
    "Item ItemStack Data value",
    "Item ItemStack Data Value",
    "itemstack item data value",
    "itemstack item data Value",
    "itemstack item Data value",
    "itemstack item Data Value",
    "itemstack Item data value",
    "itemstack Item data Value",
    "itemstack Item Data value",
    "itemstack Item Data Value",
    "Itemstack item data value",
    "Itemstack item data Value",
    "Itemstack item Data value",
    "Itemstack item Data Value",
    "Itemstack Item data value",
    "Itemstack Item data Value",
    "Itemstack Item Data value",
    "Itemstack Item Data Value",
    "itemStack item data value",
    "itemStack item data Value",
    "itemStack item Data value",
    "itemStack item Data Value",
    "itemStack Item data value",
    "itemStack Item data Value",
    "itemStack Item Data value",
    "itemStack Item Data Value",
    "ItemStack item data value",
    "ItemStack item data Value",
    "ItemStack item Data value",
    "ItemStack item Data Value",
    "ItemStack Item data value",
    "ItemStack Item data Value",
    "ItemStack Item Data value",
    "ItemStack Item Data Value",
    "itemstack itemstack data value",
    "itemstack itemstack data Value",
    "itemstack itemstack Data value",
    "itemstack itemstack Data Value",
    "itemstack Itemstack data value",
    "itemstack Itemstack data Value",
    "itemstack Itemstack Data value",
    "itemstack Itemstack Data Value",
    "itemstack itemStack data value",
    "itemstack itemStack data Value",
    "itemstack itemStack Data value",
    "itemstack itemStack Data Value",
    "itemstack ItemStack data value",
    "itemstack ItemStack data Value",
    "itemstack ItemStack Data value",
    "itemstack ItemStack Data Value",
    "Itemstack itemstack data value",
    "Itemstack itemstack data Value",
    "Itemstack itemstack Data value",
    "Itemstack itemstack Data Value",
    "Itemstack Itemstack data value",
    "Itemstack Itemstack data Value",
    "Itemstack Itemstack Data value",
    "Itemstack Itemstack Data Value",
    "Itemstack itemStack data value",
    "Itemstack itemStack data Value",
    "Itemstack itemStack Data value",
    "Itemstack itemStack Data Value",
    "Itemstack ItemStack data value",
    "Itemstack ItemStack data Value",
    "Itemstack ItemStack Data value",
    "Itemstack ItemStack Data Value",
    "itemStack itemstack data value",
    "itemStack itemstack data Value",
    "itemStack itemstack Data value",
    "itemStack itemstack Data Value",
    "itemStack Itemstack data value",
    "itemStack Itemstack data Value",
    "itemStack Itemstack Data value",
    "itemStack Itemstack Data Value",
    "itemStack itemStack data value",
    "itemStack itemStack data Value",
    "itemStack itemStack Data value",
    "itemStack itemStack Data Value",
    "itemStack ItemStack data value",
    "itemStack ItemStack data Value",
    "itemStack ItemStack Data value",
    "itemStack ItemStack Data Value",
    "ItemStack itemstack data value",
    "ItemStack itemstack data Value",
    "ItemStack itemstack Data value",
    "ItemStack itemstack Data Value",
    "ItemStack Itemstack data value",
    "ItemStack Itemstack data Value",
    "ItemStack Itemstack Data value",
    "ItemStack Itemstack Data Value",
    "ItemStack itemStack data value",
    "ItemStack itemStack data Value",
    "ItemStack itemStack Data value",
    "ItemStack itemStack Data Value",
    "ItemStack ItemStack data value",
    "ItemStack ItemStack data Value",
    "ItemStack ItemStack Data value",
    "ItemStack ItemStack Data Value",
    "item data value",
    "item data Value",
    "item Data value",
    "item Data Value",
    "Item data value",
    "Item data Value",
    "Item Data value",
    "Item Data Value",
    "itemstack data value",
    "itemstack data Value",
    "itemstack Data value",
    "itemstack Data Value",
    "Itemstack data value",
    "Itemstack data Value",
    "Itemstack Data value",
    "Itemstack Data Value",
    "itemStack data value",
    "itemStack data Value",
    "itemStack Data value",
    "itemStack Data Value",
    "ItemStack data value",
    "ItemStack data Value",
    "ItemStack Data value",
    "ItemStack Data Value",
  ];
  static override kind = "itemstack" as const;
  static override renderPattern = "INFIX_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: {
              type: "NBT",
            },
          },
        },
        normalizeSignature
      ),
      function: (item: Item): TypeLambda<iString, Tag<IntegratedValue>> => {
        return (key: iString): Tag<IntegratedValue> => {
          const nbt = item.getNBT();
          if (nbt instanceof CompoundTag && nbt.has(key)) {
            return nbt.get(key);
          }
          return new NullTag();
        };
      },
    });
  }
}
