import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";
import { NullTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/NullTag";
import { iError } from "lib/IntegratedDynamicsClasses/typeWrappers/iError";

export class OPERATOR_NBT_COMPOUND_VALUE_LIST_TAG extends BaseOperator<
  CompoundTag,
  Operator<iString, iArray<Tag<IntegratedValue>>>
> {
  static override internalName =
    "integrateddynamics:nbt_compound_value_list_tag" as const;
  static override numericID = 221;
  static override nicknames = [
    "compoundValueListNBT",
    "compoundValueListTag",
    "nbtCompoundValueList",
    "nbtCompoundValueListTag",
    "nbtGetGenericListTag",
    "compound_value_list_n_b_t",
    "compound_value_list_tag",
    "nbt_compound_value_list",
    "nbt_compound_value_list_tag",
    "nbt_get_generic_list_tag",
  ];
  static override symbol = "NBT{}.get_list_tag";
  static override interactName = "nbtGetGenericListTag";
  static override operatorName = "compound_value_list_tag" as const;
  static override displayName = "NBT Compound Value List NBT" as const;
  static override fullDisplayName = "NBT NBT Compound Value List NBT" as const;
  static override stringDisplayNames = [
    "nbt compound value list nbt",
    "nbt compound value list Nbt",
    "nbt compound value List nbt",
    "nbt compound value List Nbt",
    "nbt compound Value list nbt",
    "nbt compound Value list Nbt",
    "nbt compound Value List nbt",
    "nbt compound Value List Nbt",
    "nbt Compound value list nbt",
    "nbt Compound value list Nbt",
    "nbt Compound value List nbt",
    "nbt Compound value List Nbt",
    "nbt Compound Value list nbt",
    "nbt Compound Value list Nbt",
    "nbt Compound Value List nbt",
    "nbt Compound Value List Nbt",
    "Nbt compound value list nbt",
    "Nbt compound value list Nbt",
    "Nbt compound value List nbt",
    "Nbt compound value List Nbt",
    "Nbt compound Value list nbt",
    "Nbt compound Value list Nbt",
    "Nbt compound Value List nbt",
    "Nbt compound Value List Nbt",
    "Nbt Compound value list nbt",
    "Nbt Compound value list Nbt",
    "Nbt Compound value List nbt",
    "Nbt Compound value List Nbt",
    "Nbt Compound Value list nbt",
    "Nbt Compound Value list Nbt",
    "Nbt Compound Value List nbt",
    "Nbt Compound Value List Nbt",
    "nbt compound value list NBT",
    "nbt compound value List NBT",
    "nbt compound Value list NBT",
    "nbt compound Value List NBT",
    "nbt Compound value list NBT",
    "nbt Compound value List NBT",
    "nbt Compound Value list NBT",
    "nbt Compound Value List NBT",
    "Nbt compound value list NBT",
    "Nbt compound value List NBT",
    "Nbt compound Value list NBT",
    "Nbt compound Value List NBT",
    "Nbt Compound value list NBT",
    "Nbt Compound value List NBT",
    "Nbt Compound Value list NBT",
    "Nbt Compound Value List NBT",
    "NBT compound value list nbt",
    "NBT compound value list Nbt",
    "NBT compound value List nbt",
    "NBT compound value List Nbt",
    "NBT compound Value list nbt",
    "NBT compound Value list Nbt",
    "NBT compound Value List nbt",
    "NBT compound Value List Nbt",
    "NBT Compound value list nbt",
    "NBT Compound value list Nbt",
    "NBT Compound value List nbt",
    "NBT Compound value List Nbt",
    "NBT Compound Value list nbt",
    "NBT Compound Value list Nbt",
    "NBT Compound Value List nbt",
    "NBT Compound Value List Nbt",
    "NBT compound value list NBT",
    "NBT compound value List NBT",
    "NBT compound Value list NBT",
    "NBT compound Value List NBT",
    "NBT Compound value list NBT",
    "NBT Compound value List NBT",
    "NBT Compound Value list NBT",
    "NBT Compound Value List NBT",
    "nbt nbt compound value list nbt",
    "nbt nbt compound value list Nbt",
    "nbt nbt compound value List nbt",
    "nbt nbt compound value List Nbt",
    "nbt nbt compound Value list nbt",
    "nbt nbt compound Value list Nbt",
    "nbt nbt compound Value List nbt",
    "nbt nbt compound Value List Nbt",
    "nbt nbt Compound value list nbt",
    "nbt nbt Compound value list Nbt",
    "nbt nbt Compound value List nbt",
    "nbt nbt Compound value List Nbt",
    "nbt nbt Compound Value list nbt",
    "nbt nbt Compound Value list Nbt",
    "nbt nbt Compound Value List nbt",
    "nbt nbt Compound Value List Nbt",
    "nbt Nbt compound value list nbt",
    "nbt Nbt compound value list Nbt",
    "nbt Nbt compound value List nbt",
    "nbt Nbt compound value List Nbt",
    "nbt Nbt compound Value list nbt",
    "nbt Nbt compound Value list Nbt",
    "nbt Nbt compound Value List nbt",
    "nbt Nbt compound Value List Nbt",
    "nbt Nbt Compound value list nbt",
    "nbt Nbt Compound value list Nbt",
    "nbt Nbt Compound value List nbt",
    "nbt Nbt Compound value List Nbt",
    "nbt Nbt Compound Value list nbt",
    "nbt Nbt Compound Value list Nbt",
    "nbt Nbt Compound Value List nbt",
    "nbt Nbt Compound Value List Nbt",
    "Nbt nbt compound value list nbt",
    "Nbt nbt compound value list Nbt",
    "Nbt nbt compound value List nbt",
    "Nbt nbt compound value List Nbt",
    "Nbt nbt compound Value list nbt",
    "Nbt nbt compound Value list Nbt",
    "Nbt nbt compound Value List nbt",
    "Nbt nbt compound Value List Nbt",
    "Nbt nbt Compound value list nbt",
    "Nbt nbt Compound value list Nbt",
    "Nbt nbt Compound value List nbt",
    "Nbt nbt Compound value List Nbt",
    "Nbt nbt Compound Value list nbt",
    "Nbt nbt Compound Value list Nbt",
    "Nbt nbt Compound Value List nbt",
    "Nbt nbt Compound Value List Nbt",
    "Nbt Nbt compound value list nbt",
    "Nbt Nbt compound value list Nbt",
    "Nbt Nbt compound value List nbt",
    "Nbt Nbt compound value List Nbt",
    "Nbt Nbt compound Value list nbt",
    "Nbt Nbt compound Value list Nbt",
    "Nbt Nbt compound Value List nbt",
    "Nbt Nbt compound Value List Nbt",
    "Nbt Nbt Compound value list nbt",
    "Nbt Nbt Compound value list Nbt",
    "Nbt Nbt Compound value List nbt",
    "Nbt Nbt Compound value List Nbt",
    "Nbt Nbt Compound Value list nbt",
    "Nbt Nbt Compound Value list Nbt",
    "Nbt Nbt Compound Value List nbt",
    "Nbt Nbt Compound Value List Nbt",
    "nbt nbt compound value list NBT",
    "nbt nbt compound value List NBT",
    "nbt nbt compound Value list NBT",
    "nbt nbt compound Value List NBT",
    "nbt nbt Compound value list NBT",
    "nbt nbt Compound value List NBT",
    "nbt nbt Compound Value list NBT",
    "nbt nbt Compound Value List NBT",
    "nbt Nbt compound value list NBT",
    "nbt Nbt compound value List NBT",
    "nbt Nbt compound Value list NBT",
    "nbt Nbt compound Value List NBT",
    "nbt Nbt Compound value list NBT",
    "nbt Nbt Compound value List NBT",
    "nbt Nbt Compound Value list NBT",
    "nbt Nbt Compound Value List NBT",
    "Nbt nbt compound value list NBT",
    "Nbt nbt compound value List NBT",
    "Nbt nbt compound Value list NBT",
    "Nbt nbt compound Value List NBT",
    "Nbt nbt Compound value list NBT",
    "Nbt nbt Compound value List NBT",
    "Nbt nbt Compound Value list NBT",
    "Nbt nbt Compound Value List NBT",
    "Nbt Nbt compound value list NBT",
    "Nbt Nbt compound value List NBT",
    "Nbt Nbt compound Value list NBT",
    "Nbt Nbt compound Value List NBT",
    "Nbt Nbt Compound value list NBT",
    "Nbt Nbt Compound value List NBT",
    "Nbt Nbt Compound Value list NBT",
    "Nbt Nbt Compound Value List NBT",
    "nbt NBT compound value list nbt",
    "nbt NBT compound value list Nbt",
    "nbt NBT compound value List nbt",
    "nbt NBT compound value List Nbt",
    "nbt NBT compound Value list nbt",
    "nbt NBT compound Value list Nbt",
    "nbt NBT compound Value List nbt",
    "nbt NBT compound Value List Nbt",
    "nbt NBT Compound value list nbt",
    "nbt NBT Compound value list Nbt",
    "nbt NBT Compound value List nbt",
    "nbt NBT Compound value List Nbt",
    "nbt NBT Compound Value list nbt",
    "nbt NBT Compound Value list Nbt",
    "nbt NBT Compound Value List nbt",
    "nbt NBT Compound Value List Nbt",
    "Nbt NBT compound value list nbt",
    "Nbt NBT compound value list Nbt",
    "Nbt NBT compound value List nbt",
    "Nbt NBT compound value List Nbt",
    "Nbt NBT compound Value list nbt",
    "Nbt NBT compound Value list Nbt",
    "Nbt NBT compound Value List nbt",
    "Nbt NBT compound Value List Nbt",
    "Nbt NBT Compound value list nbt",
    "Nbt NBT Compound value list Nbt",
    "Nbt NBT Compound value List nbt",
    "Nbt NBT Compound value List Nbt",
    "Nbt NBT Compound Value list nbt",
    "Nbt NBT Compound Value list Nbt",
    "Nbt NBT Compound Value List nbt",
    "Nbt NBT Compound Value List Nbt",
    "nbt NBT compound value list NBT",
    "nbt NBT compound value List NBT",
    "nbt NBT compound Value list NBT",
    "nbt NBT compound Value List NBT",
    "nbt NBT Compound value list NBT",
    "nbt NBT Compound value List NBT",
    "nbt NBT Compound Value list NBT",
    "nbt NBT Compound Value List NBT",
    "Nbt NBT compound value list NBT",
    "Nbt NBT compound value List NBT",
    "Nbt NBT compound Value list NBT",
    "Nbt NBT compound Value List NBT",
    "Nbt NBT Compound value list NBT",
    "Nbt NBT Compound value List NBT",
    "Nbt NBT Compound Value list NBT",
    "Nbt NBT Compound Value List NBT",
    "NBT nbt compound value list nbt",
    "NBT nbt compound value list Nbt",
    "NBT nbt compound value List nbt",
    "NBT nbt compound value List Nbt",
    "NBT nbt compound Value list nbt",
    "NBT nbt compound Value list Nbt",
    "NBT nbt compound Value List nbt",
    "NBT nbt compound Value List Nbt",
    "NBT nbt Compound value list nbt",
    "NBT nbt Compound value list Nbt",
    "NBT nbt Compound value List nbt",
    "NBT nbt Compound value List Nbt",
    "NBT nbt Compound Value list nbt",
    "NBT nbt Compound Value list Nbt",
    "NBT nbt Compound Value List nbt",
    "NBT nbt Compound Value List Nbt",
    "NBT Nbt compound value list nbt",
    "NBT Nbt compound value list Nbt",
    "NBT Nbt compound value List nbt",
    "NBT Nbt compound value List Nbt",
    "NBT Nbt compound Value list nbt",
    "NBT Nbt compound Value list Nbt",
    "NBT Nbt compound Value List nbt",
    "NBT Nbt compound Value List Nbt",
    "NBT Nbt Compound value list nbt",
    "NBT Nbt Compound value list Nbt",
    "NBT Nbt Compound value List nbt",
    "NBT Nbt Compound value List Nbt",
    "NBT Nbt Compound Value list nbt",
    "NBT Nbt Compound Value list Nbt",
    "NBT Nbt Compound Value List nbt",
    "NBT Nbt Compound Value List Nbt",
    "NBT nbt compound value list NBT",
    "NBT nbt compound value List NBT",
    "NBT nbt compound Value list NBT",
    "NBT nbt compound Value List NBT",
    "NBT nbt Compound value list NBT",
    "NBT nbt Compound value List NBT",
    "NBT nbt Compound Value list NBT",
    "NBT nbt Compound Value List NBT",
    "NBT Nbt compound value list NBT",
    "NBT Nbt compound value List NBT",
    "NBT Nbt compound Value list NBT",
    "NBT Nbt compound Value List NBT",
    "NBT Nbt Compound value list NBT",
    "NBT Nbt Compound value List NBT",
    "NBT Nbt Compound Value list NBT",
    "NBT Nbt Compound Value List NBT",
    "NBT NBT compound value list nbt",
    "NBT NBT compound value list Nbt",
    "NBT NBT compound value List nbt",
    "NBT NBT compound value List Nbt",
    "NBT NBT compound Value list nbt",
    "NBT NBT compound Value list Nbt",
    "NBT NBT compound Value List nbt",
    "NBT NBT compound Value List Nbt",
    "NBT NBT Compound value list nbt",
    "NBT NBT Compound value list Nbt",
    "NBT NBT Compound value List nbt",
    "NBT NBT Compound value List Nbt",
    "NBT NBT Compound Value list nbt",
    "NBT NBT Compound Value list Nbt",
    "NBT NBT Compound Value List nbt",
    "NBT NBT Compound Value List Nbt",
    "NBT NBT compound value list NBT",
    "NBT NBT compound value List NBT",
    "NBT NBT compound Value list NBT",
    "NBT NBT compound Value List NBT",
    "NBT NBT Compound value list NBT",
    "NBT NBT Compound value List NBT",
    "NBT NBT Compound Value list NBT",
    "NBT NBT Compound Value List NBT",
  ];
  static override tooltipInfo =
    "The NBT List value in the given NBT compound tag with the given key" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "INFIX_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: { type: "List", listType: { type: "NBT" } },
          },
        },
        normalizeSignature
      ),
      function: (
        nbt: CompoundTag
      ): TypeLambda<iString, iArray<Tag<IntegratedValue>>> => {
        return (key: iString): iArray<Tag<IntegratedValue>> => {
          if (!nbt.has(key)) {
            return new iArrayEager([]);
          }
          let listTag = nbt.get(key);
          if (listTag instanceof NullTag) {
            return new iArrayEager([]);
          }
          if (listTag.getType() != Tag.TAG_LIST)
            throw new iError(
              `${key.valueOf()} is not a list of NBT in ${JSON.stringify(nbt.toJSON())}`
            );
          return (listTag as ListTag).getArray();
        };
      },
    });
  }
}
