import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";

export class OPERATOR_NBT_FROM_TAG_LIST extends BaseOperator<
  iArray<Tag<IntegratedValue>>,
  ListTag
> {
  static override internalName =
    "integrateddynamics:nbt_from_tag_list" as const;
  static override numericID = 265;
  static override nicknames = [
    "fromTagList",
    "nbtFromTagList",
    "tagListAsNbt",
    "from_tag_list",
    "nbt_from_tag_list",
    "tag_list_as_nbt",
  ];
  static override symbol = "NBT.from_tag_list";
  static override interactName = "tagListAsNbt";
  static override operatorName = "from_tag_list" as const;
  static override displayName = "NBT List From Tag List" as const;
  static override fullDisplayName = "NBT NBT List From Tag List" as const;
  static override stringDisplayNames = [
    "nbt list from tag list",
    "nbt list from tag List",
    "nbt list from Tag list",
    "nbt list from Tag List",
    "nbt list From tag list",
    "nbt list From tag List",
    "nbt list From Tag list",
    "nbt list From Tag List",
    "nbt List from tag list",
    "nbt List from tag List",
    "nbt List from Tag list",
    "nbt List from Tag List",
    "nbt List From tag list",
    "nbt List From tag List",
    "nbt List From Tag list",
    "nbt List From Tag List",
    "Nbt list from tag list",
    "Nbt list from tag List",
    "Nbt list from Tag list",
    "Nbt list from Tag List",
    "Nbt list From tag list",
    "Nbt list From tag List",
    "Nbt list From Tag list",
    "Nbt list From Tag List",
    "Nbt List from tag list",
    "Nbt List from tag List",
    "Nbt List from Tag list",
    "Nbt List from Tag List",
    "Nbt List From tag list",
    "Nbt List From tag List",
    "Nbt List From Tag list",
    "Nbt List From Tag List",
    "NBT list from tag list",
    "NBT list from tag List",
    "NBT list from Tag list",
    "NBT list from Tag List",
    "NBT list From tag list",
    "NBT list From tag List",
    "NBT list From Tag list",
    "NBT list From Tag List",
    "NBT List from tag list",
    "NBT List from tag List",
    "NBT List from Tag list",
    "NBT List from Tag List",
    "NBT List From tag list",
    "NBT List From tag List",
    "NBT List From Tag list",
    "NBT List From Tag List",
    "nbt nbt list from tag list",
    "nbt nbt list from tag List",
    "nbt nbt list from Tag list",
    "nbt nbt list from Tag List",
    "nbt nbt list From tag list",
    "nbt nbt list From tag List",
    "nbt nbt list From Tag list",
    "nbt nbt list From Tag List",
    "nbt nbt List from tag list",
    "nbt nbt List from tag List",
    "nbt nbt List from Tag list",
    "nbt nbt List from Tag List",
    "nbt nbt List From tag list",
    "nbt nbt List From tag List",
    "nbt nbt List From Tag list",
    "nbt nbt List From Tag List",
    "nbt Nbt list from tag list",
    "nbt Nbt list from tag List",
    "nbt Nbt list from Tag list",
    "nbt Nbt list from Tag List",
    "nbt Nbt list From tag list",
    "nbt Nbt list From tag List",
    "nbt Nbt list From Tag list",
    "nbt Nbt list From Tag List",
    "nbt Nbt List from tag list",
    "nbt Nbt List from tag List",
    "nbt Nbt List from Tag list",
    "nbt Nbt List from Tag List",
    "nbt Nbt List From tag list",
    "nbt Nbt List From tag List",
    "nbt Nbt List From Tag list",
    "nbt Nbt List From Tag List",
    "Nbt nbt list from tag list",
    "Nbt nbt list from tag List",
    "Nbt nbt list from Tag list",
    "Nbt nbt list from Tag List",
    "Nbt nbt list From tag list",
    "Nbt nbt list From tag List",
    "Nbt nbt list From Tag list",
    "Nbt nbt list From Tag List",
    "Nbt nbt List from tag list",
    "Nbt nbt List from tag List",
    "Nbt nbt List from Tag list",
    "Nbt nbt List from Tag List",
    "Nbt nbt List From tag list",
    "Nbt nbt List From tag List",
    "Nbt nbt List From Tag list",
    "Nbt nbt List From Tag List",
    "Nbt Nbt list from tag list",
    "Nbt Nbt list from tag List",
    "Nbt Nbt list from Tag list",
    "Nbt Nbt list from Tag List",
    "Nbt Nbt list From tag list",
    "Nbt Nbt list From tag List",
    "Nbt Nbt list From Tag list",
    "Nbt Nbt list From Tag List",
    "Nbt Nbt List from tag list",
    "Nbt Nbt List from tag List",
    "Nbt Nbt List from Tag list",
    "Nbt Nbt List from Tag List",
    "Nbt Nbt List From tag list",
    "Nbt Nbt List From tag List",
    "Nbt Nbt List From Tag list",
    "Nbt Nbt List From Tag List",
    "nbt NBT list from tag list",
    "nbt NBT list from tag List",
    "nbt NBT list from Tag list",
    "nbt NBT list from Tag List",
    "nbt NBT list From tag list",
    "nbt NBT list From tag List",
    "nbt NBT list From Tag list",
    "nbt NBT list From Tag List",
    "nbt NBT List from tag list",
    "nbt NBT List from tag List",
    "nbt NBT List from Tag list",
    "nbt NBT List from Tag List",
    "nbt NBT List From tag list",
    "nbt NBT List From tag List",
    "nbt NBT List From Tag list",
    "nbt NBT List From Tag List",
    "Nbt NBT list from tag list",
    "Nbt NBT list from tag List",
    "Nbt NBT list from Tag list",
    "Nbt NBT list from Tag List",
    "Nbt NBT list From tag list",
    "Nbt NBT list From tag List",
    "Nbt NBT list From Tag list",
    "Nbt NBT list From Tag List",
    "Nbt NBT List from tag list",
    "Nbt NBT List from tag List",
    "Nbt NBT List from Tag list",
    "Nbt NBT List from Tag List",
    "Nbt NBT List From tag list",
    "Nbt NBT List From tag List",
    "Nbt NBT List From Tag list",
    "Nbt NBT List From Tag List",
    "NBT nbt list from tag list",
    "NBT nbt list from tag List",
    "NBT nbt list from Tag list",
    "NBT nbt list from Tag List",
    "NBT nbt list From tag list",
    "NBT nbt list From tag List",
    "NBT nbt list From Tag list",
    "NBT nbt list From Tag List",
    "NBT nbt List from tag list",
    "NBT nbt List from tag List",
    "NBT nbt List from Tag list",
    "NBT nbt List from Tag List",
    "NBT nbt List From tag list",
    "NBT nbt List From tag List",
    "NBT nbt List From Tag list",
    "NBT nbt List From Tag List",
    "NBT Nbt list from tag list",
    "NBT Nbt list from tag List",
    "NBT Nbt list from Tag list",
    "NBT Nbt list from Tag List",
    "NBT Nbt list From tag list",
    "NBT Nbt list From tag List",
    "NBT Nbt list From Tag list",
    "NBT Nbt list From Tag List",
    "NBT Nbt List from tag list",
    "NBT Nbt List from tag List",
    "NBT Nbt List from Tag list",
    "NBT Nbt List from Tag List",
    "NBT Nbt List From tag list",
    "NBT Nbt List From tag List",
    "NBT Nbt List From Tag list",
    "NBT Nbt List From Tag List",
    "NBT NBT list from tag list",
    "NBT NBT list from tag List",
    "NBT NBT list from Tag list",
    "NBT NBT list from Tag List",
    "NBT NBT list From tag list",
    "NBT NBT list From tag List",
    "NBT NBT list From Tag list",
    "NBT NBT list From Tag List",
    "NBT NBT List from tag list",
    "NBT NBT List from tag List",
    "NBT NBT List from Tag list",
    "NBT NBT List from Tag List",
    "NBT NBT List From tag list",
    "NBT NBT List From tag List",
    "NBT NBT List From Tag list",
    "NBT NBT List From Tag List",
  ];
  static override tooltipInfo =
    "Create an NBT List tag from the given NBT List value" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "PREFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: { type: "List", listType: { type: "NBT" } },
          to: {
            type: "NBT",
          },
        },
        normalizeSignature
      ),
      function: (tagList: iArray<Tag<IntegratedValue>>): ListTag => {
        return new ListTag(tagList);
      },
    });
  }
}
