import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";

export class OPERATOR_NBT_COMPOUND_WITH_LIST_TAG extends BaseOperator<
  CompoundTag,
  Operator<iString, Operator<iArray<Tag<IntegratedValue>>, CompoundTag>>
> {
  static override internalName =
    "integrateddynamics:nbt_compound_with_list_tag" as const;
  static override numericID = 232;
  static override nicknames = [
    "compoundWithListTag",
    "nbtCompoundWithListTag",
    "NBTWithNBTList",
    "nbtWithTagList",
    "compound_with_list_tag",
    "n_b_t_with_n_b_t_list",
    "nbt_compound_with_list_tag",
    "nbt_with_tag_list",
  ];
  static override symbol = "NBT{}.with_tag_list";
  static override interactName = "nbtWithTagList";
  static override operatorName = "compound_with_list_tag" as const;
  static override displayName = "NBT Compound With NBT List" as const;
  static override fullDisplayName = "NBT NBT Compound With NBT List" as const;
  static override stringDisplayNames = [
    "nbt compound with nbt list",
    "nbt compound with nbt List",
    "nbt compound with Nbt list",
    "nbt compound with Nbt List",
    "nbt compound With nbt list",
    "nbt compound With nbt List",
    "nbt compound With Nbt list",
    "nbt compound With Nbt List",
    "nbt Compound with nbt list",
    "nbt Compound with nbt List",
    "nbt Compound with Nbt list",
    "nbt Compound with Nbt List",
    "nbt Compound With nbt list",
    "nbt Compound With nbt List",
    "nbt Compound With Nbt list",
    "nbt Compound With Nbt List",
    "Nbt compound with nbt list",
    "Nbt compound with nbt List",
    "Nbt compound with Nbt list",
    "Nbt compound with Nbt List",
    "Nbt compound With nbt list",
    "Nbt compound With nbt List",
    "Nbt compound With Nbt list",
    "Nbt compound With Nbt List",
    "Nbt Compound with nbt list",
    "Nbt Compound with nbt List",
    "Nbt Compound with Nbt list",
    "Nbt Compound with Nbt List",
    "Nbt Compound With nbt list",
    "Nbt Compound With nbt List",
    "Nbt Compound With Nbt list",
    "Nbt Compound With Nbt List",
    "nbt compound with NBT list",
    "nbt compound with NBT List",
    "nbt compound With NBT list",
    "nbt compound With NBT List",
    "nbt Compound with NBT list",
    "nbt Compound with NBT List",
    "nbt Compound With NBT list",
    "nbt Compound With NBT List",
    "Nbt compound with NBT list",
    "Nbt compound with NBT List",
    "Nbt compound With NBT list",
    "Nbt compound With NBT List",
    "Nbt Compound with NBT list",
    "Nbt Compound with NBT List",
    "Nbt Compound With NBT list",
    "Nbt Compound With NBT List",
    "NBT compound with nbt list",
    "NBT compound with nbt List",
    "NBT compound with Nbt list",
    "NBT compound with Nbt List",
    "NBT compound With nbt list",
    "NBT compound With nbt List",
    "NBT compound With Nbt list",
    "NBT compound With Nbt List",
    "NBT Compound with nbt list",
    "NBT Compound with nbt List",
    "NBT Compound with Nbt list",
    "NBT Compound with Nbt List",
    "NBT Compound With nbt list",
    "NBT Compound With nbt List",
    "NBT Compound With Nbt list",
    "NBT Compound With Nbt List",
    "NBT compound with NBT list",
    "NBT compound with NBT List",
    "NBT compound With NBT list",
    "NBT compound With NBT List",
    "NBT Compound with NBT list",
    "NBT Compound with NBT List",
    "NBT Compound With NBT list",
    "NBT Compound With NBT List",
    "nbt nbt compound with nbt list",
    "nbt nbt compound with nbt List",
    "nbt nbt compound with Nbt list",
    "nbt nbt compound with Nbt List",
    "nbt nbt compound With nbt list",
    "nbt nbt compound With nbt List",
    "nbt nbt compound With Nbt list",
    "nbt nbt compound With Nbt List",
    "nbt nbt Compound with nbt list",
    "nbt nbt Compound with nbt List",
    "nbt nbt Compound with Nbt list",
    "nbt nbt Compound with Nbt List",
    "nbt nbt Compound With nbt list",
    "nbt nbt Compound With nbt List",
    "nbt nbt Compound With Nbt list",
    "nbt nbt Compound With Nbt List",
    "nbt Nbt compound with nbt list",
    "nbt Nbt compound with nbt List",
    "nbt Nbt compound with Nbt list",
    "nbt Nbt compound with Nbt List",
    "nbt Nbt compound With nbt list",
    "nbt Nbt compound With nbt List",
    "nbt Nbt compound With Nbt list",
    "nbt Nbt compound With Nbt List",
    "nbt Nbt Compound with nbt list",
    "nbt Nbt Compound with nbt List",
    "nbt Nbt Compound with Nbt list",
    "nbt Nbt Compound with Nbt List",
    "nbt Nbt Compound With nbt list",
    "nbt Nbt Compound With nbt List",
    "nbt Nbt Compound With Nbt list",
    "nbt Nbt Compound With Nbt List",
    "Nbt nbt compound with nbt list",
    "Nbt nbt compound with nbt List",
    "Nbt nbt compound with Nbt list",
    "Nbt nbt compound with Nbt List",
    "Nbt nbt compound With nbt list",
    "Nbt nbt compound With nbt List",
    "Nbt nbt compound With Nbt list",
    "Nbt nbt compound With Nbt List",
    "Nbt nbt Compound with nbt list",
    "Nbt nbt Compound with nbt List",
    "Nbt nbt Compound with Nbt list",
    "Nbt nbt Compound with Nbt List",
    "Nbt nbt Compound With nbt list",
    "Nbt nbt Compound With nbt List",
    "Nbt nbt Compound With Nbt list",
    "Nbt nbt Compound With Nbt List",
    "Nbt Nbt compound with nbt list",
    "Nbt Nbt compound with nbt List",
    "Nbt Nbt compound with Nbt list",
    "Nbt Nbt compound with Nbt List",
    "Nbt Nbt compound With nbt list",
    "Nbt Nbt compound With nbt List",
    "Nbt Nbt compound With Nbt list",
    "Nbt Nbt compound With Nbt List",
    "Nbt Nbt Compound with nbt list",
    "Nbt Nbt Compound with nbt List",
    "Nbt Nbt Compound with Nbt list",
    "Nbt Nbt Compound with Nbt List",
    "Nbt Nbt Compound With nbt list",
    "Nbt Nbt Compound With nbt List",
    "Nbt Nbt Compound With Nbt list",
    "Nbt Nbt Compound With Nbt List",
    "nbt nbt compound with NBT list",
    "nbt nbt compound with NBT List",
    "nbt nbt compound With NBT list",
    "nbt nbt compound With NBT List",
    "nbt nbt Compound with NBT list",
    "nbt nbt Compound with NBT List",
    "nbt nbt Compound With NBT list",
    "nbt nbt Compound With NBT List",
    "nbt Nbt compound with NBT list",
    "nbt Nbt compound with NBT List",
    "nbt Nbt compound With NBT list",
    "nbt Nbt compound With NBT List",
    "nbt Nbt Compound with NBT list",
    "nbt Nbt Compound with NBT List",
    "nbt Nbt Compound With NBT list",
    "nbt Nbt Compound With NBT List",
    "Nbt nbt compound with NBT list",
    "Nbt nbt compound with NBT List",
    "Nbt nbt compound With NBT list",
    "Nbt nbt compound With NBT List",
    "Nbt nbt Compound with NBT list",
    "Nbt nbt Compound with NBT List",
    "Nbt nbt Compound With NBT list",
    "Nbt nbt Compound With NBT List",
    "Nbt Nbt compound with NBT list",
    "Nbt Nbt compound with NBT List",
    "Nbt Nbt compound With NBT list",
    "Nbt Nbt compound With NBT List",
    "Nbt Nbt Compound with NBT list",
    "Nbt Nbt Compound with NBT List",
    "Nbt Nbt Compound With NBT list",
    "Nbt Nbt Compound With NBT List",
    "nbt NBT compound with nbt list",
    "nbt NBT compound with nbt List",
    "nbt NBT compound with Nbt list",
    "nbt NBT compound with Nbt List",
    "nbt NBT compound With nbt list",
    "nbt NBT compound With nbt List",
    "nbt NBT compound With Nbt list",
    "nbt NBT compound With Nbt List",
    "nbt NBT Compound with nbt list",
    "nbt NBT Compound with nbt List",
    "nbt NBT Compound with Nbt list",
    "nbt NBT Compound with Nbt List",
    "nbt NBT Compound With nbt list",
    "nbt NBT Compound With nbt List",
    "nbt NBT Compound With Nbt list",
    "nbt NBT Compound With Nbt List",
    "Nbt NBT compound with nbt list",
    "Nbt NBT compound with nbt List",
    "Nbt NBT compound with Nbt list",
    "Nbt NBT compound with Nbt List",
    "Nbt NBT compound With nbt list",
    "Nbt NBT compound With nbt List",
    "Nbt NBT compound With Nbt list",
    "Nbt NBT compound With Nbt List",
    "Nbt NBT Compound with nbt list",
    "Nbt NBT Compound with nbt List",
    "Nbt NBT Compound with Nbt list",
    "Nbt NBT Compound with Nbt List",
    "Nbt NBT Compound With nbt list",
    "Nbt NBT Compound With nbt List",
    "Nbt NBT Compound With Nbt list",
    "Nbt NBT Compound With Nbt List",
    "nbt NBT compound with NBT list",
    "nbt NBT compound with NBT List",
    "nbt NBT compound With NBT list",
    "nbt NBT compound With NBT List",
    "nbt NBT Compound with NBT list",
    "nbt NBT Compound with NBT List",
    "nbt NBT Compound With NBT list",
    "nbt NBT Compound With NBT List",
    "Nbt NBT compound with NBT list",
    "Nbt NBT compound with NBT List",
    "Nbt NBT compound With NBT list",
    "Nbt NBT compound With NBT List",
    "Nbt NBT Compound with NBT list",
    "Nbt NBT Compound with NBT List",
    "Nbt NBT Compound With NBT list",
    "Nbt NBT Compound With NBT List",
    "NBT nbt compound with nbt list",
    "NBT nbt compound with nbt List",
    "NBT nbt compound with Nbt list",
    "NBT nbt compound with Nbt List",
    "NBT nbt compound With nbt list",
    "NBT nbt compound With nbt List",
    "NBT nbt compound With Nbt list",
    "NBT nbt compound With Nbt List",
    "NBT nbt Compound with nbt list",
    "NBT nbt Compound with nbt List",
    "NBT nbt Compound with Nbt list",
    "NBT nbt Compound with Nbt List",
    "NBT nbt Compound With nbt list",
    "NBT nbt Compound With nbt List",
    "NBT nbt Compound With Nbt list",
    "NBT nbt Compound With Nbt List",
    "NBT Nbt compound with nbt list",
    "NBT Nbt compound with nbt List",
    "NBT Nbt compound with Nbt list",
    "NBT Nbt compound with Nbt List",
    "NBT Nbt compound With nbt list",
    "NBT Nbt compound With nbt List",
    "NBT Nbt compound With Nbt list",
    "NBT Nbt compound With Nbt List",
    "NBT Nbt Compound with nbt list",
    "NBT Nbt Compound with nbt List",
    "NBT Nbt Compound with Nbt list",
    "NBT Nbt Compound with Nbt List",
    "NBT Nbt Compound With nbt list",
    "NBT Nbt Compound With nbt List",
    "NBT Nbt Compound With Nbt list",
    "NBT Nbt Compound With Nbt List",
    "NBT nbt compound with NBT list",
    "NBT nbt compound with NBT List",
    "NBT nbt compound With NBT list",
    "NBT nbt compound With NBT List",
    "NBT nbt Compound with NBT list",
    "NBT nbt Compound with NBT List",
    "NBT nbt Compound With NBT list",
    "NBT nbt Compound With NBT List",
    "NBT Nbt compound with NBT list",
    "NBT Nbt compound with NBT List",
    "NBT Nbt compound With NBT list",
    "NBT Nbt compound With NBT List",
    "NBT Nbt Compound with NBT list",
    "NBT Nbt Compound with NBT List",
    "NBT Nbt Compound With NBT list",
    "NBT Nbt Compound With NBT List",
    "NBT NBT compound with nbt list",
    "NBT NBT compound with nbt List",
    "NBT NBT compound with Nbt list",
    "NBT NBT compound with Nbt List",
    "NBT NBT compound With nbt list",
    "NBT NBT compound With nbt List",
    "NBT NBT compound With Nbt list",
    "NBT NBT compound With Nbt List",
    "NBT NBT Compound with nbt list",
    "NBT NBT Compound with nbt List",
    "NBT NBT Compound with Nbt list",
    "NBT NBT Compound with Nbt List",
    "NBT NBT Compound With nbt list",
    "NBT NBT Compound With nbt List",
    "NBT NBT Compound With Nbt list",
    "NBT NBT Compound With Nbt List",
    "NBT NBT compound with NBT list",
    "NBT NBT compound with NBT List",
    "NBT NBT compound With NBT list",
    "NBT NBT compound With NBT List",
    "NBT NBT Compound with NBT list",
    "NBT NBT Compound with NBT List",
    "NBT NBT Compound With NBT list",
    "NBT NBT Compound With NBT List",
  ];
  static override tooltipInfo =
    "Get a copy of the given NBT compound tag with the given NBT List entry" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "INFIX_2_VERYLONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: {
              type: "Function",
              from: { type: "List", listType: { type: "NBT" } },
              to: {
                type: "NBT",
              },
            },
          },
        },
        normalizeSignature
      ),
      function:
        (
          nbt: CompoundTag
        ): TypeLambda<
          iString,
          TypeLambda<iArray<Tag<IntegratedValue>>, CompoundTag>
        > =>
        (key: iString): TypeLambda<iArray<Tag<IntegratedValue>>, CompoundTag> =>
        (value: iArray<Tag<IntegratedValue>>): CompoundTag => {
          return nbt.set(key.valueOf(), new ListTag(value));
        },
    });
  }
}
