import { ByteArrayTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ByteArrayTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Integer } from "lib/JavaNumberClasses/Integer";

export class OPERATOR_NBT_FROM_BYTE_LIST extends BaseOperator<
  iArray<Integer>,
  ByteArrayTag
> {
  static override internalName =
    "integrateddynamics:nbt_from_byte_list" as const;
  static override numericID = 255;
  static override nicknames = [
    "byteListAsNbt",
    "fromByteList",
    "nbtFromByteList",
    "byte_list_as_nbt",
    "from_byte_list",
    "nbt_from_byte_list",
  ];
  static override symbol = "NBT.from_byte_list";
  static override interactName = "byteListAsNbt";
  static override operatorName = "from_byte_list" as const;
  static override displayName = "NBT Byte Array From Byte List" as const;
  static override fullDisplayName =
    "NBT NBT Byte Array From Byte List" as const;
  static override stringDisplayNames = [
    "nbt byte array from byte list",
    "nbt byte array from byte List",
    "nbt byte array from Byte list",
    "nbt byte array from Byte List",
    "nbt byte array From byte list",
    "nbt byte array From byte List",
    "nbt byte array From Byte list",
    "nbt byte array From Byte List",
    "nbt byte Array from byte list",
    "nbt byte Array from byte List",
    "nbt byte Array from Byte list",
    "nbt byte Array from Byte List",
    "nbt byte Array From byte list",
    "nbt byte Array From byte List",
    "nbt byte Array From Byte list",
    "nbt byte Array From Byte List",
    "nbt Byte array from byte list",
    "nbt Byte array from byte List",
    "nbt Byte array from Byte list",
    "nbt Byte array from Byte List",
    "nbt Byte array From byte list",
    "nbt Byte array From byte List",
    "nbt Byte array From Byte list",
    "nbt Byte array From Byte List",
    "nbt Byte Array from byte list",
    "nbt Byte Array from byte List",
    "nbt Byte Array from Byte list",
    "nbt Byte Array from Byte List",
    "nbt Byte Array From byte list",
    "nbt Byte Array From byte List",
    "nbt Byte Array From Byte list",
    "nbt Byte Array From Byte List",
    "Nbt byte array from byte list",
    "Nbt byte array from byte List",
    "Nbt byte array from Byte list",
    "Nbt byte array from Byte List",
    "Nbt byte array From byte list",
    "Nbt byte array From byte List",
    "Nbt byte array From Byte list",
    "Nbt byte array From Byte List",
    "Nbt byte Array from byte list",
    "Nbt byte Array from byte List",
    "Nbt byte Array from Byte list",
    "Nbt byte Array from Byte List",
    "Nbt byte Array From byte list",
    "Nbt byte Array From byte List",
    "Nbt byte Array From Byte list",
    "Nbt byte Array From Byte List",
    "Nbt Byte array from byte list",
    "Nbt Byte array from byte List",
    "Nbt Byte array from Byte list",
    "Nbt Byte array from Byte List",
    "Nbt Byte array From byte list",
    "Nbt Byte array From byte List",
    "Nbt Byte array From Byte list",
    "Nbt Byte array From Byte List",
    "Nbt Byte Array from byte list",
    "Nbt Byte Array from byte List",
    "Nbt Byte Array from Byte list",
    "Nbt Byte Array from Byte List",
    "Nbt Byte Array From byte list",
    "Nbt Byte Array From byte List",
    "Nbt Byte Array From Byte list",
    "Nbt Byte Array From Byte List",
    "NBT byte array from byte list",
    "NBT byte array from byte List",
    "NBT byte array from Byte list",
    "NBT byte array from Byte List",
    "NBT byte array From byte list",
    "NBT byte array From byte List",
    "NBT byte array From Byte list",
    "NBT byte array From Byte List",
    "NBT byte Array from byte list",
    "NBT byte Array from byte List",
    "NBT byte Array from Byte list",
    "NBT byte Array from Byte List",
    "NBT byte Array From byte list",
    "NBT byte Array From byte List",
    "NBT byte Array From Byte list",
    "NBT byte Array From Byte List",
    "NBT Byte array from byte list",
    "NBT Byte array from byte List",
    "NBT Byte array from Byte list",
    "NBT Byte array from Byte List",
    "NBT Byte array From byte list",
    "NBT Byte array From byte List",
    "NBT Byte array From Byte list",
    "NBT Byte array From Byte List",
    "NBT Byte Array from byte list",
    "NBT Byte Array from byte List",
    "NBT Byte Array from Byte list",
    "NBT Byte Array from Byte List",
    "NBT Byte Array From byte list",
    "NBT Byte Array From byte List",
    "NBT Byte Array From Byte list",
    "NBT Byte Array From Byte List",
    "nbt nbt byte array from byte list",
    "nbt nbt byte array from byte List",
    "nbt nbt byte array from Byte list",
    "nbt nbt byte array from Byte List",
    "nbt nbt byte array From byte list",
    "nbt nbt byte array From byte List",
    "nbt nbt byte array From Byte list",
    "nbt nbt byte array From Byte List",
    "nbt nbt byte Array from byte list",
    "nbt nbt byte Array from byte List",
    "nbt nbt byte Array from Byte list",
    "nbt nbt byte Array from Byte List",
    "nbt nbt byte Array From byte list",
    "nbt nbt byte Array From byte List",
    "nbt nbt byte Array From Byte list",
    "nbt nbt byte Array From Byte List",
    "nbt nbt Byte array from byte list",
    "nbt nbt Byte array from byte List",
    "nbt nbt Byte array from Byte list",
    "nbt nbt Byte array from Byte List",
    "nbt nbt Byte array From byte list",
    "nbt nbt Byte array From byte List",
    "nbt nbt Byte array From Byte list",
    "nbt nbt Byte array From Byte List",
    "nbt nbt Byte Array from byte list",
    "nbt nbt Byte Array from byte List",
    "nbt nbt Byte Array from Byte list",
    "nbt nbt Byte Array from Byte List",
    "nbt nbt Byte Array From byte list",
    "nbt nbt Byte Array From byte List",
    "nbt nbt Byte Array From Byte list",
    "nbt nbt Byte Array From Byte List",
    "nbt Nbt byte array from byte list",
    "nbt Nbt byte array from byte List",
    "nbt Nbt byte array from Byte list",
    "nbt Nbt byte array from Byte List",
    "nbt Nbt byte array From byte list",
    "nbt Nbt byte array From byte List",
    "nbt Nbt byte array From Byte list",
    "nbt Nbt byte array From Byte List",
    "nbt Nbt byte Array from byte list",
    "nbt Nbt byte Array from byte List",
    "nbt Nbt byte Array from Byte list",
    "nbt Nbt byte Array from Byte List",
    "nbt Nbt byte Array From byte list",
    "nbt Nbt byte Array From byte List",
    "nbt Nbt byte Array From Byte list",
    "nbt Nbt byte Array From Byte List",
    "nbt Nbt Byte array from byte list",
    "nbt Nbt Byte array from byte List",
    "nbt Nbt Byte array from Byte list",
    "nbt Nbt Byte array from Byte List",
    "nbt Nbt Byte array From byte list",
    "nbt Nbt Byte array From byte List",
    "nbt Nbt Byte array From Byte list",
    "nbt Nbt Byte array From Byte List",
    "nbt Nbt Byte Array from byte list",
    "nbt Nbt Byte Array from byte List",
    "nbt Nbt Byte Array from Byte list",
    "nbt Nbt Byte Array from Byte List",
    "nbt Nbt Byte Array From byte list",
    "nbt Nbt Byte Array From byte List",
    "nbt Nbt Byte Array From Byte list",
    "nbt Nbt Byte Array From Byte List",
    "Nbt nbt byte array from byte list",
    "Nbt nbt byte array from byte List",
    "Nbt nbt byte array from Byte list",
    "Nbt nbt byte array from Byte List",
    "Nbt nbt byte array From byte list",
    "Nbt nbt byte array From byte List",
    "Nbt nbt byte array From Byte list",
    "Nbt nbt byte array From Byte List",
    "Nbt nbt byte Array from byte list",
    "Nbt nbt byte Array from byte List",
    "Nbt nbt byte Array from Byte list",
    "Nbt nbt byte Array from Byte List",
    "Nbt nbt byte Array From byte list",
    "Nbt nbt byte Array From byte List",
    "Nbt nbt byte Array From Byte list",
    "Nbt nbt byte Array From Byte List",
    "Nbt nbt Byte array from byte list",
    "Nbt nbt Byte array from byte List",
    "Nbt nbt Byte array from Byte list",
    "Nbt nbt Byte array from Byte List",
    "Nbt nbt Byte array From byte list",
    "Nbt nbt Byte array From byte List",
    "Nbt nbt Byte array From Byte list",
    "Nbt nbt Byte array From Byte List",
    "Nbt nbt Byte Array from byte list",
    "Nbt nbt Byte Array from byte List",
    "Nbt nbt Byte Array from Byte list",
    "Nbt nbt Byte Array from Byte List",
    "Nbt nbt Byte Array From byte list",
    "Nbt nbt Byte Array From byte List",
    "Nbt nbt Byte Array From Byte list",
    "Nbt nbt Byte Array From Byte List",
    "Nbt Nbt byte array from byte list",
    "Nbt Nbt byte array from byte List",
    "Nbt Nbt byte array from Byte list",
    "Nbt Nbt byte array from Byte List",
    "Nbt Nbt byte array From byte list",
    "Nbt Nbt byte array From byte List",
    "Nbt Nbt byte array From Byte list",
    "Nbt Nbt byte array From Byte List",
    "Nbt Nbt byte Array from byte list",
    "Nbt Nbt byte Array from byte List",
    "Nbt Nbt byte Array from Byte list",
    "Nbt Nbt byte Array from Byte List",
    "Nbt Nbt byte Array From byte list",
    "Nbt Nbt byte Array From byte List",
    "Nbt Nbt byte Array From Byte list",
    "Nbt Nbt byte Array From Byte List",
    "Nbt Nbt Byte array from byte list",
    "Nbt Nbt Byte array from byte List",
    "Nbt Nbt Byte array from Byte list",
    "Nbt Nbt Byte array from Byte List",
    "Nbt Nbt Byte array From byte list",
    "Nbt Nbt Byte array From byte List",
    "Nbt Nbt Byte array From Byte list",
    "Nbt Nbt Byte array From Byte List",
    "Nbt Nbt Byte Array from byte list",
    "Nbt Nbt Byte Array from byte List",
    "Nbt Nbt Byte Array from Byte list",
    "Nbt Nbt Byte Array from Byte List",
    "Nbt Nbt Byte Array From byte list",
    "Nbt Nbt Byte Array From byte List",
    "Nbt Nbt Byte Array From Byte list",
    "Nbt Nbt Byte Array From Byte List",
    "nbt NBT byte array from byte list",
    "nbt NBT byte array from byte List",
    "nbt NBT byte array from Byte list",
    "nbt NBT byte array from Byte List",
    "nbt NBT byte array From byte list",
    "nbt NBT byte array From byte List",
    "nbt NBT byte array From Byte list",
    "nbt NBT byte array From Byte List",
    "nbt NBT byte Array from byte list",
    "nbt NBT byte Array from byte List",
    "nbt NBT byte Array from Byte list",
    "nbt NBT byte Array from Byte List",
    "nbt NBT byte Array From byte list",
    "nbt NBT byte Array From byte List",
    "nbt NBT byte Array From Byte list",
    "nbt NBT byte Array From Byte List",
    "nbt NBT Byte array from byte list",
    "nbt NBT Byte array from byte List",
    "nbt NBT Byte array from Byte list",
    "nbt NBT Byte array from Byte List",
    "nbt NBT Byte array From byte list",
    "nbt NBT Byte array From byte List",
    "nbt NBT Byte array From Byte list",
    "nbt NBT Byte array From Byte List",
    "nbt NBT Byte Array from byte list",
    "nbt NBT Byte Array from byte List",
    "nbt NBT Byte Array from Byte list",
    "nbt NBT Byte Array from Byte List",
    "nbt NBT Byte Array From byte list",
    "nbt NBT Byte Array From byte List",
    "nbt NBT Byte Array From Byte list",
    "nbt NBT Byte Array From Byte List",
    "Nbt NBT byte array from byte list",
    "Nbt NBT byte array from byte List",
    "Nbt NBT byte array from Byte list",
    "Nbt NBT byte array from Byte List",
    "Nbt NBT byte array From byte list",
    "Nbt NBT byte array From byte List",
    "Nbt NBT byte array From Byte list",
    "Nbt NBT byte array From Byte List",
    "Nbt NBT byte Array from byte list",
    "Nbt NBT byte Array from byte List",
    "Nbt NBT byte Array from Byte list",
    "Nbt NBT byte Array from Byte List",
    "Nbt NBT byte Array From byte list",
    "Nbt NBT byte Array From byte List",
    "Nbt NBT byte Array From Byte list",
    "Nbt NBT byte Array From Byte List",
    "Nbt NBT Byte array from byte list",
    "Nbt NBT Byte array from byte List",
    "Nbt NBT Byte array from Byte list",
    "Nbt NBT Byte array from Byte List",
    "Nbt NBT Byte array From byte list",
    "Nbt NBT Byte array From byte List",
    "Nbt NBT Byte array From Byte list",
    "Nbt NBT Byte array From Byte List",
    "Nbt NBT Byte Array from byte list",
    "Nbt NBT Byte Array from byte List",
    "Nbt NBT Byte Array from Byte list",
    "Nbt NBT Byte Array from Byte List",
    "Nbt NBT Byte Array From byte list",
    "Nbt NBT Byte Array From byte List",
    "Nbt NBT Byte Array From Byte list",
    "Nbt NBT Byte Array From Byte List",
    "NBT nbt byte array from byte list",
    "NBT nbt byte array from byte List",
    "NBT nbt byte array from Byte list",
    "NBT nbt byte array from Byte List",
    "NBT nbt byte array From byte list",
    "NBT nbt byte array From byte List",
    "NBT nbt byte array From Byte list",
    "NBT nbt byte array From Byte List",
    "NBT nbt byte Array from byte list",
    "NBT nbt byte Array from byte List",
    "NBT nbt byte Array from Byte list",
    "NBT nbt byte Array from Byte List",
    "NBT nbt byte Array From byte list",
    "NBT nbt byte Array From byte List",
    "NBT nbt byte Array From Byte list",
    "NBT nbt byte Array From Byte List",
    "NBT nbt Byte array from byte list",
    "NBT nbt Byte array from byte List",
    "NBT nbt Byte array from Byte list",
    "NBT nbt Byte array from Byte List",
    "NBT nbt Byte array From byte list",
    "NBT nbt Byte array From byte List",
    "NBT nbt Byte array From Byte list",
    "NBT nbt Byte array From Byte List",
    "NBT nbt Byte Array from byte list",
    "NBT nbt Byte Array from byte List",
    "NBT nbt Byte Array from Byte list",
    "NBT nbt Byte Array from Byte List",
    "NBT nbt Byte Array From byte list",
    "NBT nbt Byte Array From byte List",
    "NBT nbt Byte Array From Byte list",
    "NBT nbt Byte Array From Byte List",
    "NBT Nbt byte array from byte list",
    "NBT Nbt byte array from byte List",
    "NBT Nbt byte array from Byte list",
    "NBT Nbt byte array from Byte List",
    "NBT Nbt byte array From byte list",
    "NBT Nbt byte array From byte List",
    "NBT Nbt byte array From Byte list",
    "NBT Nbt byte array From Byte List",
    "NBT Nbt byte Array from byte list",
    "NBT Nbt byte Array from byte List",
    "NBT Nbt byte Array from Byte list",
    "NBT Nbt byte Array from Byte List",
    "NBT Nbt byte Array From byte list",
    "NBT Nbt byte Array From byte List",
    "NBT Nbt byte Array From Byte list",
    "NBT Nbt byte Array From Byte List",
    "NBT Nbt Byte array from byte list",
    "NBT Nbt Byte array from byte List",
    "NBT Nbt Byte array from Byte list",
    "NBT Nbt Byte array from Byte List",
    "NBT Nbt Byte array From byte list",
    "NBT Nbt Byte array From byte List",
    "NBT Nbt Byte array From Byte list",
    "NBT Nbt Byte array From Byte List",
    "NBT Nbt Byte Array from byte list",
    "NBT Nbt Byte Array from byte List",
    "NBT Nbt Byte Array from Byte list",
    "NBT Nbt Byte Array from Byte List",
    "NBT Nbt Byte Array From byte list",
    "NBT Nbt Byte Array From byte List",
    "NBT Nbt Byte Array From Byte list",
    "NBT Nbt Byte Array From Byte List",
    "NBT NBT byte array from byte list",
    "NBT NBT byte array from byte List",
    "NBT NBT byte array from Byte list",
    "NBT NBT byte array from Byte List",
    "NBT NBT byte array From byte list",
    "NBT NBT byte array From byte List",
    "NBT NBT byte array From Byte list",
    "NBT NBT byte array From Byte List",
    "NBT NBT byte Array from byte list",
    "NBT NBT byte Array from byte List",
    "NBT NBT byte Array from Byte list",
    "NBT NBT byte Array from Byte List",
    "NBT NBT byte Array From byte list",
    "NBT NBT byte Array From byte List",
    "NBT NBT byte Array From Byte list",
    "NBT NBT byte Array From Byte List",
    "NBT NBT Byte array from byte list",
    "NBT NBT Byte array from byte List",
    "NBT NBT Byte array from Byte list",
    "NBT NBT Byte array from Byte List",
    "NBT NBT Byte array From byte list",
    "NBT NBT Byte array From byte List",
    "NBT NBT Byte array From Byte list",
    "NBT NBT Byte array From Byte List",
    "NBT NBT Byte Array from byte list",
    "NBT NBT Byte Array from byte List",
    "NBT NBT Byte Array from Byte list",
    "NBT NBT Byte Array from Byte List",
    "NBT NBT Byte Array From byte list",
    "NBT NBT Byte Array From byte List",
    "NBT NBT Byte Array From Byte list",
    "NBT NBT Byte Array From Byte List",
  ];
  static override tooltipInfo =
    "Create an NBT Byte Array tag from the given Integer List value" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "PREFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: { type: "List", listType: { type: "Integer" } },
          to: {
            type: "NBT",
          },
        },
        normalizeSignature
      ),
      function: (byteList: iArray<Integer>): ByteArrayTag => {
        return new ByteArrayTag(byteList);
      },
    });
  }
}
