import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";

export class OPERATOR_NBT_AS_TAG_LIST extends BaseOperator<
  ListTag,
  iArray<Tag<IntegratedValue>>
> {
  static override internalName = "integrateddynamics:nbt_as_tag_list" as const;
  static override numericID = 253;
  static override nicknames = [
    "asTagList",
    "nbtAsTagList",
    "as_tag_list",
    "nbt_as_tag_list",
  ];
  static override symbol = "NBT.as_tag_list";
  static override interactName = "nbtAsTagList";
  static override operatorName = "as_tag_list" as const;
  static override displayName = "NBT List As NBT List" as const;
  static override fullDisplayName = "NBT NBT List As NBT List" as const;
  static override stringDisplayNames = [
    "nbt list as nbt list",
    "nbt list as nbt List",
    "nbt list as Nbt list",
    "nbt list as Nbt List",
    "nbt list As nbt list",
    "nbt list As nbt List",
    "nbt list As Nbt list",
    "nbt list As Nbt List",
    "nbt List as nbt list",
    "nbt List as nbt List",
    "nbt List as Nbt list",
    "nbt List as Nbt List",
    "nbt List As nbt list",
    "nbt List As nbt List",
    "nbt List As Nbt list",
    "nbt List As Nbt List",
    "Nbt list as nbt list",
    "Nbt list as nbt List",
    "Nbt list as Nbt list",
    "Nbt list as Nbt List",
    "Nbt list As nbt list",
    "Nbt list As nbt List",
    "Nbt list As Nbt list",
    "Nbt list As Nbt List",
    "Nbt List as nbt list",
    "Nbt List as nbt List",
    "Nbt List as Nbt list",
    "Nbt List as Nbt List",
    "Nbt List As nbt list",
    "Nbt List As nbt List",
    "Nbt List As Nbt list",
    "Nbt List As Nbt List",
    "nbt list as NBT list",
    "nbt list as NBT List",
    "nbt list As NBT list",
    "nbt list As NBT List",
    "nbt List as NBT list",
    "nbt List as NBT List",
    "nbt List As NBT list",
    "nbt List As NBT List",
    "Nbt list as NBT list",
    "Nbt list as NBT List",
    "Nbt list As NBT list",
    "Nbt list As NBT List",
    "Nbt List as NBT list",
    "Nbt List as NBT List",
    "Nbt List As NBT list",
    "Nbt List As NBT List",
    "NBT list as nbt list",
    "NBT list as nbt List",
    "NBT list as Nbt list",
    "NBT list as Nbt List",
    "NBT list As nbt list",
    "NBT list As nbt List",
    "NBT list As Nbt list",
    "NBT list As Nbt List",
    "NBT List as nbt list",
    "NBT List as nbt List",
    "NBT List as Nbt list",
    "NBT List as Nbt List",
    "NBT List As nbt list",
    "NBT List As nbt List",
    "NBT List As Nbt list",
    "NBT List As Nbt List",
    "NBT list as NBT list",
    "NBT list as NBT List",
    "NBT list As NBT list",
    "NBT list As NBT List",
    "NBT List as NBT list",
    "NBT List as NBT List",
    "NBT List As NBT list",
    "NBT List As NBT List",
    "nbt nbt list as nbt list",
    "nbt nbt list as nbt List",
    "nbt nbt list as Nbt list",
    "nbt nbt list as Nbt List",
    "nbt nbt list As nbt list",
    "nbt nbt list As nbt List",
    "nbt nbt list As Nbt list",
    "nbt nbt list As Nbt List",
    "nbt nbt List as nbt list",
    "nbt nbt List as nbt List",
    "nbt nbt List as Nbt list",
    "nbt nbt List as Nbt List",
    "nbt nbt List As nbt list",
    "nbt nbt List As nbt List",
    "nbt nbt List As Nbt list",
    "nbt nbt List As Nbt List",
    "nbt Nbt list as nbt list",
    "nbt Nbt list as nbt List",
    "nbt Nbt list as Nbt list",
    "nbt Nbt list as Nbt List",
    "nbt Nbt list As nbt list",
    "nbt Nbt list As nbt List",
    "nbt Nbt list As Nbt list",
    "nbt Nbt list As Nbt List",
    "nbt Nbt List as nbt list",
    "nbt Nbt List as nbt List",
    "nbt Nbt List as Nbt list",
    "nbt Nbt List as Nbt List",
    "nbt Nbt List As nbt list",
    "nbt Nbt List As nbt List",
    "nbt Nbt List As Nbt list",
    "nbt Nbt List As Nbt List",
    "Nbt nbt list as nbt list",
    "Nbt nbt list as nbt List",
    "Nbt nbt list as Nbt list",
    "Nbt nbt list as Nbt List",
    "Nbt nbt list As nbt list",
    "Nbt nbt list As nbt List",
    "Nbt nbt list As Nbt list",
    "Nbt nbt list As Nbt List",
    "Nbt nbt List as nbt list",
    "Nbt nbt List as nbt List",
    "Nbt nbt List as Nbt list",
    "Nbt nbt List as Nbt List",
    "Nbt nbt List As nbt list",
    "Nbt nbt List As nbt List",
    "Nbt nbt List As Nbt list",
    "Nbt nbt List As Nbt List",
    "Nbt Nbt list as nbt list",
    "Nbt Nbt list as nbt List",
    "Nbt Nbt list as Nbt list",
    "Nbt Nbt list as Nbt List",
    "Nbt Nbt list As nbt list",
    "Nbt Nbt list As nbt List",
    "Nbt Nbt list As Nbt list",
    "Nbt Nbt list As Nbt List",
    "Nbt Nbt List as nbt list",
    "Nbt Nbt List as nbt List",
    "Nbt Nbt List as Nbt list",
    "Nbt Nbt List as Nbt List",
    "Nbt Nbt List As nbt list",
    "Nbt Nbt List As nbt List",
    "Nbt Nbt List As Nbt list",
    "Nbt Nbt List As Nbt List",
    "nbt nbt list as NBT list",
    "nbt nbt list as NBT List",
    "nbt nbt list As NBT list",
    "nbt nbt list As NBT List",
    "nbt nbt List as NBT list",
    "nbt nbt List as NBT List",
    "nbt nbt List As NBT list",
    "nbt nbt List As NBT List",
    "nbt Nbt list as NBT list",
    "nbt Nbt list as NBT List",
    "nbt Nbt list As NBT list",
    "nbt Nbt list As NBT List",
    "nbt Nbt List as NBT list",
    "nbt Nbt List as NBT List",
    "nbt Nbt List As NBT list",
    "nbt Nbt List As NBT List",
    "Nbt nbt list as NBT list",
    "Nbt nbt list as NBT List",
    "Nbt nbt list As NBT list",
    "Nbt nbt list As NBT List",
    "Nbt nbt List as NBT list",
    "Nbt nbt List as NBT List",
    "Nbt nbt List As NBT list",
    "Nbt nbt List As NBT List",
    "Nbt Nbt list as NBT list",
    "Nbt Nbt list as NBT List",
    "Nbt Nbt list As NBT list",
    "Nbt Nbt list As NBT List",
    "Nbt Nbt List as NBT list",
    "Nbt Nbt List as NBT List",
    "Nbt Nbt List As NBT list",
    "Nbt Nbt List As NBT List",
    "nbt NBT list as nbt list",
    "nbt NBT list as nbt List",
    "nbt NBT list as Nbt list",
    "nbt NBT list as Nbt List",
    "nbt NBT list As nbt list",
    "nbt NBT list As nbt List",
    "nbt NBT list As Nbt list",
    "nbt NBT list As Nbt List",
    "nbt NBT List as nbt list",
    "nbt NBT List as nbt List",
    "nbt NBT List as Nbt list",
    "nbt NBT List as Nbt List",
    "nbt NBT List As nbt list",
    "nbt NBT List As nbt List",
    "nbt NBT List As Nbt list",
    "nbt NBT List As Nbt List",
    "Nbt NBT list as nbt list",
    "Nbt NBT list as nbt List",
    "Nbt NBT list as Nbt list",
    "Nbt NBT list as Nbt List",
    "Nbt NBT list As nbt list",
    "Nbt NBT list As nbt List",
    "Nbt NBT list As Nbt list",
    "Nbt NBT list As Nbt List",
    "Nbt NBT List as nbt list",
    "Nbt NBT List as nbt List",
    "Nbt NBT List as Nbt list",
    "Nbt NBT List as Nbt List",
    "Nbt NBT List As nbt list",
    "Nbt NBT List As nbt List",
    "Nbt NBT List As Nbt list",
    "Nbt NBT List As Nbt List",
    "nbt NBT list as NBT list",
    "nbt NBT list as NBT List",
    "nbt NBT list As NBT list",
    "nbt NBT list As NBT List",
    "nbt NBT List as NBT list",
    "nbt NBT List as NBT List",
    "nbt NBT List As NBT list",
    "nbt NBT List As NBT List",
    "Nbt NBT list as NBT list",
    "Nbt NBT list as NBT List",
    "Nbt NBT list As NBT list",
    "Nbt NBT list As NBT List",
    "Nbt NBT List as NBT list",
    "Nbt NBT List as NBT List",
    "Nbt NBT List As NBT list",
    "Nbt NBT List As NBT List",
    "NBT nbt list as nbt list",
    "NBT nbt list as nbt List",
    "NBT nbt list as Nbt list",
    "NBT nbt list as Nbt List",
    "NBT nbt list As nbt list",
    "NBT nbt list As nbt List",
    "NBT nbt list As Nbt list",
    "NBT nbt list As Nbt List",
    "NBT nbt List as nbt list",
    "NBT nbt List as nbt List",
    "NBT nbt List as Nbt list",
    "NBT nbt List as Nbt List",
    "NBT nbt List As nbt list",
    "NBT nbt List As nbt List",
    "NBT nbt List As Nbt list",
    "NBT nbt List As Nbt List",
    "NBT Nbt list as nbt list",
    "NBT Nbt list as nbt List",
    "NBT Nbt list as Nbt list",
    "NBT Nbt list as Nbt List",
    "NBT Nbt list As nbt list",
    "NBT Nbt list As nbt List",
    "NBT Nbt list As Nbt list",
    "NBT Nbt list As Nbt List",
    "NBT Nbt List as nbt list",
    "NBT Nbt List as nbt List",
    "NBT Nbt List as Nbt list",
    "NBT Nbt List as Nbt List",
    "NBT Nbt List As nbt list",
    "NBT Nbt List As nbt List",
    "NBT Nbt List As Nbt list",
    "NBT Nbt List As Nbt List",
    "NBT nbt list as NBT list",
    "NBT nbt list as NBT List",
    "NBT nbt list As NBT list",
    "NBT nbt list As NBT List",
    "NBT nbt List as NBT list",
    "NBT nbt List as NBT List",
    "NBT nbt List As NBT list",
    "NBT nbt List As NBT List",
    "NBT Nbt list as NBT list",
    "NBT Nbt list as NBT List",
    "NBT Nbt list As NBT list",
    "NBT Nbt list As NBT List",
    "NBT Nbt List as NBT list",
    "NBT Nbt List as NBT List",
    "NBT Nbt List As NBT list",
    "NBT Nbt List As NBT List",
    "NBT NBT list as nbt list",
    "NBT NBT list as nbt List",
    "NBT NBT list as Nbt list",
    "NBT NBT list as Nbt List",
    "NBT NBT list As nbt list",
    "NBT NBT list As nbt List",
    "NBT NBT list As Nbt list",
    "NBT NBT list As Nbt List",
    "NBT NBT List as nbt list",
    "NBT NBT List as nbt List",
    "NBT NBT List as Nbt list",
    "NBT NBT List as Nbt List",
    "NBT NBT List As nbt list",
    "NBT NBT List As nbt List",
    "NBT NBT List As Nbt list",
    "NBT NBT List As Nbt List",
    "NBT NBT list as NBT list",
    "NBT NBT list as NBT List",
    "NBT NBT list As NBT list",
    "NBT NBT list As NBT List",
    "NBT NBT List as NBT list",
    "NBT NBT List as NBT List",
    "NBT NBT List As NBT list",
    "NBT NBT List As NBT List",
  ];
  static override tooltipInfo =
    "Get the NBT List value of the given NBT List tag" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: { type: "List", listType: { type: "NBT" } },
        },
        normalizeSignature
      ),
      function: (nbt: ListTag): iArray<Tag<IntegratedValue>> => {
        if (nbt.getType() === Tag.TAG_LIST) {
          return nbt.valueOf();
        } else {
          return new iArrayEager<Tag<any>>([]);
        }
      },
    });
  }
}
