import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Integer } from "lib/JavaNumberClasses/Integer";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { IntArrayTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/IntArrayTag";

export class OPERATOR_NBT_COMPOUND_WITH_LIST_INT extends BaseOperator<
  CompoundTag,
  Operator<iString, Operator<iArray<Integer>, CompoundTag>>
> {
  static override internalName =
    "integrateddynamics:nbt_compound_with_list_int" as const;
  static override numericID = 230;
  static override nicknames = [
    "compoundWithListInt",
    "nbtCompoundWithListInt",
    "NBTWithIntegerList",
    "nbtWithIntList",
    "compound_with_list_int",
    "n_b_t_with_integer_list",
    "nbt_compound_with_list_int",
    "nbt_with_int_list",
  ];
  static override symbol = "NBT{}.with_int_list";
  static override interactName = "nbtWithIntList";
  static override operatorName = "compound_with_list_int" as const;
  static override displayName = "NBT Compound With Int List" as const;
  static override fullDisplayName = "NBT NBT Compound With Int List" as const;
  static override stringDisplayNames = [
    "nbt compound with int list",
    "nbt compound with int List",
    "nbt compound with Int list",
    "nbt compound with Int List",
    "nbt compound With int list",
    "nbt compound With int List",
    "nbt compound With Int list",
    "nbt compound With Int List",
    "nbt Compound with int list",
    "nbt Compound with int List",
    "nbt Compound with Int list",
    "nbt Compound with Int List",
    "nbt Compound With int list",
    "nbt Compound With int List",
    "nbt Compound With Int list",
    "nbt Compound With Int List",
    "Nbt compound with int list",
    "Nbt compound with int List",
    "Nbt compound with Int list",
    "Nbt compound with Int List",
    "Nbt compound With int list",
    "Nbt compound With int List",
    "Nbt compound With Int list",
    "Nbt compound With Int List",
    "Nbt Compound with int list",
    "Nbt Compound with int List",
    "Nbt Compound with Int list",
    "Nbt Compound with Int List",
    "Nbt Compound With int list",
    "Nbt Compound With int List",
    "Nbt Compound With Int list",
    "Nbt Compound With Int List",
    "NBT compound with int list",
    "NBT compound with int List",
    "NBT compound with Int list",
    "NBT compound with Int List",
    "NBT compound With int list",
    "NBT compound With int List",
    "NBT compound With Int list",
    "NBT compound With Int List",
    "NBT Compound with int list",
    "NBT Compound with int List",
    "NBT Compound with Int list",
    "NBT Compound with Int List",
    "NBT Compound With int list",
    "NBT Compound With int List",
    "NBT Compound With Int list",
    "NBT Compound With Int List",
    "nbt nbt compound with int list",
    "nbt nbt compound with int List",
    "nbt nbt compound with Int list",
    "nbt nbt compound with Int List",
    "nbt nbt compound With int list",
    "nbt nbt compound With int List",
    "nbt nbt compound With Int list",
    "nbt nbt compound With Int List",
    "nbt nbt Compound with int list",
    "nbt nbt Compound with int List",
    "nbt nbt Compound with Int list",
    "nbt nbt Compound with Int List",
    "nbt nbt Compound With int list",
    "nbt nbt Compound With int List",
    "nbt nbt Compound With Int list",
    "nbt nbt Compound With Int List",
    "nbt Nbt compound with int list",
    "nbt Nbt compound with int List",
    "nbt Nbt compound with Int list",
    "nbt Nbt compound with Int List",
    "nbt Nbt compound With int list",
    "nbt Nbt compound With int List",
    "nbt Nbt compound With Int list",
    "nbt Nbt compound With Int List",
    "nbt Nbt Compound with int list",
    "nbt Nbt Compound with int List",
    "nbt Nbt Compound with Int list",
    "nbt Nbt Compound with Int List",
    "nbt Nbt Compound With int list",
    "nbt Nbt Compound With int List",
    "nbt Nbt Compound With Int list",
    "nbt Nbt Compound With Int List",
    "Nbt nbt compound with int list",
    "Nbt nbt compound with int List",
    "Nbt nbt compound with Int list",
    "Nbt nbt compound with Int List",
    "Nbt nbt compound With int list",
    "Nbt nbt compound With int List",
    "Nbt nbt compound With Int list",
    "Nbt nbt compound With Int List",
    "Nbt nbt Compound with int list",
    "Nbt nbt Compound with int List",
    "Nbt nbt Compound with Int list",
    "Nbt nbt Compound with Int List",
    "Nbt nbt Compound With int list",
    "Nbt nbt Compound With int List",
    "Nbt nbt Compound With Int list",
    "Nbt nbt Compound With Int List",
    "Nbt Nbt compound with int list",
    "Nbt Nbt compound with int List",
    "Nbt Nbt compound with Int list",
    "Nbt Nbt compound with Int List",
    "Nbt Nbt compound With int list",
    "Nbt Nbt compound With int List",
    "Nbt Nbt compound With Int list",
    "Nbt Nbt compound With Int List",
    "Nbt Nbt Compound with int list",
    "Nbt Nbt Compound with int List",
    "Nbt Nbt Compound with Int list",
    "Nbt Nbt Compound with Int List",
    "Nbt Nbt Compound With int list",
    "Nbt Nbt Compound With int List",
    "Nbt Nbt Compound With Int list",
    "Nbt Nbt Compound With Int List",
    "nbt NBT compound with int list",
    "nbt NBT compound with int List",
    "nbt NBT compound with Int list",
    "nbt NBT compound with Int List",
    "nbt NBT compound With int list",
    "nbt NBT compound With int List",
    "nbt NBT compound With Int list",
    "nbt NBT compound With Int List",
    "nbt NBT Compound with int list",
    "nbt NBT Compound with int List",
    "nbt NBT Compound with Int list",
    "nbt NBT Compound with Int List",
    "nbt NBT Compound With int list",
    "nbt NBT Compound With int List",
    "nbt NBT Compound With Int list",
    "nbt NBT Compound With Int List",
    "Nbt NBT compound with int list",
    "Nbt NBT compound with int List",
    "Nbt NBT compound with Int list",
    "Nbt NBT compound with Int List",
    "Nbt NBT compound With int list",
    "Nbt NBT compound With int List",
    "Nbt NBT compound With Int list",
    "Nbt NBT compound With Int List",
    "Nbt NBT Compound with int list",
    "Nbt NBT Compound with int List",
    "Nbt NBT Compound with Int list",
    "Nbt NBT Compound with Int List",
    "Nbt NBT Compound With int list",
    "Nbt NBT Compound With int List",
    "Nbt NBT Compound With Int list",
    "Nbt NBT Compound With Int List",
    "NBT nbt compound with int list",
    "NBT nbt compound with int List",
    "NBT nbt compound with Int list",
    "NBT nbt compound with Int List",
    "NBT nbt compound With int list",
    "NBT nbt compound With int List",
    "NBT nbt compound With Int list",
    "NBT nbt compound With Int List",
    "NBT nbt Compound with int list",
    "NBT nbt Compound with int List",
    "NBT nbt Compound with Int list",
    "NBT nbt Compound with Int List",
    "NBT nbt Compound With int list",
    "NBT nbt Compound With int List",
    "NBT nbt Compound With Int list",
    "NBT nbt Compound With Int List",
    "NBT Nbt compound with int list",
    "NBT Nbt compound with int List",
    "NBT Nbt compound with Int list",
    "NBT Nbt compound with Int List",
    "NBT Nbt compound With int list",
    "NBT Nbt compound With int List",
    "NBT Nbt compound With Int list",
    "NBT Nbt compound With Int List",
    "NBT Nbt Compound with int list",
    "NBT Nbt Compound with int List",
    "NBT Nbt Compound with Int list",
    "NBT Nbt Compound with Int List",
    "NBT Nbt Compound With int list",
    "NBT Nbt Compound With int List",
    "NBT Nbt Compound With Int list",
    "NBT Nbt Compound With Int List",
    "NBT NBT compound with int list",
    "NBT NBT compound with int List",
    "NBT NBT compound with Int list",
    "NBT NBT compound with Int List",
    "NBT NBT compound With int list",
    "NBT NBT compound With int List",
    "NBT NBT compound With Int list",
    "NBT NBT compound With Int List",
    "NBT NBT Compound with int list",
    "NBT NBT Compound with int List",
    "NBT NBT Compound with Int list",
    "NBT NBT Compound with Int List",
    "NBT NBT Compound With int list",
    "NBT NBT Compound With int List",
    "NBT NBT Compound With Int list",
    "NBT NBT Compound With Int List",
  ];
  static override tooltipInfo =
    "Get a copy of the given NBT compound tag with the given NBT Integer Array entry" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "INFIX_2_VERYLONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: {
              type: "Function",
              from: { type: "List", listType: { type: "Integer" } },
              to: {
                type: "NBT",
              },
            },
          },
        },
        normalizeSignature
      ),
      function: (
        nbt: CompoundTag
      ): TypeLambda<iString, TypeLambda<iArray<Integer>, CompoundTag>> => {
        return (key: iString): TypeLambda<iArray<Integer>, CompoundTag> => {
          return (value: iArray<Integer>): CompoundTag => {
            return nbt.set(key.valueOf(), new IntArrayTag(value));
          };
        };
      },
    });
  }
}
