import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { Long } from "lib/JavaNumberClasses/Long";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";

export class OPERATOR_NBT_AS_LONG_LIST extends BaseOperator<
  ListTag,
  iArray<Long>
> {
  static override internalName = "integrateddynamics:nbt_as_long_list" as const;
  static override numericID = 250;
  static override nicknames = [
    "asLongList",
    "nbtAsLongList",
    "as_long_list",
    "nbt_as_long_list",
  ];
  static override symbol = "NBT.as_long_list";
  static override interactName = "nbtAsLongList";
  static override operatorName = "as_long_list" as const;
  static override displayName = "NBT Long Array As Long List" as const;
  static override fullDisplayName = "NBT NBT Long Array As Long List" as const;
  static override stringDisplayNames = [
    "nbt long array as long list",
    "nbt long array as long List",
    "nbt long array as Long list",
    "nbt long array as Long List",
    "nbt long array As long list",
    "nbt long array As long List",
    "nbt long array As Long list",
    "nbt long array As Long List",
    "nbt long Array as long list",
    "nbt long Array as long List",
    "nbt long Array as Long list",
    "nbt long Array as Long List",
    "nbt long Array As long list",
    "nbt long Array As long List",
    "nbt long Array As Long list",
    "nbt long Array As Long List",
    "nbt Long array as long list",
    "nbt Long array as long List",
    "nbt Long array as Long list",
    "nbt Long array as Long List",
    "nbt Long array As long list",
    "nbt Long array As long List",
    "nbt Long array As Long list",
    "nbt Long array As Long List",
    "nbt Long Array as long list",
    "nbt Long Array as long List",
    "nbt Long Array as Long list",
    "nbt Long Array as Long List",
    "nbt Long Array As long list",
    "nbt Long Array As long List",
    "nbt Long Array As Long list",
    "nbt Long Array As Long List",
    "Nbt long array as long list",
    "Nbt long array as long List",
    "Nbt long array as Long list",
    "Nbt long array as Long List",
    "Nbt long array As long list",
    "Nbt long array As long List",
    "Nbt long array As Long list",
    "Nbt long array As Long List",
    "Nbt long Array as long list",
    "Nbt long Array as long List",
    "Nbt long Array as Long list",
    "Nbt long Array as Long List",
    "Nbt long Array As long list",
    "Nbt long Array As long List",
    "Nbt long Array As Long list",
    "Nbt long Array As Long List",
    "Nbt Long array as long list",
    "Nbt Long array as long List",
    "Nbt Long array as Long list",
    "Nbt Long array as Long List",
    "Nbt Long array As long list",
    "Nbt Long array As long List",
    "Nbt Long array As Long list",
    "Nbt Long array As Long List",
    "Nbt Long Array as long list",
    "Nbt Long Array as long List",
    "Nbt Long Array as Long list",
    "Nbt Long Array as Long List",
    "Nbt Long Array As long list",
    "Nbt Long Array As long List",
    "Nbt Long Array As Long list",
    "Nbt Long Array As Long List",
    "NBT long array as long list",
    "NBT long array as long List",
    "NBT long array as Long list",
    "NBT long array as Long List",
    "NBT long array As long list",
    "NBT long array As long List",
    "NBT long array As Long list",
    "NBT long array As Long List",
    "NBT long Array as long list",
    "NBT long Array as long List",
    "NBT long Array as Long list",
    "NBT long Array as Long List",
    "NBT long Array As long list",
    "NBT long Array As long List",
    "NBT long Array As Long list",
    "NBT long Array As Long List",
    "NBT Long array as long list",
    "NBT Long array as long List",
    "NBT Long array as Long list",
    "NBT Long array as Long List",
    "NBT Long array As long list",
    "NBT Long array As long List",
    "NBT Long array As Long list",
    "NBT Long array As Long List",
    "NBT Long Array as long list",
    "NBT Long Array as long List",
    "NBT Long Array as Long list",
    "NBT Long Array as Long List",
    "NBT Long Array As long list",
    "NBT Long Array As long List",
    "NBT Long Array As Long list",
    "NBT Long Array As Long List",
    "nbt nbt long array as long list",
    "nbt nbt long array as long List",
    "nbt nbt long array as Long list",
    "nbt nbt long array as Long List",
    "nbt nbt long array As long list",
    "nbt nbt long array As long List",
    "nbt nbt long array As Long list",
    "nbt nbt long array As Long List",
    "nbt nbt long Array as long list",
    "nbt nbt long Array as long List",
    "nbt nbt long Array as Long list",
    "nbt nbt long Array as Long List",
    "nbt nbt long Array As long list",
    "nbt nbt long Array As long List",
    "nbt nbt long Array As Long list",
    "nbt nbt long Array As Long List",
    "nbt nbt Long array as long list",
    "nbt nbt Long array as long List",
    "nbt nbt Long array as Long list",
    "nbt nbt Long array as Long List",
    "nbt nbt Long array As long list",
    "nbt nbt Long array As long List",
    "nbt nbt Long array As Long list",
    "nbt nbt Long array As Long List",
    "nbt nbt Long Array as long list",
    "nbt nbt Long Array as long List",
    "nbt nbt Long Array as Long list",
    "nbt nbt Long Array as Long List",
    "nbt nbt Long Array As long list",
    "nbt nbt Long Array As long List",
    "nbt nbt Long Array As Long list",
    "nbt nbt Long Array As Long List",
    "nbt Nbt long array as long list",
    "nbt Nbt long array as long List",
    "nbt Nbt long array as Long list",
    "nbt Nbt long array as Long List",
    "nbt Nbt long array As long list",
    "nbt Nbt long array As long List",
    "nbt Nbt long array As Long list",
    "nbt Nbt long array As Long List",
    "nbt Nbt long Array as long list",
    "nbt Nbt long Array as long List",
    "nbt Nbt long Array as Long list",
    "nbt Nbt long Array as Long List",
    "nbt Nbt long Array As long list",
    "nbt Nbt long Array As long List",
    "nbt Nbt long Array As Long list",
    "nbt Nbt long Array As Long List",
    "nbt Nbt Long array as long list",
    "nbt Nbt Long array as long List",
    "nbt Nbt Long array as Long list",
    "nbt Nbt Long array as Long List",
    "nbt Nbt Long array As long list",
    "nbt Nbt Long array As long List",
    "nbt Nbt Long array As Long list",
    "nbt Nbt Long array As Long List",
    "nbt Nbt Long Array as long list",
    "nbt Nbt Long Array as long List",
    "nbt Nbt Long Array as Long list",
    "nbt Nbt Long Array as Long List",
    "nbt Nbt Long Array As long list",
    "nbt Nbt Long Array As long List",
    "nbt Nbt Long Array As Long list",
    "nbt Nbt Long Array As Long List",
    "Nbt nbt long array as long list",
    "Nbt nbt long array as long List",
    "Nbt nbt long array as Long list",
    "Nbt nbt long array as Long List",
    "Nbt nbt long array As long list",
    "Nbt nbt long array As long List",
    "Nbt nbt long array As Long list",
    "Nbt nbt long array As Long List",
    "Nbt nbt long Array as long list",
    "Nbt nbt long Array as long List",
    "Nbt nbt long Array as Long list",
    "Nbt nbt long Array as Long List",
    "Nbt nbt long Array As long list",
    "Nbt nbt long Array As long List",
    "Nbt nbt long Array As Long list",
    "Nbt nbt long Array As Long List",
    "Nbt nbt Long array as long list",
    "Nbt nbt Long array as long List",
    "Nbt nbt Long array as Long list",
    "Nbt nbt Long array as Long List",
    "Nbt nbt Long array As long list",
    "Nbt nbt Long array As long List",
    "Nbt nbt Long array As Long list",
    "Nbt nbt Long array As Long List",
    "Nbt nbt Long Array as long list",
    "Nbt nbt Long Array as long List",
    "Nbt nbt Long Array as Long list",
    "Nbt nbt Long Array as Long List",
    "Nbt nbt Long Array As long list",
    "Nbt nbt Long Array As long List",
    "Nbt nbt Long Array As Long list",
    "Nbt nbt Long Array As Long List",
    "Nbt Nbt long array as long list",
    "Nbt Nbt long array as long List",
    "Nbt Nbt long array as Long list",
    "Nbt Nbt long array as Long List",
    "Nbt Nbt long array As long list",
    "Nbt Nbt long array As long List",
    "Nbt Nbt long array As Long list",
    "Nbt Nbt long array As Long List",
    "Nbt Nbt long Array as long list",
    "Nbt Nbt long Array as long List",
    "Nbt Nbt long Array as Long list",
    "Nbt Nbt long Array as Long List",
    "Nbt Nbt long Array As long list",
    "Nbt Nbt long Array As long List",
    "Nbt Nbt long Array As Long list",
    "Nbt Nbt long Array As Long List",
    "Nbt Nbt Long array as long list",
    "Nbt Nbt Long array as long List",
    "Nbt Nbt Long array as Long list",
    "Nbt Nbt Long array as Long List",
    "Nbt Nbt Long array As long list",
    "Nbt Nbt Long array As long List",
    "Nbt Nbt Long array As Long list",
    "Nbt Nbt Long array As Long List",
    "Nbt Nbt Long Array as long list",
    "Nbt Nbt Long Array as long List",
    "Nbt Nbt Long Array as Long list",
    "Nbt Nbt Long Array as Long List",
    "Nbt Nbt Long Array As long list",
    "Nbt Nbt Long Array As long List",
    "Nbt Nbt Long Array As Long list",
    "Nbt Nbt Long Array As Long List",
    "nbt NBT long array as long list",
    "nbt NBT long array as long List",
    "nbt NBT long array as Long list",
    "nbt NBT long array as Long List",
    "nbt NBT long array As long list",
    "nbt NBT long array As long List",
    "nbt NBT long array As Long list",
    "nbt NBT long array As Long List",
    "nbt NBT long Array as long list",
    "nbt NBT long Array as long List",
    "nbt NBT long Array as Long list",
    "nbt NBT long Array as Long List",
    "nbt NBT long Array As long list",
    "nbt NBT long Array As long List",
    "nbt NBT long Array As Long list",
    "nbt NBT long Array As Long List",
    "nbt NBT Long array as long list",
    "nbt NBT Long array as long List",
    "nbt NBT Long array as Long list",
    "nbt NBT Long array as Long List",
    "nbt NBT Long array As long list",
    "nbt NBT Long array As long List",
    "nbt NBT Long array As Long list",
    "nbt NBT Long array As Long List",
    "nbt NBT Long Array as long list",
    "nbt NBT Long Array as long List",
    "nbt NBT Long Array as Long list",
    "nbt NBT Long Array as Long List",
    "nbt NBT Long Array As long list",
    "nbt NBT Long Array As long List",
    "nbt NBT Long Array As Long list",
    "nbt NBT Long Array As Long List",
    "Nbt NBT long array as long list",
    "Nbt NBT long array as long List",
    "Nbt NBT long array as Long list",
    "Nbt NBT long array as Long List",
    "Nbt NBT long array As long list",
    "Nbt NBT long array As long List",
    "Nbt NBT long array As Long list",
    "Nbt NBT long array As Long List",
    "Nbt NBT long Array as long list",
    "Nbt NBT long Array as long List",
    "Nbt NBT long Array as Long list",
    "Nbt NBT long Array as Long List",
    "Nbt NBT long Array As long list",
    "Nbt NBT long Array As long List",
    "Nbt NBT long Array As Long list",
    "Nbt NBT long Array As Long List",
    "Nbt NBT Long array as long list",
    "Nbt NBT Long array as long List",
    "Nbt NBT Long array as Long list",
    "Nbt NBT Long array as Long List",
    "Nbt NBT Long array As long list",
    "Nbt NBT Long array As long List",
    "Nbt NBT Long array As Long list",
    "Nbt NBT Long array As Long List",
    "Nbt NBT Long Array as long list",
    "Nbt NBT Long Array as long List",
    "Nbt NBT Long Array as Long list",
    "Nbt NBT Long Array as Long List",
    "Nbt NBT Long Array As long list",
    "Nbt NBT Long Array As long List",
    "Nbt NBT Long Array As Long list",
    "Nbt NBT Long Array As Long List",
    "NBT nbt long array as long list",
    "NBT nbt long array as long List",
    "NBT nbt long array as Long list",
    "NBT nbt long array as Long List",
    "NBT nbt long array As long list",
    "NBT nbt long array As long List",
    "NBT nbt long array As Long list",
    "NBT nbt long array As Long List",
    "NBT nbt long Array as long list",
    "NBT nbt long Array as long List",
    "NBT nbt long Array as Long list",
    "NBT nbt long Array as Long List",
    "NBT nbt long Array As long list",
    "NBT nbt long Array As long List",
    "NBT nbt long Array As Long list",
    "NBT nbt long Array As Long List",
    "NBT nbt Long array as long list",
    "NBT nbt Long array as long List",
    "NBT nbt Long array as Long list",
    "NBT nbt Long array as Long List",
    "NBT nbt Long array As long list",
    "NBT nbt Long array As long List",
    "NBT nbt Long array As Long list",
    "NBT nbt Long array As Long List",
    "NBT nbt Long Array as long list",
    "NBT nbt Long Array as long List",
    "NBT nbt Long Array as Long list",
    "NBT nbt Long Array as Long List",
    "NBT nbt Long Array As long list",
    "NBT nbt Long Array As long List",
    "NBT nbt Long Array As Long list",
    "NBT nbt Long Array As Long List",
    "NBT Nbt long array as long list",
    "NBT Nbt long array as long List",
    "NBT Nbt long array as Long list",
    "NBT Nbt long array as Long List",
    "NBT Nbt long array As long list",
    "NBT Nbt long array As long List",
    "NBT Nbt long array As Long list",
    "NBT Nbt long array As Long List",
    "NBT Nbt long Array as long list",
    "NBT Nbt long Array as long List",
    "NBT Nbt long Array as Long list",
    "NBT Nbt long Array as Long List",
    "NBT Nbt long Array As long list",
    "NBT Nbt long Array As long List",
    "NBT Nbt long Array As Long list",
    "NBT Nbt long Array As Long List",
    "NBT Nbt Long array as long list",
    "NBT Nbt Long array as long List",
    "NBT Nbt Long array as Long list",
    "NBT Nbt Long array as Long List",
    "NBT Nbt Long array As long list",
    "NBT Nbt Long array As long List",
    "NBT Nbt Long array As Long list",
    "NBT Nbt Long array As Long List",
    "NBT Nbt Long Array as long list",
    "NBT Nbt Long Array as long List",
    "NBT Nbt Long Array as Long list",
    "NBT Nbt Long Array as Long List",
    "NBT Nbt Long Array As long list",
    "NBT Nbt Long Array As long List",
    "NBT Nbt Long Array As Long list",
    "NBT Nbt Long Array As Long List",
    "NBT NBT long array as long list",
    "NBT NBT long array as long List",
    "NBT NBT long array as Long list",
    "NBT NBT long array as Long List",
    "NBT NBT long array As long list",
    "NBT NBT long array As long List",
    "NBT NBT long array As Long list",
    "NBT NBT long array As Long List",
    "NBT NBT long Array as long list",
    "NBT NBT long Array as long List",
    "NBT NBT long Array as Long list",
    "NBT NBT long Array as Long List",
    "NBT NBT long Array As long list",
    "NBT NBT long Array As long List",
    "NBT NBT long Array As Long list",
    "NBT NBT long Array As Long List",
    "NBT NBT Long array as long list",
    "NBT NBT Long array as long List",
    "NBT NBT Long array as Long list",
    "NBT NBT Long array as Long List",
    "NBT NBT Long array As long list",
    "NBT NBT Long array As long List",
    "NBT NBT Long array As Long list",
    "NBT NBT Long array As Long List",
    "NBT NBT Long Array as long list",
    "NBT NBT Long Array as long List",
    "NBT NBT Long Array as Long list",
    "NBT NBT Long Array as Long List",
    "NBT NBT Long Array As long list",
    "NBT NBT Long Array As long List",
    "NBT NBT Long Array As Long list",
    "NBT NBT Long Array As Long List",
  ];
  static override tooltipInfo =
    "Get the Long List value of the given NBT Long Array tag" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: { type: "List", listType: { type: "Long" } },
        },
        normalizeSignature
      ),
      function: (nbt: ListTag): iArray<Long> => {
        if (nbt.getType() === Tag.TAG_LONG_ARRAY) {
          const list = nbt.valueOf();
          if (!list.every((e: Tag<any>) => e.getType() == Tag.TAG_LONG))
            return new iArrayEager<Long>([]);
          return list.map(
            new Operator({
              function: ((e: IntegratedValue) => e.valueOf()) as TypeLambda<
                IntegratedValue,
                IntegratedValue
              >,
              parsedSignature: new ParsedSignature(
                {
                  type: "Function",
                  from: { type: "Any", typeID: 1 },
                  to: { type: "Any", typeID: 2 },
                } as TypeRawSignatureAST.RawSignatureDefiniteValue,
                normalizeSignature
              ),
            })
          ) as iArray<Long>;
        } else {
          return new iArrayEager<Long>([]);
        }
      },
    });
  }
}
