import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";
import { Integer } from "lib/JavaNumberClasses/Integer";

export class OPERATOR_NBT_AS_INT_LIST extends BaseOperator<ListTag, Integer> {
  static override internalName = "integrateddynamics:nbt_as_int_list" as const;
  static override numericID = 248;
  static override nicknames = [
    "asIntList",
    "nbtAsIntList",
    "as_int_list",
    "nbt_as_int_list",
  ];
  static override symbol = "NBT.as_int_list";
  static override interactName = "nbtAsIntList";
  static override operatorName = "as_int_list" as const;
  static override displayName = "NBT Integer Array As Integer List" as const;
  static override fullDisplayName =
    "NBT NBT Integer Array As Integer List" as const;
  static override stringDisplayNames = [
    "nbt integer array as integer list",
    "nbt integer array as integer List",
    "nbt integer array as Integer list",
    "nbt integer array as Integer List",
    "nbt integer array As integer list",
    "nbt integer array As integer List",
    "nbt integer array As Integer list",
    "nbt integer array As Integer List",
    "nbt integer Array as integer list",
    "nbt integer Array as integer List",
    "nbt integer Array as Integer list",
    "nbt integer Array as Integer List",
    "nbt integer Array As integer list",
    "nbt integer Array As integer List",
    "nbt integer Array As Integer list",
    "nbt integer Array As Integer List",
    "nbt Integer array as integer list",
    "nbt Integer array as integer List",
    "nbt Integer array as Integer list",
    "nbt Integer array as Integer List",
    "nbt Integer array As integer list",
    "nbt Integer array As integer List",
    "nbt Integer array As Integer list",
    "nbt Integer array As Integer List",
    "nbt Integer Array as integer list",
    "nbt Integer Array as integer List",
    "nbt Integer Array as Integer list",
    "nbt Integer Array as Integer List",
    "nbt Integer Array As integer list",
    "nbt Integer Array As integer List",
    "nbt Integer Array As Integer list",
    "nbt Integer Array As Integer List",
    "Nbt integer array as integer list",
    "Nbt integer array as integer List",
    "Nbt integer array as Integer list",
    "Nbt integer array as Integer List",
    "Nbt integer array As integer list",
    "Nbt integer array As integer List",
    "Nbt integer array As Integer list",
    "Nbt integer array As Integer List",
    "Nbt integer Array as integer list",
    "Nbt integer Array as integer List",
    "Nbt integer Array as Integer list",
    "Nbt integer Array as Integer List",
    "Nbt integer Array As integer list",
    "Nbt integer Array As integer List",
    "Nbt integer Array As Integer list",
    "Nbt integer Array As Integer List",
    "Nbt Integer array as integer list",
    "Nbt Integer array as integer List",
    "Nbt Integer array as Integer list",
    "Nbt Integer array as Integer List",
    "Nbt Integer array As integer list",
    "Nbt Integer array As integer List",
    "Nbt Integer array As Integer list",
    "Nbt Integer array As Integer List",
    "Nbt Integer Array as integer list",
    "Nbt Integer Array as integer List",
    "Nbt Integer Array as Integer list",
    "Nbt Integer Array as Integer List",
    "Nbt Integer Array As integer list",
    "Nbt Integer Array As integer List",
    "Nbt Integer Array As Integer list",
    "Nbt Integer Array As Integer List",
    "NBT integer array as integer list",
    "NBT integer array as integer List",
    "NBT integer array as Integer list",
    "NBT integer array as Integer List",
    "NBT integer array As integer list",
    "NBT integer array As integer List",
    "NBT integer array As Integer list",
    "NBT integer array As Integer List",
    "NBT integer Array as integer list",
    "NBT integer Array as integer List",
    "NBT integer Array as Integer list",
    "NBT integer Array as Integer List",
    "NBT integer Array As integer list",
    "NBT integer Array As integer List",
    "NBT integer Array As Integer list",
    "NBT integer Array As Integer List",
    "NBT Integer array as integer list",
    "NBT Integer array as integer List",
    "NBT Integer array as Integer list",
    "NBT Integer array as Integer List",
    "NBT Integer array As integer list",
    "NBT Integer array As integer List",
    "NBT Integer array As Integer list",
    "NBT Integer array As Integer List",
    "NBT Integer Array as integer list",
    "NBT Integer Array as integer List",
    "NBT Integer Array as Integer list",
    "NBT Integer Array as Integer List",
    "NBT Integer Array As integer list",
    "NBT Integer Array As integer List",
    "NBT Integer Array As Integer list",
    "NBT Integer Array As Integer List",
    "nbt nbt integer array as integer list",
    "nbt nbt integer array as integer List",
    "nbt nbt integer array as Integer list",
    "nbt nbt integer array as Integer List",
    "nbt nbt integer array As integer list",
    "nbt nbt integer array As integer List",
    "nbt nbt integer array As Integer list",
    "nbt nbt integer array As Integer List",
    "nbt nbt integer Array as integer list",
    "nbt nbt integer Array as integer List",
    "nbt nbt integer Array as Integer list",
    "nbt nbt integer Array as Integer List",
    "nbt nbt integer Array As integer list",
    "nbt nbt integer Array As integer List",
    "nbt nbt integer Array As Integer list",
    "nbt nbt integer Array As Integer List",
    "nbt nbt Integer array as integer list",
    "nbt nbt Integer array as integer List",
    "nbt nbt Integer array as Integer list",
    "nbt nbt Integer array as Integer List",
    "nbt nbt Integer array As integer list",
    "nbt nbt Integer array As integer List",
    "nbt nbt Integer array As Integer list",
    "nbt nbt Integer array As Integer List",
    "nbt nbt Integer Array as integer list",
    "nbt nbt Integer Array as integer List",
    "nbt nbt Integer Array as Integer list",
    "nbt nbt Integer Array as Integer List",
    "nbt nbt Integer Array As integer list",
    "nbt nbt Integer Array As integer List",
    "nbt nbt Integer Array As Integer list",
    "nbt nbt Integer Array As Integer List",
    "nbt Nbt integer array as integer list",
    "nbt Nbt integer array as integer List",
    "nbt Nbt integer array as Integer list",
    "nbt Nbt integer array as Integer List",
    "nbt Nbt integer array As integer list",
    "nbt Nbt integer array As integer List",
    "nbt Nbt integer array As Integer list",
    "nbt Nbt integer array As Integer List",
    "nbt Nbt integer Array as integer list",
    "nbt Nbt integer Array as integer List",
    "nbt Nbt integer Array as Integer list",
    "nbt Nbt integer Array as Integer List",
    "nbt Nbt integer Array As integer list",
    "nbt Nbt integer Array As integer List",
    "nbt Nbt integer Array As Integer list",
    "nbt Nbt integer Array As Integer List",
    "nbt Nbt Integer array as integer list",
    "nbt Nbt Integer array as integer List",
    "nbt Nbt Integer array as Integer list",
    "nbt Nbt Integer array as Integer List",
    "nbt Nbt Integer array As integer list",
    "nbt Nbt Integer array As integer List",
    "nbt Nbt Integer array As Integer list",
    "nbt Nbt Integer array As Integer List",
    "nbt Nbt Integer Array as integer list",
    "nbt Nbt Integer Array as integer List",
    "nbt Nbt Integer Array as Integer list",
    "nbt Nbt Integer Array as Integer List",
    "nbt Nbt Integer Array As integer list",
    "nbt Nbt Integer Array As integer List",
    "nbt Nbt Integer Array As Integer list",
    "nbt Nbt Integer Array As Integer List",
    "Nbt nbt integer array as integer list",
    "Nbt nbt integer array as integer List",
    "Nbt nbt integer array as Integer list",
    "Nbt nbt integer array as Integer List",
    "Nbt nbt integer array As integer list",
    "Nbt nbt integer array As integer List",
    "Nbt nbt integer array As Integer list",
    "Nbt nbt integer array As Integer List",
    "Nbt nbt integer Array as integer list",
    "Nbt nbt integer Array as integer List",
    "Nbt nbt integer Array as Integer list",
    "Nbt nbt integer Array as Integer List",
    "Nbt nbt integer Array As integer list",
    "Nbt nbt integer Array As integer List",
    "Nbt nbt integer Array As Integer list",
    "Nbt nbt integer Array As Integer List",
    "Nbt nbt Integer array as integer list",
    "Nbt nbt Integer array as integer List",
    "Nbt nbt Integer array as Integer list",
    "Nbt nbt Integer array as Integer List",
    "Nbt nbt Integer array As integer list",
    "Nbt nbt Integer array As integer List",
    "Nbt nbt Integer array As Integer list",
    "Nbt nbt Integer array As Integer List",
    "Nbt nbt Integer Array as integer list",
    "Nbt nbt Integer Array as integer List",
    "Nbt nbt Integer Array as Integer list",
    "Nbt nbt Integer Array as Integer List",
    "Nbt nbt Integer Array As integer list",
    "Nbt nbt Integer Array As integer List",
    "Nbt nbt Integer Array As Integer list",
    "Nbt nbt Integer Array As Integer List",
    "Nbt Nbt integer array as integer list",
    "Nbt Nbt integer array as integer List",
    "Nbt Nbt integer array as Integer list",
    "Nbt Nbt integer array as Integer List",
    "Nbt Nbt integer array As integer list",
    "Nbt Nbt integer array As integer List",
    "Nbt Nbt integer array As Integer list",
    "Nbt Nbt integer array As Integer List",
    "Nbt Nbt integer Array as integer list",
    "Nbt Nbt integer Array as integer List",
    "Nbt Nbt integer Array as Integer list",
    "Nbt Nbt integer Array as Integer List",
    "Nbt Nbt integer Array As integer list",
    "Nbt Nbt integer Array As integer List",
    "Nbt Nbt integer Array As Integer list",
    "Nbt Nbt integer Array As Integer List",
    "Nbt Nbt Integer array as integer list",
    "Nbt Nbt Integer array as integer List",
    "Nbt Nbt Integer array as Integer list",
    "Nbt Nbt Integer array as Integer List",
    "Nbt Nbt Integer array As integer list",
    "Nbt Nbt Integer array As integer List",
    "Nbt Nbt Integer array As Integer list",
    "Nbt Nbt Integer array As Integer List",
    "Nbt Nbt Integer Array as integer list",
    "Nbt Nbt Integer Array as integer List",
    "Nbt Nbt Integer Array as Integer list",
    "Nbt Nbt Integer Array as Integer List",
    "Nbt Nbt Integer Array As integer list",
    "Nbt Nbt Integer Array As integer List",
    "Nbt Nbt Integer Array As Integer list",
    "Nbt Nbt Integer Array As Integer List",
    "nbt NBT integer array as integer list",
    "nbt NBT integer array as integer List",
    "nbt NBT integer array as Integer list",
    "nbt NBT integer array as Integer List",
    "nbt NBT integer array As integer list",
    "nbt NBT integer array As integer List",
    "nbt NBT integer array As Integer list",
    "nbt NBT integer array As Integer List",
    "nbt NBT integer Array as integer list",
    "nbt NBT integer Array as integer List",
    "nbt NBT integer Array as Integer list",
    "nbt NBT integer Array as Integer List",
    "nbt NBT integer Array As integer list",
    "nbt NBT integer Array As integer List",
    "nbt NBT integer Array As Integer list",
    "nbt NBT integer Array As Integer List",
    "nbt NBT Integer array as integer list",
    "nbt NBT Integer array as integer List",
    "nbt NBT Integer array as Integer list",
    "nbt NBT Integer array as Integer List",
    "nbt NBT Integer array As integer list",
    "nbt NBT Integer array As integer List",
    "nbt NBT Integer array As Integer list",
    "nbt NBT Integer array As Integer List",
    "nbt NBT Integer Array as integer list",
    "nbt NBT Integer Array as integer List",
    "nbt NBT Integer Array as Integer list",
    "nbt NBT Integer Array as Integer List",
    "nbt NBT Integer Array As integer list",
    "nbt NBT Integer Array As integer List",
    "nbt NBT Integer Array As Integer list",
    "nbt NBT Integer Array As Integer List",
    "Nbt NBT integer array as integer list",
    "Nbt NBT integer array as integer List",
    "Nbt NBT integer array as Integer list",
    "Nbt NBT integer array as Integer List",
    "Nbt NBT integer array As integer list",
    "Nbt NBT integer array As integer List",
    "Nbt NBT integer array As Integer list",
    "Nbt NBT integer array As Integer List",
    "Nbt NBT integer Array as integer list",
    "Nbt NBT integer Array as integer List",
    "Nbt NBT integer Array as Integer list",
    "Nbt NBT integer Array as Integer List",
    "Nbt NBT integer Array As integer list",
    "Nbt NBT integer Array As integer List",
    "Nbt NBT integer Array As Integer list",
    "Nbt NBT integer Array As Integer List",
    "Nbt NBT Integer array as integer list",
    "Nbt NBT Integer array as integer List",
    "Nbt NBT Integer array as Integer list",
    "Nbt NBT Integer array as Integer List",
    "Nbt NBT Integer array As integer list",
    "Nbt NBT Integer array As integer List",
    "Nbt NBT Integer array As Integer list",
    "Nbt NBT Integer array As Integer List",
    "Nbt NBT Integer Array as integer list",
    "Nbt NBT Integer Array as integer List",
    "Nbt NBT Integer Array as Integer list",
    "Nbt NBT Integer Array as Integer List",
    "Nbt NBT Integer Array As integer list",
    "Nbt NBT Integer Array As integer List",
    "Nbt NBT Integer Array As Integer list",
    "Nbt NBT Integer Array As Integer List",
    "NBT nbt integer array as integer list",
    "NBT nbt integer array as integer List",
    "NBT nbt integer array as Integer list",
    "NBT nbt integer array as Integer List",
    "NBT nbt integer array As integer list",
    "NBT nbt integer array As integer List",
    "NBT nbt integer array As Integer list",
    "NBT nbt integer array As Integer List",
    "NBT nbt integer Array as integer list",
    "NBT nbt integer Array as integer List",
    "NBT nbt integer Array as Integer list",
    "NBT nbt integer Array as Integer List",
    "NBT nbt integer Array As integer list",
    "NBT nbt integer Array As integer List",
    "NBT nbt integer Array As Integer list",
    "NBT nbt integer Array As Integer List",
    "NBT nbt Integer array as integer list",
    "NBT nbt Integer array as integer List",
    "NBT nbt Integer array as Integer list",
    "NBT nbt Integer array as Integer List",
    "NBT nbt Integer array As integer list",
    "NBT nbt Integer array As integer List",
    "NBT nbt Integer array As Integer list",
    "NBT nbt Integer array As Integer List",
    "NBT nbt Integer Array as integer list",
    "NBT nbt Integer Array as integer List",
    "NBT nbt Integer Array as Integer list",
    "NBT nbt Integer Array as Integer List",
    "NBT nbt Integer Array As integer list",
    "NBT nbt Integer Array As integer List",
    "NBT nbt Integer Array As Integer list",
    "NBT nbt Integer Array As Integer List",
    "NBT Nbt integer array as integer list",
    "NBT Nbt integer array as integer List",
    "NBT Nbt integer array as Integer list",
    "NBT Nbt integer array as Integer List",
    "NBT Nbt integer array As integer list",
    "NBT Nbt integer array As integer List",
    "NBT Nbt integer array As Integer list",
    "NBT Nbt integer array As Integer List",
    "NBT Nbt integer Array as integer list",
    "NBT Nbt integer Array as integer List",
    "NBT Nbt integer Array as Integer list",
    "NBT Nbt integer Array as Integer List",
    "NBT Nbt integer Array As integer list",
    "NBT Nbt integer Array As integer List",
    "NBT Nbt integer Array As Integer list",
    "NBT Nbt integer Array As Integer List",
    "NBT Nbt Integer array as integer list",
    "NBT Nbt Integer array as integer List",
    "NBT Nbt Integer array as Integer list",
    "NBT Nbt Integer array as Integer List",
    "NBT Nbt Integer array As integer list",
    "NBT Nbt Integer array As integer List",
    "NBT Nbt Integer array As Integer list",
    "NBT Nbt Integer array As Integer List",
    "NBT Nbt Integer Array as integer list",
    "NBT Nbt Integer Array as integer List",
    "NBT Nbt Integer Array as Integer list",
    "NBT Nbt Integer Array as Integer List",
    "NBT Nbt Integer Array As integer list",
    "NBT Nbt Integer Array As integer List",
    "NBT Nbt Integer Array As Integer list",
    "NBT Nbt Integer Array As Integer List",
    "NBT NBT integer array as integer list",
    "NBT NBT integer array as integer List",
    "NBT NBT integer array as Integer list",
    "NBT NBT integer array as Integer List",
    "NBT NBT integer array As integer list",
    "NBT NBT integer array As integer List",
    "NBT NBT integer array As Integer list",
    "NBT NBT integer array As Integer List",
    "NBT NBT integer Array as integer list",
    "NBT NBT integer Array as integer List",
    "NBT NBT integer Array as Integer list",
    "NBT NBT integer Array as Integer List",
    "NBT NBT integer Array As integer list",
    "NBT NBT integer Array As integer List",
    "NBT NBT integer Array As Integer list",
    "NBT NBT integer Array As Integer List",
    "NBT NBT Integer array as integer list",
    "NBT NBT Integer array as integer List",
    "NBT NBT Integer array as Integer list",
    "NBT NBT Integer array as Integer List",
    "NBT NBT Integer array As integer list",
    "NBT NBT Integer array As integer List",
    "NBT NBT Integer array As Integer list",
    "NBT NBT Integer array As Integer List",
    "NBT NBT Integer Array as integer list",
    "NBT NBT Integer Array as integer List",
    "NBT NBT Integer Array as Integer list",
    "NBT NBT Integer Array as Integer List",
    "NBT NBT Integer Array As integer list",
    "NBT NBT Integer Array As integer List",
    "NBT NBT Integer Array As Integer list",
    "NBT NBT Integer Array As Integer List",
  ];
  static override tooltipInfo =
    "Get the Integer List value of the given NBT Integer Array tag" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: { type: "List", listType: { type: "Integer" } },
        },
        normalizeSignature
      ),
      function: (nbt: ListTag): iArray<Integer> => {
        if (nbt.getType() === Tag.TAG_INT_ARRAY) {
          const list = nbt.valueOf();
          if (!list.every((e: Tag<any>) => e.getType() == Tag.TAG_INT))
            return new iArrayEager<Integer>([]);
          return list.map(
            new Operator({
              function: ((e: IntegratedValue) => e.valueOf()) as TypeLambda<
                IntegratedValue,
                IntegratedValue
              >,
              parsedSignature: new ParsedSignature(
                {
                  type: "Function",
                  from: { type: "Any", typeID: 1 },
                  to: { type: "Any", typeID: 2 },
                } as TypeRawSignatureAST.RawSignatureDefiniteValue,
                normalizeSignature
              ),
            })
          ) as iArray<Integer>;
        } else {
          return new iArrayEager<Integer>([]);
        }
      },
    });
  }
}
