import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Long } from "lib/JavaNumberClasses/Long";
import { LongArrayTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/LongArrayTag";

export class OPERATOR_NBT_COMPOUND_WITH_LIST_LONG extends BaseOperator<
  CompoundTag,
  Operator<iString, Operator<iArray<Long>, CompoundTag>>
> {
  static override internalName =
    "integrateddynamics:nbt_compound_with_list_long" as const;
  static override numericID = 231;
  static override nicknames = [
    "compoundWithListLong",
    "nbtCompoundWithListLong",
    "nbtWithLongList",
    "NBTWithLongList",
    "compound_with_list_long",
    "n_b_t_with_long_list",
    "nbt_compound_with_list_long",
    "nbt_with_long_list",
  ];
  static override symbol = "NBT{}.with_long_list";
  static override interactName = "nbtWithLongList";
  static override operatorName = "compound_with_list_long" as const;
  static override displayName = "NBT Compound With Long List" as const;
  static override fullDisplayName = "NBT NBT Compound With Long List" as const;
  static override stringDisplayNames = [
    "nbt compound with long list",
    "nbt compound with long List",
    "nbt compound with Long list",
    "nbt compound with Long List",
    "nbt compound With long list",
    "nbt compound With long List",
    "nbt compound With Long list",
    "nbt compound With Long List",
    "nbt Compound with long list",
    "nbt Compound with long List",
    "nbt Compound with Long list",
    "nbt Compound with Long List",
    "nbt Compound With long list",
    "nbt Compound With long List",
    "nbt Compound With Long list",
    "nbt Compound With Long List",
    "Nbt compound with long list",
    "Nbt compound with long List",
    "Nbt compound with Long list",
    "Nbt compound with Long List",
    "Nbt compound With long list",
    "Nbt compound With long List",
    "Nbt compound With Long list",
    "Nbt compound With Long List",
    "Nbt Compound with long list",
    "Nbt Compound with long List",
    "Nbt Compound with Long list",
    "Nbt Compound with Long List",
    "Nbt Compound With long list",
    "Nbt Compound With long List",
    "Nbt Compound With Long list",
    "Nbt Compound With Long List",
    "NBT compound with long list",
    "NBT compound with long List",
    "NBT compound with Long list",
    "NBT compound with Long List",
    "NBT compound With long list",
    "NBT compound With long List",
    "NBT compound With Long list",
    "NBT compound With Long List",
    "NBT Compound with long list",
    "NBT Compound with long List",
    "NBT Compound with Long list",
    "NBT Compound with Long List",
    "NBT Compound With long list",
    "NBT Compound With long List",
    "NBT Compound With Long list",
    "NBT Compound With Long List",
    "nbt nbt compound with long list",
    "nbt nbt compound with long List",
    "nbt nbt compound with Long list",
    "nbt nbt compound with Long List",
    "nbt nbt compound With long list",
    "nbt nbt compound With long List",
    "nbt nbt compound With Long list",
    "nbt nbt compound With Long List",
    "nbt nbt Compound with long list",
    "nbt nbt Compound with long List",
    "nbt nbt Compound with Long list",
    "nbt nbt Compound with Long List",
    "nbt nbt Compound With long list",
    "nbt nbt Compound With long List",
    "nbt nbt Compound With Long list",
    "nbt nbt Compound With Long List",
    "nbt Nbt compound with long list",
    "nbt Nbt compound with long List",
    "nbt Nbt compound with Long list",
    "nbt Nbt compound with Long List",
    "nbt Nbt compound With long list",
    "nbt Nbt compound With long List",
    "nbt Nbt compound With Long list",
    "nbt Nbt compound With Long List",
    "nbt Nbt Compound with long list",
    "nbt Nbt Compound with long List",
    "nbt Nbt Compound with Long list",
    "nbt Nbt Compound with Long List",
    "nbt Nbt Compound With long list",
    "nbt Nbt Compound With long List",
    "nbt Nbt Compound With Long list",
    "nbt Nbt Compound With Long List",
    "Nbt nbt compound with long list",
    "Nbt nbt compound with long List",
    "Nbt nbt compound with Long list",
    "Nbt nbt compound with Long List",
    "Nbt nbt compound With long list",
    "Nbt nbt compound With long List",
    "Nbt nbt compound With Long list",
    "Nbt nbt compound With Long List",
    "Nbt nbt Compound with long list",
    "Nbt nbt Compound with long List",
    "Nbt nbt Compound with Long list",
    "Nbt nbt Compound with Long List",
    "Nbt nbt Compound With long list",
    "Nbt nbt Compound With long List",
    "Nbt nbt Compound With Long list",
    "Nbt nbt Compound With Long List",
    "Nbt Nbt compound with long list",
    "Nbt Nbt compound with long List",
    "Nbt Nbt compound with Long list",
    "Nbt Nbt compound with Long List",
    "Nbt Nbt compound With long list",
    "Nbt Nbt compound With long List",
    "Nbt Nbt compound With Long list",
    "Nbt Nbt compound With Long List",
    "Nbt Nbt Compound with long list",
    "Nbt Nbt Compound with long List",
    "Nbt Nbt Compound with Long list",
    "Nbt Nbt Compound with Long List",
    "Nbt Nbt Compound With long list",
    "Nbt Nbt Compound With long List",
    "Nbt Nbt Compound With Long list",
    "Nbt Nbt Compound With Long List",
    "nbt NBT compound with long list",
    "nbt NBT compound with long List",
    "nbt NBT compound with Long list",
    "nbt NBT compound with Long List",
    "nbt NBT compound With long list",
    "nbt NBT compound With long List",
    "nbt NBT compound With Long list",
    "nbt NBT compound With Long List",
    "nbt NBT Compound with long list",
    "nbt NBT Compound with long List",
    "nbt NBT Compound with Long list",
    "nbt NBT Compound with Long List",
    "nbt NBT Compound With long list",
    "nbt NBT Compound With long List",
    "nbt NBT Compound With Long list",
    "nbt NBT Compound With Long List",
    "Nbt NBT compound with long list",
    "Nbt NBT compound with long List",
    "Nbt NBT compound with Long list",
    "Nbt NBT compound with Long List",
    "Nbt NBT compound With long list",
    "Nbt NBT compound With long List",
    "Nbt NBT compound With Long list",
    "Nbt NBT compound With Long List",
    "Nbt NBT Compound with long list",
    "Nbt NBT Compound with long List",
    "Nbt NBT Compound with Long list",
    "Nbt NBT Compound with Long List",
    "Nbt NBT Compound With long list",
    "Nbt NBT Compound With long List",
    "Nbt NBT Compound With Long list",
    "Nbt NBT Compound With Long List",
    "NBT nbt compound with long list",
    "NBT nbt compound with long List",
    "NBT nbt compound with Long list",
    "NBT nbt compound with Long List",
    "NBT nbt compound With long list",
    "NBT nbt compound With long List",
    "NBT nbt compound With Long list",
    "NBT nbt compound With Long List",
    "NBT nbt Compound with long list",
    "NBT nbt Compound with long List",
    "NBT nbt Compound with Long list",
    "NBT nbt Compound with Long List",
    "NBT nbt Compound With long list",
    "NBT nbt Compound With long List",
    "NBT nbt Compound With Long list",
    "NBT nbt Compound With Long List",
    "NBT Nbt compound with long list",
    "NBT Nbt compound with long List",
    "NBT Nbt compound with Long list",
    "NBT Nbt compound with Long List",
    "NBT Nbt compound With long list",
    "NBT Nbt compound With long List",
    "NBT Nbt compound With Long list",
    "NBT Nbt compound With Long List",
    "NBT Nbt Compound with long list",
    "NBT Nbt Compound with long List",
    "NBT Nbt Compound with Long list",
    "NBT Nbt Compound with Long List",
    "NBT Nbt Compound With long list",
    "NBT Nbt Compound With long List",
    "NBT Nbt Compound With Long list",
    "NBT Nbt Compound With Long List",
    "NBT NBT compound with long list",
    "NBT NBT compound with long List",
    "NBT NBT compound with Long list",
    "NBT NBT compound with Long List",
    "NBT NBT compound With long list",
    "NBT NBT compound With long List",
    "NBT NBT compound With Long list",
    "NBT NBT compound With Long List",
    "NBT NBT Compound with long list",
    "NBT NBT Compound with long List",
    "NBT NBT Compound with Long list",
    "NBT NBT Compound with Long List",
    "NBT NBT Compound With long list",
    "NBT NBT Compound With long List",
    "NBT NBT Compound With Long list",
    "NBT NBT Compound With Long List",
  ];
  static override tooltipInfo =
    "Get a copy of the given NBT compound tag with the given NBT Long Array entry" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "INFIX_2_VERYLONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: {
              type: "Function",
              from: { type: "List", listType: { type: "Long" } },
              to: {
                type: "NBT",
              },
            },
          },
        },
        normalizeSignature
      ),
      function:
        (
          nbt: CompoundTag
        ): TypeLambda<iString, TypeLambda<iArray<Long>, CompoundTag>> =>
        (key: iString): TypeLambda<iArray<Long>, CompoundTag> =>
        (value: iArray<Long>): CompoundTag => {
          return nbt.set(key.valueOf(), new LongArrayTag(value));
        },
    });
  }
}
