import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { ListTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ListTag";
import { Integer } from "lib/JavaNumberClasses/Integer";

export class OPERATOR_NBT_AS_BYTE_LIST extends BaseOperator<
  ListTag,
  iArray<Integer>
> {
  static override internalName = "integrateddynamics:nbt_as_byte_list" as const;
  static override numericID = 243;
  static override nicknames = [
    "asByteList",
    "nbtAsByteList",
    "as_byte_list",
    "nbt_as_byte_list",
  ];
  static override symbol = "NBT.as_byte_list";
  static override interactName = "nbtAsByteList";
  static override operatorName = "as_byte_list" as const;
  static override displayName = "NBT Byte Array As Byte List" as const;
  static override fullDisplayName = "NBT NBT Byte Array As Byte List" as const;
  static override stringDisplayNames = [
    "nbt byte array as byte list",
    "nbt byte array as byte List",
    "nbt byte array as Byte list",
    "nbt byte array as Byte List",
    "nbt byte array As byte list",
    "nbt byte array As byte List",
    "nbt byte array As Byte list",
    "nbt byte array As Byte List",
    "nbt byte Array as byte list",
    "nbt byte Array as byte List",
    "nbt byte Array as Byte list",
    "nbt byte Array as Byte List",
    "nbt byte Array As byte list",
    "nbt byte Array As byte List",
    "nbt byte Array As Byte list",
    "nbt byte Array As Byte List",
    "nbt Byte array as byte list",
    "nbt Byte array as byte List",
    "nbt Byte array as Byte list",
    "nbt Byte array as Byte List",
    "nbt Byte array As byte list",
    "nbt Byte array As byte List",
    "nbt Byte array As Byte list",
    "nbt Byte array As Byte List",
    "nbt Byte Array as byte list",
    "nbt Byte Array as byte List",
    "nbt Byte Array as Byte list",
    "nbt Byte Array as Byte List",
    "nbt Byte Array As byte list",
    "nbt Byte Array As byte List",
    "nbt Byte Array As Byte list",
    "nbt Byte Array As Byte List",
    "Nbt byte array as byte list",
    "Nbt byte array as byte List",
    "Nbt byte array as Byte list",
    "Nbt byte array as Byte List",
    "Nbt byte array As byte list",
    "Nbt byte array As byte List",
    "Nbt byte array As Byte list",
    "Nbt byte array As Byte List",
    "Nbt byte Array as byte list",
    "Nbt byte Array as byte List",
    "Nbt byte Array as Byte list",
    "Nbt byte Array as Byte List",
    "Nbt byte Array As byte list",
    "Nbt byte Array As byte List",
    "Nbt byte Array As Byte list",
    "Nbt byte Array As Byte List",
    "Nbt Byte array as byte list",
    "Nbt Byte array as byte List",
    "Nbt Byte array as Byte list",
    "Nbt Byte array as Byte List",
    "Nbt Byte array As byte list",
    "Nbt Byte array As byte List",
    "Nbt Byte array As Byte list",
    "Nbt Byte array As Byte List",
    "Nbt Byte Array as byte list",
    "Nbt Byte Array as byte List",
    "Nbt Byte Array as Byte list",
    "Nbt Byte Array as Byte List",
    "Nbt Byte Array As byte list",
    "Nbt Byte Array As byte List",
    "Nbt Byte Array As Byte list",
    "Nbt Byte Array As Byte List",
    "NBT byte array as byte list",
    "NBT byte array as byte List",
    "NBT byte array as Byte list",
    "NBT byte array as Byte List",
    "NBT byte array As byte list",
    "NBT byte array As byte List",
    "NBT byte array As Byte list",
    "NBT byte array As Byte List",
    "NBT byte Array as byte list",
    "NBT byte Array as byte List",
    "NBT byte Array as Byte list",
    "NBT byte Array as Byte List",
    "NBT byte Array As byte list",
    "NBT byte Array As byte List",
    "NBT byte Array As Byte list",
    "NBT byte Array As Byte List",
    "NBT Byte array as byte list",
    "NBT Byte array as byte List",
    "NBT Byte array as Byte list",
    "NBT Byte array as Byte List",
    "NBT Byte array As byte list",
    "NBT Byte array As byte List",
    "NBT Byte array As Byte list",
    "NBT Byte array As Byte List",
    "NBT Byte Array as byte list",
    "NBT Byte Array as byte List",
    "NBT Byte Array as Byte list",
    "NBT Byte Array as Byte List",
    "NBT Byte Array As byte list",
    "NBT Byte Array As byte List",
    "NBT Byte Array As Byte list",
    "NBT Byte Array As Byte List",
    "nbt nbt byte array as byte list",
    "nbt nbt byte array as byte List",
    "nbt nbt byte array as Byte list",
    "nbt nbt byte array as Byte List",
    "nbt nbt byte array As byte list",
    "nbt nbt byte array As byte List",
    "nbt nbt byte array As Byte list",
    "nbt nbt byte array As Byte List",
    "nbt nbt byte Array as byte list",
    "nbt nbt byte Array as byte List",
    "nbt nbt byte Array as Byte list",
    "nbt nbt byte Array as Byte List",
    "nbt nbt byte Array As byte list",
    "nbt nbt byte Array As byte List",
    "nbt nbt byte Array As Byte list",
    "nbt nbt byte Array As Byte List",
    "nbt nbt Byte array as byte list",
    "nbt nbt Byte array as byte List",
    "nbt nbt Byte array as Byte list",
    "nbt nbt Byte array as Byte List",
    "nbt nbt Byte array As byte list",
    "nbt nbt Byte array As byte List",
    "nbt nbt Byte array As Byte list",
    "nbt nbt Byte array As Byte List",
    "nbt nbt Byte Array as byte list",
    "nbt nbt Byte Array as byte List",
    "nbt nbt Byte Array as Byte list",
    "nbt nbt Byte Array as Byte List",
    "nbt nbt Byte Array As byte list",
    "nbt nbt Byte Array As byte List",
    "nbt nbt Byte Array As Byte list",
    "nbt nbt Byte Array As Byte List",
    "nbt Nbt byte array as byte list",
    "nbt Nbt byte array as byte List",
    "nbt Nbt byte array as Byte list",
    "nbt Nbt byte array as Byte List",
    "nbt Nbt byte array As byte list",
    "nbt Nbt byte array As byte List",
    "nbt Nbt byte array As Byte list",
    "nbt Nbt byte array As Byte List",
    "nbt Nbt byte Array as byte list",
    "nbt Nbt byte Array as byte List",
    "nbt Nbt byte Array as Byte list",
    "nbt Nbt byte Array as Byte List",
    "nbt Nbt byte Array As byte list",
    "nbt Nbt byte Array As byte List",
    "nbt Nbt byte Array As Byte list",
    "nbt Nbt byte Array As Byte List",
    "nbt Nbt Byte array as byte list",
    "nbt Nbt Byte array as byte List",
    "nbt Nbt Byte array as Byte list",
    "nbt Nbt Byte array as Byte List",
    "nbt Nbt Byte array As byte list",
    "nbt Nbt Byte array As byte List",
    "nbt Nbt Byte array As Byte list",
    "nbt Nbt Byte array As Byte List",
    "nbt Nbt Byte Array as byte list",
    "nbt Nbt Byte Array as byte List",
    "nbt Nbt Byte Array as Byte list",
    "nbt Nbt Byte Array as Byte List",
    "nbt Nbt Byte Array As byte list",
    "nbt Nbt Byte Array As byte List",
    "nbt Nbt Byte Array As Byte list",
    "nbt Nbt Byte Array As Byte List",
    "Nbt nbt byte array as byte list",
    "Nbt nbt byte array as byte List",
    "Nbt nbt byte array as Byte list",
    "Nbt nbt byte array as Byte List",
    "Nbt nbt byte array As byte list",
    "Nbt nbt byte array As byte List",
    "Nbt nbt byte array As Byte list",
    "Nbt nbt byte array As Byte List",
    "Nbt nbt byte Array as byte list",
    "Nbt nbt byte Array as byte List",
    "Nbt nbt byte Array as Byte list",
    "Nbt nbt byte Array as Byte List",
    "Nbt nbt byte Array As byte list",
    "Nbt nbt byte Array As byte List",
    "Nbt nbt byte Array As Byte list",
    "Nbt nbt byte Array As Byte List",
    "Nbt nbt Byte array as byte list",
    "Nbt nbt Byte array as byte List",
    "Nbt nbt Byte array as Byte list",
    "Nbt nbt Byte array as Byte List",
    "Nbt nbt Byte array As byte list",
    "Nbt nbt Byte array As byte List",
    "Nbt nbt Byte array As Byte list",
    "Nbt nbt Byte array As Byte List",
    "Nbt nbt Byte Array as byte list",
    "Nbt nbt Byte Array as byte List",
    "Nbt nbt Byte Array as Byte list",
    "Nbt nbt Byte Array as Byte List",
    "Nbt nbt Byte Array As byte list",
    "Nbt nbt Byte Array As byte List",
    "Nbt nbt Byte Array As Byte list",
    "Nbt nbt Byte Array As Byte List",
    "Nbt Nbt byte array as byte list",
    "Nbt Nbt byte array as byte List",
    "Nbt Nbt byte array as Byte list",
    "Nbt Nbt byte array as Byte List",
    "Nbt Nbt byte array As byte list",
    "Nbt Nbt byte array As byte List",
    "Nbt Nbt byte array As Byte list",
    "Nbt Nbt byte array As Byte List",
    "Nbt Nbt byte Array as byte list",
    "Nbt Nbt byte Array as byte List",
    "Nbt Nbt byte Array as Byte list",
    "Nbt Nbt byte Array as Byte List",
    "Nbt Nbt byte Array As byte list",
    "Nbt Nbt byte Array As byte List",
    "Nbt Nbt byte Array As Byte list",
    "Nbt Nbt byte Array As Byte List",
    "Nbt Nbt Byte array as byte list",
    "Nbt Nbt Byte array as byte List",
    "Nbt Nbt Byte array as Byte list",
    "Nbt Nbt Byte array as Byte List",
    "Nbt Nbt Byte array As byte list",
    "Nbt Nbt Byte array As byte List",
    "Nbt Nbt Byte array As Byte list",
    "Nbt Nbt Byte array As Byte List",
    "Nbt Nbt Byte Array as byte list",
    "Nbt Nbt Byte Array as byte List",
    "Nbt Nbt Byte Array as Byte list",
    "Nbt Nbt Byte Array as Byte List",
    "Nbt Nbt Byte Array As byte list",
    "Nbt Nbt Byte Array As byte List",
    "Nbt Nbt Byte Array As Byte list",
    "Nbt Nbt Byte Array As Byte List",
    "nbt NBT byte array as byte list",
    "nbt NBT byte array as byte List",
    "nbt NBT byte array as Byte list",
    "nbt NBT byte array as Byte List",
    "nbt NBT byte array As byte list",
    "nbt NBT byte array As byte List",
    "nbt NBT byte array As Byte list",
    "nbt NBT byte array As Byte List",
    "nbt NBT byte Array as byte list",
    "nbt NBT byte Array as byte List",
    "nbt NBT byte Array as Byte list",
    "nbt NBT byte Array as Byte List",
    "nbt NBT byte Array As byte list",
    "nbt NBT byte Array As byte List",
    "nbt NBT byte Array As Byte list",
    "nbt NBT byte Array As Byte List",
    "nbt NBT Byte array as byte list",
    "nbt NBT Byte array as byte List",
    "nbt NBT Byte array as Byte list",
    "nbt NBT Byte array as Byte List",
    "nbt NBT Byte array As byte list",
    "nbt NBT Byte array As byte List",
    "nbt NBT Byte array As Byte list",
    "nbt NBT Byte array As Byte List",
    "nbt NBT Byte Array as byte list",
    "nbt NBT Byte Array as byte List",
    "nbt NBT Byte Array as Byte list",
    "nbt NBT Byte Array as Byte List",
    "nbt NBT Byte Array As byte list",
    "nbt NBT Byte Array As byte List",
    "nbt NBT Byte Array As Byte list",
    "nbt NBT Byte Array As Byte List",
    "Nbt NBT byte array as byte list",
    "Nbt NBT byte array as byte List",
    "Nbt NBT byte array as Byte list",
    "Nbt NBT byte array as Byte List",
    "Nbt NBT byte array As byte list",
    "Nbt NBT byte array As byte List",
    "Nbt NBT byte array As Byte list",
    "Nbt NBT byte array As Byte List",
    "Nbt NBT byte Array as byte list",
    "Nbt NBT byte Array as byte List",
    "Nbt NBT byte Array as Byte list",
    "Nbt NBT byte Array as Byte List",
    "Nbt NBT byte Array As byte list",
    "Nbt NBT byte Array As byte List",
    "Nbt NBT byte Array As Byte list",
    "Nbt NBT byte Array As Byte List",
    "Nbt NBT Byte array as byte list",
    "Nbt NBT Byte array as byte List",
    "Nbt NBT Byte array as Byte list",
    "Nbt NBT Byte array as Byte List",
    "Nbt NBT Byte array As byte list",
    "Nbt NBT Byte array As byte List",
    "Nbt NBT Byte array As Byte list",
    "Nbt NBT Byte array As Byte List",
    "Nbt NBT Byte Array as byte list",
    "Nbt NBT Byte Array as byte List",
    "Nbt NBT Byte Array as Byte list",
    "Nbt NBT Byte Array as Byte List",
    "Nbt NBT Byte Array As byte list",
    "Nbt NBT Byte Array As byte List",
    "Nbt NBT Byte Array As Byte list",
    "Nbt NBT Byte Array As Byte List",
    "NBT nbt byte array as byte list",
    "NBT nbt byte array as byte List",
    "NBT nbt byte array as Byte list",
    "NBT nbt byte array as Byte List",
    "NBT nbt byte array As byte list",
    "NBT nbt byte array As byte List",
    "NBT nbt byte array As Byte list",
    "NBT nbt byte array As Byte List",
    "NBT nbt byte Array as byte list",
    "NBT nbt byte Array as byte List",
    "NBT nbt byte Array as Byte list",
    "NBT nbt byte Array as Byte List",
    "NBT nbt byte Array As byte list",
    "NBT nbt byte Array As byte List",
    "NBT nbt byte Array As Byte list",
    "NBT nbt byte Array As Byte List",
    "NBT nbt Byte array as byte list",
    "NBT nbt Byte array as byte List",
    "NBT nbt Byte array as Byte list",
    "NBT nbt Byte array as Byte List",
    "NBT nbt Byte array As byte list",
    "NBT nbt Byte array As byte List",
    "NBT nbt Byte array As Byte list",
    "NBT nbt Byte array As Byte List",
    "NBT nbt Byte Array as byte list",
    "NBT nbt Byte Array as byte List",
    "NBT nbt Byte Array as Byte list",
    "NBT nbt Byte Array as Byte List",
    "NBT nbt Byte Array As byte list",
    "NBT nbt Byte Array As byte List",
    "NBT nbt Byte Array As Byte list",
    "NBT nbt Byte Array As Byte List",
    "NBT Nbt byte array as byte list",
    "NBT Nbt byte array as byte List",
    "NBT Nbt byte array as Byte list",
    "NBT Nbt byte array as Byte List",
    "NBT Nbt byte array As byte list",
    "NBT Nbt byte array As byte List",
    "NBT Nbt byte array As Byte list",
    "NBT Nbt byte array As Byte List",
    "NBT Nbt byte Array as byte list",
    "NBT Nbt byte Array as byte List",
    "NBT Nbt byte Array as Byte list",
    "NBT Nbt byte Array as Byte List",
    "NBT Nbt byte Array As byte list",
    "NBT Nbt byte Array As byte List",
    "NBT Nbt byte Array As Byte list",
    "NBT Nbt byte Array As Byte List",
    "NBT Nbt Byte array as byte list",
    "NBT Nbt Byte array as byte List",
    "NBT Nbt Byte array as Byte list",
    "NBT Nbt Byte array as Byte List",
    "NBT Nbt Byte array As byte list",
    "NBT Nbt Byte array As byte List",
    "NBT Nbt Byte array As Byte list",
    "NBT Nbt Byte array As Byte List",
    "NBT Nbt Byte Array as byte list",
    "NBT Nbt Byte Array as byte List",
    "NBT Nbt Byte Array as Byte list",
    "NBT Nbt Byte Array as Byte List",
    "NBT Nbt Byte Array As byte list",
    "NBT Nbt Byte Array As byte List",
    "NBT Nbt Byte Array As Byte list",
    "NBT Nbt Byte Array As Byte List",
    "NBT NBT byte array as byte list",
    "NBT NBT byte array as byte List",
    "NBT NBT byte array as Byte list",
    "NBT NBT byte array as Byte List",
    "NBT NBT byte array As byte list",
    "NBT NBT byte array As byte List",
    "NBT NBT byte array As Byte list",
    "NBT NBT byte array As Byte List",
    "NBT NBT byte Array as byte list",
    "NBT NBT byte Array as byte List",
    "NBT NBT byte Array as Byte list",
    "NBT NBT byte Array as Byte List",
    "NBT NBT byte Array As byte list",
    "NBT NBT byte Array As byte List",
    "NBT NBT byte Array As Byte list",
    "NBT NBT byte Array As Byte List",
    "NBT NBT Byte array as byte list",
    "NBT NBT Byte array as byte List",
    "NBT NBT Byte array as Byte list",
    "NBT NBT Byte array as Byte List",
    "NBT NBT Byte array As byte list",
    "NBT NBT Byte array As byte List",
    "NBT NBT Byte array As Byte list",
    "NBT NBT Byte array As Byte List",
    "NBT NBT Byte Array as byte list",
    "NBT NBT Byte Array as byte List",
    "NBT NBT Byte Array as Byte list",
    "NBT NBT Byte Array as Byte List",
    "NBT NBT Byte Array As byte list",
    "NBT NBT Byte Array As byte List",
    "NBT NBT Byte Array As Byte list",
    "NBT NBT Byte Array As Byte List",
  ];
  static override tooltipInfo =
    "Get the Byte List value of the given NBT Byte Array tag" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: { type: "List", listType: { type: "Integer" } },
        },
        normalizeSignature
      ),
      function: (nbt: ListTag): iArray<Integer> => {
        if (nbt.getType() === Tag.TAG_BYTE_ARRAY) {
          const list = nbt.valueOf();
          if (!list.every((e: Tag<any>) => e.getType() == Tag.TAG_INT))
            return new iArrayEager<Integer>([]);
          return list.map(
            new Operator({
              function: ((e: IntegratedValue) => e.valueOf()) as TypeLambda<
                IntegratedValue,
                IntegratedValue
              >,
              parsedSignature: new ParsedSignature(
                {
                  type: "Function",
                  from: { type: "Any", typeID: 1 },
                  to: { type: "Any", typeID: 2 },
                } as TypeRawSignatureAST.RawSignatureDefiniteValue,
                normalizeSignature
              ),
            })
          ) as iArray<Integer>;
        } else {
          return new iArrayEager<Integer>([]);
        }
      },
    });
  }
}
