import { LongArrayTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/LongArrayTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Long } from "lib/JavaNumberClasses/Long";

export class OPERATOR_NBT_FROM_LONG_LIST extends BaseOperator<
  iArray<Long>,
  LongArrayTag
> {
  static override internalName =
    "integrateddynamics:nbt_from_long_list" as const;
  static override numericID = 262;
  static override nicknames = [
    "fromLongList",
    "longListAsNbt",
    "nbtFromLongList",
    "from_long_list",
    "long_list_as_nbt",
    "nbt_from_long_list",
  ];
  static override symbol = "NBT.from_long_list";
  static override interactName = "longListAsNbt";
  static override operatorName = "from_long_list" as const;
  static override displayName = "NBT Long Array From Long List" as const;
  static override fullDisplayName =
    "NBT NBT Long Array From Long List" as const;
  static override stringDisplayNames = [
    "nbt long array from long list",
    "nbt long array from long List",
    "nbt long array from Long list",
    "nbt long array from Long List",
    "nbt long array From long list",
    "nbt long array From long List",
    "nbt long array From Long list",
    "nbt long array From Long List",
    "nbt long Array from long list",
    "nbt long Array from long List",
    "nbt long Array from Long list",
    "nbt long Array from Long List",
    "nbt long Array From long list",
    "nbt long Array From long List",
    "nbt long Array From Long list",
    "nbt long Array From Long List",
    "nbt Long array from long list",
    "nbt Long array from long List",
    "nbt Long array from Long list",
    "nbt Long array from Long List",
    "nbt Long array From long list",
    "nbt Long array From long List",
    "nbt Long array From Long list",
    "nbt Long array From Long List",
    "nbt Long Array from long list",
    "nbt Long Array from long List",
    "nbt Long Array from Long list",
    "nbt Long Array from Long List",
    "nbt Long Array From long list",
    "nbt Long Array From long List",
    "nbt Long Array From Long list",
    "nbt Long Array From Long List",
    "Nbt long array from long list",
    "Nbt long array from long List",
    "Nbt long array from Long list",
    "Nbt long array from Long List",
    "Nbt long array From long list",
    "Nbt long array From long List",
    "Nbt long array From Long list",
    "Nbt long array From Long List",
    "Nbt long Array from long list",
    "Nbt long Array from long List",
    "Nbt long Array from Long list",
    "Nbt long Array from Long List",
    "Nbt long Array From long list",
    "Nbt long Array From long List",
    "Nbt long Array From Long list",
    "Nbt long Array From Long List",
    "Nbt Long array from long list",
    "Nbt Long array from long List",
    "Nbt Long array from Long list",
    "Nbt Long array from Long List",
    "Nbt Long array From long list",
    "Nbt Long array From long List",
    "Nbt Long array From Long list",
    "Nbt Long array From Long List",
    "Nbt Long Array from long list",
    "Nbt Long Array from long List",
    "Nbt Long Array from Long list",
    "Nbt Long Array from Long List",
    "Nbt Long Array From long list",
    "Nbt Long Array From long List",
    "Nbt Long Array From Long list",
    "Nbt Long Array From Long List",
    "NBT long array from long list",
    "NBT long array from long List",
    "NBT long array from Long list",
    "NBT long array from Long List",
    "NBT long array From long list",
    "NBT long array From long List",
    "NBT long array From Long list",
    "NBT long array From Long List",
    "NBT long Array from long list",
    "NBT long Array from long List",
    "NBT long Array from Long list",
    "NBT long Array from Long List",
    "NBT long Array From long list",
    "NBT long Array From long List",
    "NBT long Array From Long list",
    "NBT long Array From Long List",
    "NBT Long array from long list",
    "NBT Long array from long List",
    "NBT Long array from Long list",
    "NBT Long array from Long List",
    "NBT Long array From long list",
    "NBT Long array From long List",
    "NBT Long array From Long list",
    "NBT Long array From Long List",
    "NBT Long Array from long list",
    "NBT Long Array from long List",
    "NBT Long Array from Long list",
    "NBT Long Array from Long List",
    "NBT Long Array From long list",
    "NBT Long Array From long List",
    "NBT Long Array From Long list",
    "NBT Long Array From Long List",
    "nbt nbt long array from long list",
    "nbt nbt long array from long List",
    "nbt nbt long array from Long list",
    "nbt nbt long array from Long List",
    "nbt nbt long array From long list",
    "nbt nbt long array From long List",
    "nbt nbt long array From Long list",
    "nbt nbt long array From Long List",
    "nbt nbt long Array from long list",
    "nbt nbt long Array from long List",
    "nbt nbt long Array from Long list",
    "nbt nbt long Array from Long List",
    "nbt nbt long Array From long list",
    "nbt nbt long Array From long List",
    "nbt nbt long Array From Long list",
    "nbt nbt long Array From Long List",
    "nbt nbt Long array from long list",
    "nbt nbt Long array from long List",
    "nbt nbt Long array from Long list",
    "nbt nbt Long array from Long List",
    "nbt nbt Long array From long list",
    "nbt nbt Long array From long List",
    "nbt nbt Long array From Long list",
    "nbt nbt Long array From Long List",
    "nbt nbt Long Array from long list",
    "nbt nbt Long Array from long List",
    "nbt nbt Long Array from Long list",
    "nbt nbt Long Array from Long List",
    "nbt nbt Long Array From long list",
    "nbt nbt Long Array From long List",
    "nbt nbt Long Array From Long list",
    "nbt nbt Long Array From Long List",
    "nbt Nbt long array from long list",
    "nbt Nbt long array from long List",
    "nbt Nbt long array from Long list",
    "nbt Nbt long array from Long List",
    "nbt Nbt long array From long list",
    "nbt Nbt long array From long List",
    "nbt Nbt long array From Long list",
    "nbt Nbt long array From Long List",
    "nbt Nbt long Array from long list",
    "nbt Nbt long Array from long List",
    "nbt Nbt long Array from Long list",
    "nbt Nbt long Array from Long List",
    "nbt Nbt long Array From long list",
    "nbt Nbt long Array From long List",
    "nbt Nbt long Array From Long list",
    "nbt Nbt long Array From Long List",
    "nbt Nbt Long array from long list",
    "nbt Nbt Long array from long List",
    "nbt Nbt Long array from Long list",
    "nbt Nbt Long array from Long List",
    "nbt Nbt Long array From long list",
    "nbt Nbt Long array From long List",
    "nbt Nbt Long array From Long list",
    "nbt Nbt Long array From Long List",
    "nbt Nbt Long Array from long list",
    "nbt Nbt Long Array from long List",
    "nbt Nbt Long Array from Long list",
    "nbt Nbt Long Array from Long List",
    "nbt Nbt Long Array From long list",
    "nbt Nbt Long Array From long List",
    "nbt Nbt Long Array From Long list",
    "nbt Nbt Long Array From Long List",
    "Nbt nbt long array from long list",
    "Nbt nbt long array from long List",
    "Nbt nbt long array from Long list",
    "Nbt nbt long array from Long List",
    "Nbt nbt long array From long list",
    "Nbt nbt long array From long List",
    "Nbt nbt long array From Long list",
    "Nbt nbt long array From Long List",
    "Nbt nbt long Array from long list",
    "Nbt nbt long Array from long List",
    "Nbt nbt long Array from Long list",
    "Nbt nbt long Array from Long List",
    "Nbt nbt long Array From long list",
    "Nbt nbt long Array From long List",
    "Nbt nbt long Array From Long list",
    "Nbt nbt long Array From Long List",
    "Nbt nbt Long array from long list",
    "Nbt nbt Long array from long List",
    "Nbt nbt Long array from Long list",
    "Nbt nbt Long array from Long List",
    "Nbt nbt Long array From long list",
    "Nbt nbt Long array From long List",
    "Nbt nbt Long array From Long list",
    "Nbt nbt Long array From Long List",
    "Nbt nbt Long Array from long list",
    "Nbt nbt Long Array from long List",
    "Nbt nbt Long Array from Long list",
    "Nbt nbt Long Array from Long List",
    "Nbt nbt Long Array From long list",
    "Nbt nbt Long Array From long List",
    "Nbt nbt Long Array From Long list",
    "Nbt nbt Long Array From Long List",
    "Nbt Nbt long array from long list",
    "Nbt Nbt long array from long List",
    "Nbt Nbt long array from Long list",
    "Nbt Nbt long array from Long List",
    "Nbt Nbt long array From long list",
    "Nbt Nbt long array From long List",
    "Nbt Nbt long array From Long list",
    "Nbt Nbt long array From Long List",
    "Nbt Nbt long Array from long list",
    "Nbt Nbt long Array from long List",
    "Nbt Nbt long Array from Long list",
    "Nbt Nbt long Array from Long List",
    "Nbt Nbt long Array From long list",
    "Nbt Nbt long Array From long List",
    "Nbt Nbt long Array From Long list",
    "Nbt Nbt long Array From Long List",
    "Nbt Nbt Long array from long list",
    "Nbt Nbt Long array from long List",
    "Nbt Nbt Long array from Long list",
    "Nbt Nbt Long array from Long List",
    "Nbt Nbt Long array From long list",
    "Nbt Nbt Long array From long List",
    "Nbt Nbt Long array From Long list",
    "Nbt Nbt Long array From Long List",
    "Nbt Nbt Long Array from long list",
    "Nbt Nbt Long Array from long List",
    "Nbt Nbt Long Array from Long list",
    "Nbt Nbt Long Array from Long List",
    "Nbt Nbt Long Array From long list",
    "Nbt Nbt Long Array From long List",
    "Nbt Nbt Long Array From Long list",
    "Nbt Nbt Long Array From Long List",
    "nbt NBT long array from long list",
    "nbt NBT long array from long List",
    "nbt NBT long array from Long list",
    "nbt NBT long array from Long List",
    "nbt NBT long array From long list",
    "nbt NBT long array From long List",
    "nbt NBT long array From Long list",
    "nbt NBT long array From Long List",
    "nbt NBT long Array from long list",
    "nbt NBT long Array from long List",
    "nbt NBT long Array from Long list",
    "nbt NBT long Array from Long List",
    "nbt NBT long Array From long list",
    "nbt NBT long Array From long List",
    "nbt NBT long Array From Long list",
    "nbt NBT long Array From Long List",
    "nbt NBT Long array from long list",
    "nbt NBT Long array from long List",
    "nbt NBT Long array from Long list",
    "nbt NBT Long array from Long List",
    "nbt NBT Long array From long list",
    "nbt NBT Long array From long List",
    "nbt NBT Long array From Long list",
    "nbt NBT Long array From Long List",
    "nbt NBT Long Array from long list",
    "nbt NBT Long Array from long List",
    "nbt NBT Long Array from Long list",
    "nbt NBT Long Array from Long List",
    "nbt NBT Long Array From long list",
    "nbt NBT Long Array From long List",
    "nbt NBT Long Array From Long list",
    "nbt NBT Long Array From Long List",
    "Nbt NBT long array from long list",
    "Nbt NBT long array from long List",
    "Nbt NBT long array from Long list",
    "Nbt NBT long array from Long List",
    "Nbt NBT long array From long list",
    "Nbt NBT long array From long List",
    "Nbt NBT long array From Long list",
    "Nbt NBT long array From Long List",
    "Nbt NBT long Array from long list",
    "Nbt NBT long Array from long List",
    "Nbt NBT long Array from Long list",
    "Nbt NBT long Array from Long List",
    "Nbt NBT long Array From long list",
    "Nbt NBT long Array From long List",
    "Nbt NBT long Array From Long list",
    "Nbt NBT long Array From Long List",
    "Nbt NBT Long array from long list",
    "Nbt NBT Long array from long List",
    "Nbt NBT Long array from Long list",
    "Nbt NBT Long array from Long List",
    "Nbt NBT Long array From long list",
    "Nbt NBT Long array From long List",
    "Nbt NBT Long array From Long list",
    "Nbt NBT Long array From Long List",
    "Nbt NBT Long Array from long list",
    "Nbt NBT Long Array from long List",
    "Nbt NBT Long Array from Long list",
    "Nbt NBT Long Array from Long List",
    "Nbt NBT Long Array From long list",
    "Nbt NBT Long Array From long List",
    "Nbt NBT Long Array From Long list",
    "Nbt NBT Long Array From Long List",
    "NBT nbt long array from long list",
    "NBT nbt long array from long List",
    "NBT nbt long array from Long list",
    "NBT nbt long array from Long List",
    "NBT nbt long array From long list",
    "NBT nbt long array From long List",
    "NBT nbt long array From Long list",
    "NBT nbt long array From Long List",
    "NBT nbt long Array from long list",
    "NBT nbt long Array from long List",
    "NBT nbt long Array from Long list",
    "NBT nbt long Array from Long List",
    "NBT nbt long Array From long list",
    "NBT nbt long Array From long List",
    "NBT nbt long Array From Long list",
    "NBT nbt long Array From Long List",
    "NBT nbt Long array from long list",
    "NBT nbt Long array from long List",
    "NBT nbt Long array from Long list",
    "NBT nbt Long array from Long List",
    "NBT nbt Long array From long list",
    "NBT nbt Long array From long List",
    "NBT nbt Long array From Long list",
    "NBT nbt Long array From Long List",
    "NBT nbt Long Array from long list",
    "NBT nbt Long Array from long List",
    "NBT nbt Long Array from Long list",
    "NBT nbt Long Array from Long List",
    "NBT nbt Long Array From long list",
    "NBT nbt Long Array From long List",
    "NBT nbt Long Array From Long list",
    "NBT nbt Long Array From Long List",
    "NBT Nbt long array from long list",
    "NBT Nbt long array from long List",
    "NBT Nbt long array from Long list",
    "NBT Nbt long array from Long List",
    "NBT Nbt long array From long list",
    "NBT Nbt long array From long List",
    "NBT Nbt long array From Long list",
    "NBT Nbt long array From Long List",
    "NBT Nbt long Array from long list",
    "NBT Nbt long Array from long List",
    "NBT Nbt long Array from Long list",
    "NBT Nbt long Array from Long List",
    "NBT Nbt long Array From long list",
    "NBT Nbt long Array From long List",
    "NBT Nbt long Array From Long list",
    "NBT Nbt long Array From Long List",
    "NBT Nbt Long array from long list",
    "NBT Nbt Long array from long List",
    "NBT Nbt Long array from Long list",
    "NBT Nbt Long array from Long List",
    "NBT Nbt Long array From long list",
    "NBT Nbt Long array From long List",
    "NBT Nbt Long array From Long list",
    "NBT Nbt Long array From Long List",
    "NBT Nbt Long Array from long list",
    "NBT Nbt Long Array from long List",
    "NBT Nbt Long Array from Long list",
    "NBT Nbt Long Array from Long List",
    "NBT Nbt Long Array From long list",
    "NBT Nbt Long Array From long List",
    "NBT Nbt Long Array From Long list",
    "NBT Nbt Long Array From Long List",
    "NBT NBT long array from long list",
    "NBT NBT long array from long List",
    "NBT NBT long array from Long list",
    "NBT NBT long array from Long List",
    "NBT NBT long array From long list",
    "NBT NBT long array From long List",
    "NBT NBT long array From Long list",
    "NBT NBT long array From Long List",
    "NBT NBT long Array from long list",
    "NBT NBT long Array from long List",
    "NBT NBT long Array from Long list",
    "NBT NBT long Array from Long List",
    "NBT NBT long Array From long list",
    "NBT NBT long Array From long List",
    "NBT NBT long Array From Long list",
    "NBT NBT long Array From Long List",
    "NBT NBT Long array from long list",
    "NBT NBT Long array from long List",
    "NBT NBT Long array from Long list",
    "NBT NBT Long array from Long List",
    "NBT NBT Long array From long list",
    "NBT NBT Long array From long List",
    "NBT NBT Long array From Long list",
    "NBT NBT Long array From Long List",
    "NBT NBT Long Array from long list",
    "NBT NBT Long Array from long List",
    "NBT NBT Long Array from Long list",
    "NBT NBT Long Array from Long List",
    "NBT NBT Long Array From long list",
    "NBT NBT Long Array From long List",
    "NBT NBT Long Array From Long list",
    "NBT NBT Long Array From Long List",
  ];
  static override tooltipInfo =
    "Create an NBT Long Array tag from the given Long List value" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "PREFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: { type: "List", listType: { type: "Long" } },
          to: {
            type: "NBT",
          },
        },
        normalizeSignature
      ),
      function: (longList: iArray<Long>): LongArrayTag => {
        return new LongArrayTag(longList);
      },
    });
  }
}
