import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Integer } from "lib/JavaNumberClasses/Integer";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { ByteArrayTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/ByteArrayTag";

export class OPERATOR_NBT_COMPOUND_WITH_LIST_BYTE extends BaseOperator<
  CompoundTag,
  Operator<iString, Operator<iArray<Integer>, CompoundTag>>
> {
  static override internalName =
    "integrateddynamics:nbt_compound_with_list_byte" as const;
  static override numericID = 229;
  static override nicknames = [
    "compoundWithListByte",
    "nbtCompoundWithListByte",
    "nbtWithByteList",
    "NBTWithByteList",
    "compound_with_list_byte",
    "n_b_t_with_byte_list",
    "nbt_compound_with_list_byte",
    "nbt_with_byte_list",
  ];
  static override symbol = "NBT{}.with_byte_list";
  static override interactName = "nbtWithByteList";
  static override operatorName = "compound_with_list_byte" as const;
  static override displayName = "NBT Compound With Byte List" as const;
  static override fullDisplayName = "NBT NBT Compound With Byte List" as const;
  static override stringDisplayNames = [
    "nbt compound with byte list",
    "nbt compound with byte List",
    "nbt compound with Byte list",
    "nbt compound with Byte List",
    "nbt compound With byte list",
    "nbt compound With byte List",
    "nbt compound With Byte list",
    "nbt compound With Byte List",
    "nbt Compound with byte list",
    "nbt Compound with byte List",
    "nbt Compound with Byte list",
    "nbt Compound with Byte List",
    "nbt Compound With byte list",
    "nbt Compound With byte List",
    "nbt Compound With Byte list",
    "nbt Compound With Byte List",
    "Nbt compound with byte list",
    "Nbt compound with byte List",
    "Nbt compound with Byte list",
    "Nbt compound with Byte List",
    "Nbt compound With byte list",
    "Nbt compound With byte List",
    "Nbt compound With Byte list",
    "Nbt compound With Byte List",
    "Nbt Compound with byte list",
    "Nbt Compound with byte List",
    "Nbt Compound with Byte list",
    "Nbt Compound with Byte List",
    "Nbt Compound With byte list",
    "Nbt Compound With byte List",
    "Nbt Compound With Byte list",
    "Nbt Compound With Byte List",
    "NBT compound with byte list",
    "NBT compound with byte List",
    "NBT compound with Byte list",
    "NBT compound with Byte List",
    "NBT compound With byte list",
    "NBT compound With byte List",
    "NBT compound With Byte list",
    "NBT compound With Byte List",
    "NBT Compound with byte list",
    "NBT Compound with byte List",
    "NBT Compound with Byte list",
    "NBT Compound with Byte List",
    "NBT Compound With byte list",
    "NBT Compound With byte List",
    "NBT Compound With Byte list",
    "NBT Compound With Byte List",
    "nbt nbt compound with byte list",
    "nbt nbt compound with byte List",
    "nbt nbt compound with Byte list",
    "nbt nbt compound with Byte List",
    "nbt nbt compound With byte list",
    "nbt nbt compound With byte List",
    "nbt nbt compound With Byte list",
    "nbt nbt compound With Byte List",
    "nbt nbt Compound with byte list",
    "nbt nbt Compound with byte List",
    "nbt nbt Compound with Byte list",
    "nbt nbt Compound with Byte List",
    "nbt nbt Compound With byte list",
    "nbt nbt Compound With byte List",
    "nbt nbt Compound With Byte list",
    "nbt nbt Compound With Byte List",
    "nbt Nbt compound with byte list",
    "nbt Nbt compound with byte List",
    "nbt Nbt compound with Byte list",
    "nbt Nbt compound with Byte List",
    "nbt Nbt compound With byte list",
    "nbt Nbt compound With byte List",
    "nbt Nbt compound With Byte list",
    "nbt Nbt compound With Byte List",
    "nbt Nbt Compound with byte list",
    "nbt Nbt Compound with byte List",
    "nbt Nbt Compound with Byte list",
    "nbt Nbt Compound with Byte List",
    "nbt Nbt Compound With byte list",
    "nbt Nbt Compound With byte List",
    "nbt Nbt Compound With Byte list",
    "nbt Nbt Compound With Byte List",
    "Nbt nbt compound with byte list",
    "Nbt nbt compound with byte List",
    "Nbt nbt compound with Byte list",
    "Nbt nbt compound with Byte List",
    "Nbt nbt compound With byte list",
    "Nbt nbt compound With byte List",
    "Nbt nbt compound With Byte list",
    "Nbt nbt compound With Byte List",
    "Nbt nbt Compound with byte list",
    "Nbt nbt Compound with byte List",
    "Nbt nbt Compound with Byte list",
    "Nbt nbt Compound with Byte List",
    "Nbt nbt Compound With byte list",
    "Nbt nbt Compound With byte List",
    "Nbt nbt Compound With Byte list",
    "Nbt nbt Compound With Byte List",
    "Nbt Nbt compound with byte list",
    "Nbt Nbt compound with byte List",
    "Nbt Nbt compound with Byte list",
    "Nbt Nbt compound with Byte List",
    "Nbt Nbt compound With byte list",
    "Nbt Nbt compound With byte List",
    "Nbt Nbt compound With Byte list",
    "Nbt Nbt compound With Byte List",
    "Nbt Nbt Compound with byte list",
    "Nbt Nbt Compound with byte List",
    "Nbt Nbt Compound with Byte list",
    "Nbt Nbt Compound with Byte List",
    "Nbt Nbt Compound With byte list",
    "Nbt Nbt Compound With byte List",
    "Nbt Nbt Compound With Byte list",
    "Nbt Nbt Compound With Byte List",
    "nbt NBT compound with byte list",
    "nbt NBT compound with byte List",
    "nbt NBT compound with Byte list",
    "nbt NBT compound with Byte List",
    "nbt NBT compound With byte list",
    "nbt NBT compound With byte List",
    "nbt NBT compound With Byte list",
    "nbt NBT compound With Byte List",
    "nbt NBT Compound with byte list",
    "nbt NBT Compound with byte List",
    "nbt NBT Compound with Byte list",
    "nbt NBT Compound with Byte List",
    "nbt NBT Compound With byte list",
    "nbt NBT Compound With byte List",
    "nbt NBT Compound With Byte list",
    "nbt NBT Compound With Byte List",
    "Nbt NBT compound with byte list",
    "Nbt NBT compound with byte List",
    "Nbt NBT compound with Byte list",
    "Nbt NBT compound with Byte List",
    "Nbt NBT compound With byte list",
    "Nbt NBT compound With byte List",
    "Nbt NBT compound With Byte list",
    "Nbt NBT compound With Byte List",
    "Nbt NBT Compound with byte list",
    "Nbt NBT Compound with byte List",
    "Nbt NBT Compound with Byte list",
    "Nbt NBT Compound with Byte List",
    "Nbt NBT Compound With byte list",
    "Nbt NBT Compound With byte List",
    "Nbt NBT Compound With Byte list",
    "Nbt NBT Compound With Byte List",
    "NBT nbt compound with byte list",
    "NBT nbt compound with byte List",
    "NBT nbt compound with Byte list",
    "NBT nbt compound with Byte List",
    "NBT nbt compound With byte list",
    "NBT nbt compound With byte List",
    "NBT nbt compound With Byte list",
    "NBT nbt compound With Byte List",
    "NBT nbt Compound with byte list",
    "NBT nbt Compound with byte List",
    "NBT nbt Compound with Byte list",
    "NBT nbt Compound with Byte List",
    "NBT nbt Compound With byte list",
    "NBT nbt Compound With byte List",
    "NBT nbt Compound With Byte list",
    "NBT nbt Compound With Byte List",
    "NBT Nbt compound with byte list",
    "NBT Nbt compound with byte List",
    "NBT Nbt compound with Byte list",
    "NBT Nbt compound with Byte List",
    "NBT Nbt compound With byte list",
    "NBT Nbt compound With byte List",
    "NBT Nbt compound With Byte list",
    "NBT Nbt compound With Byte List",
    "NBT Nbt Compound with byte list",
    "NBT Nbt Compound with byte List",
    "NBT Nbt Compound with Byte list",
    "NBT Nbt Compound with Byte List",
    "NBT Nbt Compound With byte list",
    "NBT Nbt Compound With byte List",
    "NBT Nbt Compound With Byte list",
    "NBT Nbt Compound With Byte List",
    "NBT NBT compound with byte list",
    "NBT NBT compound with byte List",
    "NBT NBT compound with Byte list",
    "NBT NBT compound with Byte List",
    "NBT NBT compound With byte list",
    "NBT NBT compound With byte List",
    "NBT NBT compound With Byte list",
    "NBT NBT compound With Byte List",
    "NBT NBT Compound with byte list",
    "NBT NBT Compound with byte List",
    "NBT NBT Compound with Byte list",
    "NBT NBT Compound with Byte List",
    "NBT NBT Compound With byte list",
    "NBT NBT Compound With byte List",
    "NBT NBT Compound With Byte list",
    "NBT NBT Compound With Byte List",
  ];
  static override tooltipInfo =
    "Get a copy of the given NBT compound tag with the given Integer List as an NBT Byte Array entry" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "INFIX_2_VERYLONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "NBT",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: {
              type: "Function",
              from: { type: "List", listType: { type: "Integer" } },
              to: {
                type: "NBT",
              },
            },
          },
        },
        normalizeSignature
      ),
      function:
        (
          nbt: CompoundTag
        ): TypeLambda<iString, TypeLambda<iArray<Integer>, CompoundTag>> =>
        (key: iString): TypeLambda<iArray<Integer>, CompoundTag> =>
        (value: iArray<Integer>): CompoundTag => {
          return nbt.set(key.valueOf(), new ByteArrayTag(value));
        },
    });
  }
}
