import { IntArrayTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/IntArrayTag";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { Integer } from "lib/JavaNumberClasses/Integer";

export class OPERATOR_NBT_FROM_INT_LIST extends BaseOperator<
  iArray<Integer>,
  IntArrayTag
> {
  static override internalName =
    "integrateddynamics:nbt_from_int_list" as const;
  static override numericID = 260;
  static override nicknames = [
    "fromIntList",
    "intListAsNbt",
    "nbtFromIntList",
    "from_int_list",
    "int_list_as_nbt",
    "nbt_from_int_list",
  ];
  static override symbol = "NBT.from_int_list";
  static override interactName = "intListAsNbt";
  static override operatorName = "from_int_list" as const;
  static override displayName = "NBT Integer Array From Integer List" as const;
  static override fullDisplayName =
    "NBT NBT Integer Array From Integer List" as const;
  static override stringDisplayNames = [
    "nbt integer array from integer list",
    "nbt integer array from integer List",
    "nbt integer array from Integer list",
    "nbt integer array from Integer List",
    "nbt integer array From integer list",
    "nbt integer array From integer List",
    "nbt integer array From Integer list",
    "nbt integer array From Integer List",
    "nbt integer Array from integer list",
    "nbt integer Array from integer List",
    "nbt integer Array from Integer list",
    "nbt integer Array from Integer List",
    "nbt integer Array From integer list",
    "nbt integer Array From integer List",
    "nbt integer Array From Integer list",
    "nbt integer Array From Integer List",
    "nbt Integer array from integer list",
    "nbt Integer array from integer List",
    "nbt Integer array from Integer list",
    "nbt Integer array from Integer List",
    "nbt Integer array From integer list",
    "nbt Integer array From integer List",
    "nbt Integer array From Integer list",
    "nbt Integer array From Integer List",
    "nbt Integer Array from integer list",
    "nbt Integer Array from integer List",
    "nbt Integer Array from Integer list",
    "nbt Integer Array from Integer List",
    "nbt Integer Array From integer list",
    "nbt Integer Array From integer List",
    "nbt Integer Array From Integer list",
    "nbt Integer Array From Integer List",
    "Nbt integer array from integer list",
    "Nbt integer array from integer List",
    "Nbt integer array from Integer list",
    "Nbt integer array from Integer List",
    "Nbt integer array From integer list",
    "Nbt integer array From integer List",
    "Nbt integer array From Integer list",
    "Nbt integer array From Integer List",
    "Nbt integer Array from integer list",
    "Nbt integer Array from integer List",
    "Nbt integer Array from Integer list",
    "Nbt integer Array from Integer List",
    "Nbt integer Array From integer list",
    "Nbt integer Array From integer List",
    "Nbt integer Array From Integer list",
    "Nbt integer Array From Integer List",
    "Nbt Integer array from integer list",
    "Nbt Integer array from integer List",
    "Nbt Integer array from Integer list",
    "Nbt Integer array from Integer List",
    "Nbt Integer array From integer list",
    "Nbt Integer array From integer List",
    "Nbt Integer array From Integer list",
    "Nbt Integer array From Integer List",
    "Nbt Integer Array from integer list",
    "Nbt Integer Array from integer List",
    "Nbt Integer Array from Integer list",
    "Nbt Integer Array from Integer List",
    "Nbt Integer Array From integer list",
    "Nbt Integer Array From integer List",
    "Nbt Integer Array From Integer list",
    "Nbt Integer Array From Integer List",
    "NBT integer array from integer list",
    "NBT integer array from integer List",
    "NBT integer array from Integer list",
    "NBT integer array from Integer List",
    "NBT integer array From integer list",
    "NBT integer array From integer List",
    "NBT integer array From Integer list",
    "NBT integer array From Integer List",
    "NBT integer Array from integer list",
    "NBT integer Array from integer List",
    "NBT integer Array from Integer list",
    "NBT integer Array from Integer List",
    "NBT integer Array From integer list",
    "NBT integer Array From integer List",
    "NBT integer Array From Integer list",
    "NBT integer Array From Integer List",
    "NBT Integer array from integer list",
    "NBT Integer array from integer List",
    "NBT Integer array from Integer list",
    "NBT Integer array from Integer List",
    "NBT Integer array From integer list",
    "NBT Integer array From integer List",
    "NBT Integer array From Integer list",
    "NBT Integer array From Integer List",
    "NBT Integer Array from integer list",
    "NBT Integer Array from integer List",
    "NBT Integer Array from Integer list",
    "NBT Integer Array from Integer List",
    "NBT Integer Array From integer list",
    "NBT Integer Array From integer List",
    "NBT Integer Array From Integer list",
    "NBT Integer Array From Integer List",
    "nbt nbt integer array from integer list",
    "nbt nbt integer array from integer List",
    "nbt nbt integer array from Integer list",
    "nbt nbt integer array from Integer List",
    "nbt nbt integer array From integer list",
    "nbt nbt integer array From integer List",
    "nbt nbt integer array From Integer list",
    "nbt nbt integer array From Integer List",
    "nbt nbt integer Array from integer list",
    "nbt nbt integer Array from integer List",
    "nbt nbt integer Array from Integer list",
    "nbt nbt integer Array from Integer List",
    "nbt nbt integer Array From integer list",
    "nbt nbt integer Array From integer List",
    "nbt nbt integer Array From Integer list",
    "nbt nbt integer Array From Integer List",
    "nbt nbt Integer array from integer list",
    "nbt nbt Integer array from integer List",
    "nbt nbt Integer array from Integer list",
    "nbt nbt Integer array from Integer List",
    "nbt nbt Integer array From integer list",
    "nbt nbt Integer array From integer List",
    "nbt nbt Integer array From Integer list",
    "nbt nbt Integer array From Integer List",
    "nbt nbt Integer Array from integer list",
    "nbt nbt Integer Array from integer List",
    "nbt nbt Integer Array from Integer list",
    "nbt nbt Integer Array from Integer List",
    "nbt nbt Integer Array From integer list",
    "nbt nbt Integer Array From integer List",
    "nbt nbt Integer Array From Integer list",
    "nbt nbt Integer Array From Integer List",
    "nbt Nbt integer array from integer list",
    "nbt Nbt integer array from integer List",
    "nbt Nbt integer array from Integer list",
    "nbt Nbt integer array from Integer List",
    "nbt Nbt integer array From integer list",
    "nbt Nbt integer array From integer List",
    "nbt Nbt integer array From Integer list",
    "nbt Nbt integer array From Integer List",
    "nbt Nbt integer Array from integer list",
    "nbt Nbt integer Array from integer List",
    "nbt Nbt integer Array from Integer list",
    "nbt Nbt integer Array from Integer List",
    "nbt Nbt integer Array From integer list",
    "nbt Nbt integer Array From integer List",
    "nbt Nbt integer Array From Integer list",
    "nbt Nbt integer Array From Integer List",
    "nbt Nbt Integer array from integer list",
    "nbt Nbt Integer array from integer List",
    "nbt Nbt Integer array from Integer list",
    "nbt Nbt Integer array from Integer List",
    "nbt Nbt Integer array From integer list",
    "nbt Nbt Integer array From integer List",
    "nbt Nbt Integer array From Integer list",
    "nbt Nbt Integer array From Integer List",
    "nbt Nbt Integer Array from integer list",
    "nbt Nbt Integer Array from integer List",
    "nbt Nbt Integer Array from Integer list",
    "nbt Nbt Integer Array from Integer List",
    "nbt Nbt Integer Array From integer list",
    "nbt Nbt Integer Array From integer List",
    "nbt Nbt Integer Array From Integer list",
    "nbt Nbt Integer Array From Integer List",
    "Nbt nbt integer array from integer list",
    "Nbt nbt integer array from integer List",
    "Nbt nbt integer array from Integer list",
    "Nbt nbt integer array from Integer List",
    "Nbt nbt integer array From integer list",
    "Nbt nbt integer array From integer List",
    "Nbt nbt integer array From Integer list",
    "Nbt nbt integer array From Integer List",
    "Nbt nbt integer Array from integer list",
    "Nbt nbt integer Array from integer List",
    "Nbt nbt integer Array from Integer list",
    "Nbt nbt integer Array from Integer List",
    "Nbt nbt integer Array From integer list",
    "Nbt nbt integer Array From integer List",
    "Nbt nbt integer Array From Integer list",
    "Nbt nbt integer Array From Integer List",
    "Nbt nbt Integer array from integer list",
    "Nbt nbt Integer array from integer List",
    "Nbt nbt Integer array from Integer list",
    "Nbt nbt Integer array from Integer List",
    "Nbt nbt Integer array From integer list",
    "Nbt nbt Integer array From integer List",
    "Nbt nbt Integer array From Integer list",
    "Nbt nbt Integer array From Integer List",
    "Nbt nbt Integer Array from integer list",
    "Nbt nbt Integer Array from integer List",
    "Nbt nbt Integer Array from Integer list",
    "Nbt nbt Integer Array from Integer List",
    "Nbt nbt Integer Array From integer list",
    "Nbt nbt Integer Array From integer List",
    "Nbt nbt Integer Array From Integer list",
    "Nbt nbt Integer Array From Integer List",
    "Nbt Nbt integer array from integer list",
    "Nbt Nbt integer array from integer List",
    "Nbt Nbt integer array from Integer list",
    "Nbt Nbt integer array from Integer List",
    "Nbt Nbt integer array From integer list",
    "Nbt Nbt integer array From integer List",
    "Nbt Nbt integer array From Integer list",
    "Nbt Nbt integer array From Integer List",
    "Nbt Nbt integer Array from integer list",
    "Nbt Nbt integer Array from integer List",
    "Nbt Nbt integer Array from Integer list",
    "Nbt Nbt integer Array from Integer List",
    "Nbt Nbt integer Array From integer list",
    "Nbt Nbt integer Array From integer List",
    "Nbt Nbt integer Array From Integer list",
    "Nbt Nbt integer Array From Integer List",
    "Nbt Nbt Integer array from integer list",
    "Nbt Nbt Integer array from integer List",
    "Nbt Nbt Integer array from Integer list",
    "Nbt Nbt Integer array from Integer List",
    "Nbt Nbt Integer array From integer list",
    "Nbt Nbt Integer array From integer List",
    "Nbt Nbt Integer array From Integer list",
    "Nbt Nbt Integer array From Integer List",
    "Nbt Nbt Integer Array from integer list",
    "Nbt Nbt Integer Array from integer List",
    "Nbt Nbt Integer Array from Integer list",
    "Nbt Nbt Integer Array from Integer List",
    "Nbt Nbt Integer Array From integer list",
    "Nbt Nbt Integer Array From integer List",
    "Nbt Nbt Integer Array From Integer list",
    "Nbt Nbt Integer Array From Integer List",
    "nbt NBT integer array from integer list",
    "nbt NBT integer array from integer List",
    "nbt NBT integer array from Integer list",
    "nbt NBT integer array from Integer List",
    "nbt NBT integer array From integer list",
    "nbt NBT integer array From integer List",
    "nbt NBT integer array From Integer list",
    "nbt NBT integer array From Integer List",
    "nbt NBT integer Array from integer list",
    "nbt NBT integer Array from integer List",
    "nbt NBT integer Array from Integer list",
    "nbt NBT integer Array from Integer List",
    "nbt NBT integer Array From integer list",
    "nbt NBT integer Array From integer List",
    "nbt NBT integer Array From Integer list",
    "nbt NBT integer Array From Integer List",
    "nbt NBT Integer array from integer list",
    "nbt NBT Integer array from integer List",
    "nbt NBT Integer array from Integer list",
    "nbt NBT Integer array from Integer List",
    "nbt NBT Integer array From integer list",
    "nbt NBT Integer array From integer List",
    "nbt NBT Integer array From Integer list",
    "nbt NBT Integer array From Integer List",
    "nbt NBT Integer Array from integer list",
    "nbt NBT Integer Array from integer List",
    "nbt NBT Integer Array from Integer list",
    "nbt NBT Integer Array from Integer List",
    "nbt NBT Integer Array From integer list",
    "nbt NBT Integer Array From integer List",
    "nbt NBT Integer Array From Integer list",
    "nbt NBT Integer Array From Integer List",
    "Nbt NBT integer array from integer list",
    "Nbt NBT integer array from integer List",
    "Nbt NBT integer array from Integer list",
    "Nbt NBT integer array from Integer List",
    "Nbt NBT integer array From integer list",
    "Nbt NBT integer array From integer List",
    "Nbt NBT integer array From Integer list",
    "Nbt NBT integer array From Integer List",
    "Nbt NBT integer Array from integer list",
    "Nbt NBT integer Array from integer List",
    "Nbt NBT integer Array from Integer list",
    "Nbt NBT integer Array from Integer List",
    "Nbt NBT integer Array From integer list",
    "Nbt NBT integer Array From integer List",
    "Nbt NBT integer Array From Integer list",
    "Nbt NBT integer Array From Integer List",
    "Nbt NBT Integer array from integer list",
    "Nbt NBT Integer array from integer List",
    "Nbt NBT Integer array from Integer list",
    "Nbt NBT Integer array from Integer List",
    "Nbt NBT Integer array From integer list",
    "Nbt NBT Integer array From integer List",
    "Nbt NBT Integer array From Integer list",
    "Nbt NBT Integer array From Integer List",
    "Nbt NBT Integer Array from integer list",
    "Nbt NBT Integer Array from integer List",
    "Nbt NBT Integer Array from Integer list",
    "Nbt NBT Integer Array from Integer List",
    "Nbt NBT Integer Array From integer list",
    "Nbt NBT Integer Array From integer List",
    "Nbt NBT Integer Array From Integer list",
    "Nbt NBT Integer Array From Integer List",
    "NBT nbt integer array from integer list",
    "NBT nbt integer array from integer List",
    "NBT nbt integer array from Integer list",
    "NBT nbt integer array from Integer List",
    "NBT nbt integer array From integer list",
    "NBT nbt integer array From integer List",
    "NBT nbt integer array From Integer list",
    "NBT nbt integer array From Integer List",
    "NBT nbt integer Array from integer list",
    "NBT nbt integer Array from integer List",
    "NBT nbt integer Array from Integer list",
    "NBT nbt integer Array from Integer List",
    "NBT nbt integer Array From integer list",
    "NBT nbt integer Array From integer List",
    "NBT nbt integer Array From Integer list",
    "NBT nbt integer Array From Integer List",
    "NBT nbt Integer array from integer list",
    "NBT nbt Integer array from integer List",
    "NBT nbt Integer array from Integer list",
    "NBT nbt Integer array from Integer List",
    "NBT nbt Integer array From integer list",
    "NBT nbt Integer array From integer List",
    "NBT nbt Integer array From Integer list",
    "NBT nbt Integer array From Integer List",
    "NBT nbt Integer Array from integer list",
    "NBT nbt Integer Array from integer List",
    "NBT nbt Integer Array from Integer list",
    "NBT nbt Integer Array from Integer List",
    "NBT nbt Integer Array From integer list",
    "NBT nbt Integer Array From integer List",
    "NBT nbt Integer Array From Integer list",
    "NBT nbt Integer Array From Integer List",
    "NBT Nbt integer array from integer list",
    "NBT Nbt integer array from integer List",
    "NBT Nbt integer array from Integer list",
    "NBT Nbt integer array from Integer List",
    "NBT Nbt integer array From integer list",
    "NBT Nbt integer array From integer List",
    "NBT Nbt integer array From Integer list",
    "NBT Nbt integer array From Integer List",
    "NBT Nbt integer Array from integer list",
    "NBT Nbt integer Array from integer List",
    "NBT Nbt integer Array from Integer list",
    "NBT Nbt integer Array from Integer List",
    "NBT Nbt integer Array From integer list",
    "NBT Nbt integer Array From integer List",
    "NBT Nbt integer Array From Integer list",
    "NBT Nbt integer Array From Integer List",
    "NBT Nbt Integer array from integer list",
    "NBT Nbt Integer array from integer List",
    "NBT Nbt Integer array from Integer list",
    "NBT Nbt Integer array from Integer List",
    "NBT Nbt Integer array From integer list",
    "NBT Nbt Integer array From integer List",
    "NBT Nbt Integer array From Integer list",
    "NBT Nbt Integer array From Integer List",
    "NBT Nbt Integer Array from integer list",
    "NBT Nbt Integer Array from integer List",
    "NBT Nbt Integer Array from Integer list",
    "NBT Nbt Integer Array from Integer List",
    "NBT Nbt Integer Array From integer list",
    "NBT Nbt Integer Array From integer List",
    "NBT Nbt Integer Array From Integer list",
    "NBT Nbt Integer Array From Integer List",
    "NBT NBT integer array from integer list",
    "NBT NBT integer array from integer List",
    "NBT NBT integer array from Integer list",
    "NBT NBT integer array from Integer List",
    "NBT NBT integer array From integer list",
    "NBT NBT integer array From integer List",
    "NBT NBT integer array From Integer list",
    "NBT NBT integer array From Integer List",
    "NBT NBT integer Array from integer list",
    "NBT NBT integer Array from integer List",
    "NBT NBT integer Array from Integer list",
    "NBT NBT integer Array from Integer List",
    "NBT NBT integer Array From integer list",
    "NBT NBT integer Array From integer List",
    "NBT NBT integer Array From Integer list",
    "NBT NBT integer Array From Integer List",
    "NBT NBT Integer array from integer list",
    "NBT NBT Integer array from integer List",
    "NBT NBT Integer array from Integer list",
    "NBT NBT Integer array from Integer List",
    "NBT NBT Integer array From integer list",
    "NBT NBT Integer array From integer List",
    "NBT NBT Integer array From Integer list",
    "NBT NBT Integer array From Integer List",
    "NBT NBT Integer Array from integer list",
    "NBT NBT Integer Array from integer List",
    "NBT NBT Integer Array from Integer list",
    "NBT NBT Integer Array from Integer List",
    "NBT NBT Integer Array From integer list",
    "NBT NBT Integer Array From integer List",
    "NBT NBT Integer Array From Integer list",
    "NBT NBT Integer Array From Integer List",
  ];
  static override tooltipInfo =
    "Create an NBT Integer Array tag from the given Integer List value" as const;

  static override kind = "nbt" as const;
  static override renderPattern = "PREFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: { type: "List", listType: { type: "Integer" } },
          to: {
            type: "NBT",
          },
        },
        normalizeSignature
      ),
      function: (intList: iArray<Integer>): IntArrayTag => {
        return new IntArrayTag(intList);
      },
    });
  }
}
