import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { iBoolean } from "lib/IntegratedDynamicsClasses/typeWrappers/iBoolean";

export class OPERATOR_OBJECT_ITEMSTACK_ISRAWITEMEQUAL extends BaseOperator<
  Item,
  Operator<Item, iBoolean>
> {
  static override internalName =
    "integrateddynamics:itemstack_israwitemequal" as const;
  static override numericID = 57;
  static override nicknames = [
    "israwitemequal",
    "itemstackIsEqualRaw",
    "itemstackIsrawitemequal",
    "itemstackIsRawitemequal",
    "ItemstackIsrawitemequal",
    "rawItemEquals",
    "itemstack_is_equal_raw",
    "itemstack_is_rawitemequal",
    "itemstack_israwitemequal",
    "raw_item_equals",
  ];
  static override symbol = "=Raw=";
  static override interactName = "itemstackIsEqualRaw";
  static override operatorName = "israwitemequal" as const;
  static override displayName = "Raw item equals" as const;
  static override fullDisplayName = "Item Raw item equals" as const;
  static override stringDisplayNames = [
    "item raw item equals",
    "item raw item Equals",
    "item raw Item equals",
    "item raw Item Equals",
    "item Raw item equals",
    "item Raw item Equals",
    "item Raw Item equals",
    "item Raw Item Equals",
    "Item raw item equals",
    "Item raw item Equals",
    "Item raw Item equals",
    "Item raw Item Equals",
    "Item Raw item equals",
    "Item Raw item Equals",
    "Item Raw Item equals",
    "Item Raw Item Equals",
    "item raw itemstack equals",
    "item raw itemstack Equals",
    "item raw Itemstack equals",
    "item raw Itemstack Equals",
    "item raw itemStack equals",
    "item raw itemStack Equals",
    "item raw ItemStack equals",
    "item raw ItemStack Equals",
    "item Raw itemstack equals",
    "item Raw itemstack Equals",
    "item Raw Itemstack equals",
    "item Raw Itemstack Equals",
    "item Raw itemStack equals",
    "item Raw itemStack Equals",
    "item Raw ItemStack equals",
    "item Raw ItemStack Equals",
    "Item raw itemstack equals",
    "Item raw itemstack Equals",
    "Item raw Itemstack equals",
    "Item raw Itemstack Equals",
    "Item raw itemStack equals",
    "Item raw itemStack Equals",
    "Item raw ItemStack equals",
    "Item raw ItemStack Equals",
    "Item Raw itemstack equals",
    "Item Raw itemstack Equals",
    "Item Raw Itemstack equals",
    "Item Raw Itemstack Equals",
    "Item Raw itemStack equals",
    "Item Raw itemStack Equals",
    "Item Raw ItemStack equals",
    "Item Raw ItemStack Equals",
    "itemstack raw item equals",
    "itemstack raw item Equals",
    "itemstack raw Item equals",
    "itemstack raw Item Equals",
    "itemstack Raw item equals",
    "itemstack Raw item Equals",
    "itemstack Raw Item equals",
    "itemstack Raw Item Equals",
    "Itemstack raw item equals",
    "Itemstack raw item Equals",
    "Itemstack raw Item equals",
    "Itemstack raw Item Equals",
    "Itemstack Raw item equals",
    "Itemstack Raw item Equals",
    "Itemstack Raw Item equals",
    "Itemstack Raw Item Equals",
    "itemStack raw item equals",
    "itemStack raw item Equals",
    "itemStack raw Item equals",
    "itemStack raw Item Equals",
    "itemStack Raw item equals",
    "itemStack Raw item Equals",
    "itemStack Raw Item equals",
    "itemStack Raw Item Equals",
    "ItemStack raw item equals",
    "ItemStack raw item Equals",
    "ItemStack raw Item equals",
    "ItemStack raw Item Equals",
    "ItemStack Raw item equals",
    "ItemStack Raw item Equals",
    "ItemStack Raw Item equals",
    "ItemStack Raw Item Equals",
    "itemstack raw itemstack equals",
    "itemstack raw itemstack Equals",
    "itemstack raw Itemstack equals",
    "itemstack raw Itemstack Equals",
    "itemstack raw itemStack equals",
    "itemstack raw itemStack Equals",
    "itemstack raw ItemStack equals",
    "itemstack raw ItemStack Equals",
    "itemstack Raw itemstack equals",
    "itemstack Raw itemstack Equals",
    "itemstack Raw Itemstack equals",
    "itemstack Raw Itemstack Equals",
    "itemstack Raw itemStack equals",
    "itemstack Raw itemStack Equals",
    "itemstack Raw ItemStack equals",
    "itemstack Raw ItemStack Equals",
    "Itemstack raw itemstack equals",
    "Itemstack raw itemstack Equals",
    "Itemstack raw Itemstack equals",
    "Itemstack raw Itemstack Equals",
    "Itemstack raw itemStack equals",
    "Itemstack raw itemStack Equals",
    "Itemstack raw ItemStack equals",
    "Itemstack raw ItemStack Equals",
    "Itemstack Raw itemstack equals",
    "Itemstack Raw itemstack Equals",
    "Itemstack Raw Itemstack equals",
    "Itemstack Raw Itemstack Equals",
    "Itemstack Raw itemStack equals",
    "Itemstack Raw itemStack Equals",
    "Itemstack Raw ItemStack equals",
    "Itemstack Raw ItemStack Equals",
    "itemStack raw itemstack equals",
    "itemStack raw itemstack Equals",
    "itemStack raw Itemstack equals",
    "itemStack raw Itemstack Equals",
    "itemStack raw itemStack equals",
    "itemStack raw itemStack Equals",
    "itemStack raw ItemStack equals",
    "itemStack raw ItemStack Equals",
    "itemStack Raw itemstack equals",
    "itemStack Raw itemstack Equals",
    "itemStack Raw Itemstack equals",
    "itemStack Raw Itemstack Equals",
    "itemStack Raw itemStack equals",
    "itemStack Raw itemStack Equals",
    "itemStack Raw ItemStack equals",
    "itemStack Raw ItemStack Equals",
    "ItemStack raw itemstack equals",
    "ItemStack raw itemstack Equals",
    "ItemStack raw Itemstack equals",
    "ItemStack raw Itemstack Equals",
    "ItemStack raw itemStack equals",
    "ItemStack raw itemStack Equals",
    "ItemStack raw ItemStack equals",
    "ItemStack raw ItemStack Equals",
    "ItemStack Raw itemstack equals",
    "ItemStack Raw itemstack Equals",
    "ItemStack Raw Itemstack equals",
    "ItemStack Raw Itemstack Equals",
    "ItemStack Raw itemStack equals",
    "ItemStack Raw itemStack Equals",
    "ItemStack Raw ItemStack equals",
    "ItemStack Raw ItemStack Equals",
    "raw item equals",
    "raw item Equals",
    "raw Item equals",
    "raw Item Equals",
    "Raw item equals",
    "Raw item Equals",
    "Raw Item equals",
    "Raw Item Equals",
    "raw itemstack equals",
    "raw itemstack Equals",
    "raw Itemstack equals",
    "raw Itemstack Equals",
    "raw itemStack equals",
    "raw itemStack Equals",
    "raw ItemStack equals",
    "raw ItemStack Equals",
    "Raw itemstack equals",
    "Raw itemstack Equals",
    "Raw Itemstack equals",
    "Raw Itemstack Equals",
    "Raw itemStack equals",
    "Raw itemStack Equals",
    "Raw ItemStack equals",
    "Raw ItemStack Equals",
  ];
  static override tooltipInfo =
    "If the raw items of the given items are equal, ignoring NBT and damage value." as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "INFIX" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Function",
            from: {
              type: "Item",
            },
            to: {
              type: "Boolean",
            },
          },
        },
        normalizeSignature
      ),
      function: (item1: Item): TypeLambda<Item, iBoolean> => {
        return (item2: Item): iBoolean => {
          return new iBoolean(
            item1.getUniqueName().valueOf() === item2.getUniqueName().valueOf()
          );
        };
      },
      flipTarget: "OBJECT_ITEMSTACK_ISRAWITEMEQUAL",
    });
  }
}
