import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";

export class OPERATOR_OBJECT_FLUIDSTACK_SOUND_FLUID_VAPORIZE extends BaseOperator<
  Fluid,
  iString
> {
  static override internalName =
    "integrateddynamics:fluidstack_sound_fluid_vaporize" as const;
  static override numericID = 275;
  static override nicknames = [
    "fluidSoundFluidVaporize",
    "fluidstackFluidVaporizeSound",
    "fluidstackSoundFluidVaporize",
    "fluidStackSoundFluidVaporize",
    "FluidstackSoundFluidVaporize",
    "soundFluidVaporize",
    "fluid_sound_fluid_vaporize",
    "fluid_stack_sound_fluid_vaporize",
    "fluidstack_fluid_vaporize_sound",
    "fluidstack_sound_fluid_vaporize",
    "fluidstackSound_fluid_vaporize",
    "sound_fluid_vaporize",
  ];
  static override symbol = "sound_fluid_vaporize";
  static override interactName = "fluidstackFluidVaporizeSound";
  static override operatorName = "sound_fluid_vaporize" as const;
  static override displayName = "Fluid vaporize sound" as const;
  static override fullDisplayName = "Fluid Fluid vaporize sound" as const;
  static override stringDisplayNames = [
    "fluid fluid vaporize sound",
    "fluid fluid vaporize Sound",
    "fluid fluid Vaporize sound",
    "fluid fluid Vaporize Sound",
    "fluid Fluid vaporize sound",
    "fluid Fluid vaporize Sound",
    "fluid Fluid Vaporize sound",
    "fluid Fluid Vaporize Sound",
    "Fluid fluid vaporize sound",
    "Fluid fluid vaporize Sound",
    "Fluid fluid Vaporize sound",
    "Fluid fluid Vaporize Sound",
    "Fluid Fluid vaporize sound",
    "Fluid Fluid vaporize Sound",
    "Fluid Fluid Vaporize sound",
    "Fluid Fluid Vaporize Sound",
    "fluid fluidstack vaporize sound",
    "fluid fluidstack vaporize Sound",
    "fluid fluidstack Vaporize sound",
    "fluid fluidstack Vaporize Sound",
    "fluid Fluidstack vaporize sound",
    "fluid Fluidstack vaporize Sound",
    "fluid Fluidstack Vaporize sound",
    "fluid Fluidstack Vaporize Sound",
    "fluid fluidStack vaporize sound",
    "fluid fluidStack vaporize Sound",
    "fluid fluidStack Vaporize sound",
    "fluid fluidStack Vaporize Sound",
    "fluid FluidStack vaporize sound",
    "fluid FluidStack vaporize Sound",
    "fluid FluidStack Vaporize sound",
    "fluid FluidStack Vaporize Sound",
    "Fluid fluidstack vaporize sound",
    "Fluid fluidstack vaporize Sound",
    "Fluid fluidstack Vaporize sound",
    "Fluid fluidstack Vaporize Sound",
    "Fluid Fluidstack vaporize sound",
    "Fluid Fluidstack vaporize Sound",
    "Fluid Fluidstack Vaporize sound",
    "Fluid Fluidstack Vaporize Sound",
    "Fluid fluidStack vaporize sound",
    "Fluid fluidStack vaporize Sound",
    "Fluid fluidStack Vaporize sound",
    "Fluid fluidStack Vaporize Sound",
    "Fluid FluidStack vaporize sound",
    "Fluid FluidStack vaporize Sound",
    "Fluid FluidStack Vaporize sound",
    "Fluid FluidStack Vaporize Sound",
    "fluidstack fluid vaporize sound",
    "fluidstack fluid vaporize Sound",
    "fluidstack fluid Vaporize sound",
    "fluidstack fluid Vaporize Sound",
    "fluidstack Fluid vaporize sound",
    "fluidstack Fluid vaporize Sound",
    "fluidstack Fluid Vaporize sound",
    "fluidstack Fluid Vaporize Sound",
    "Fluidstack fluid vaporize sound",
    "Fluidstack fluid vaporize Sound",
    "Fluidstack fluid Vaporize sound",
    "Fluidstack fluid Vaporize Sound",
    "Fluidstack Fluid vaporize sound",
    "Fluidstack Fluid vaporize Sound",
    "Fluidstack Fluid Vaporize sound",
    "Fluidstack Fluid Vaporize Sound",
    "fluidStack fluid vaporize sound",
    "fluidStack fluid vaporize Sound",
    "fluidStack fluid Vaporize sound",
    "fluidStack fluid Vaporize Sound",
    "fluidStack Fluid vaporize sound",
    "fluidStack Fluid vaporize Sound",
    "fluidStack Fluid Vaporize sound",
    "fluidStack Fluid Vaporize Sound",
    "FluidStack fluid vaporize sound",
    "FluidStack fluid vaporize Sound",
    "FluidStack fluid Vaporize sound",
    "FluidStack fluid Vaporize Sound",
    "FluidStack Fluid vaporize sound",
    "FluidStack Fluid vaporize Sound",
    "FluidStack Fluid Vaporize sound",
    "FluidStack Fluid Vaporize Sound",
    "fluidstack fluidstack vaporize sound",
    "fluidstack fluidstack vaporize Sound",
    "fluidstack fluidstack Vaporize sound",
    "fluidstack fluidstack Vaporize Sound",
    "fluidstack Fluidstack vaporize sound",
    "fluidstack Fluidstack vaporize Sound",
    "fluidstack Fluidstack Vaporize sound",
    "fluidstack Fluidstack Vaporize Sound",
    "fluidstack fluidStack vaporize sound",
    "fluidstack fluidStack vaporize Sound",
    "fluidstack fluidStack Vaporize sound",
    "fluidstack fluidStack Vaporize Sound",
    "fluidstack FluidStack vaporize sound",
    "fluidstack FluidStack vaporize Sound",
    "fluidstack FluidStack Vaporize sound",
    "fluidstack FluidStack Vaporize Sound",
    "Fluidstack fluidstack vaporize sound",
    "Fluidstack fluidstack vaporize Sound",
    "Fluidstack fluidstack Vaporize sound",
    "Fluidstack fluidstack Vaporize Sound",
    "Fluidstack Fluidstack vaporize sound",
    "Fluidstack Fluidstack vaporize Sound",
    "Fluidstack Fluidstack Vaporize sound",
    "Fluidstack Fluidstack Vaporize Sound",
    "Fluidstack fluidStack vaporize sound",
    "Fluidstack fluidStack vaporize Sound",
    "Fluidstack fluidStack Vaporize sound",
    "Fluidstack fluidStack Vaporize Sound",
    "Fluidstack FluidStack vaporize sound",
    "Fluidstack FluidStack vaporize Sound",
    "Fluidstack FluidStack Vaporize sound",
    "Fluidstack FluidStack Vaporize Sound",
    "fluidStack fluidstack vaporize sound",
    "fluidStack fluidstack vaporize Sound",
    "fluidStack fluidstack Vaporize sound",
    "fluidStack fluidstack Vaporize Sound",
    "fluidStack Fluidstack vaporize sound",
    "fluidStack Fluidstack vaporize Sound",
    "fluidStack Fluidstack Vaporize sound",
    "fluidStack Fluidstack Vaporize Sound",
    "fluidStack fluidStack vaporize sound",
    "fluidStack fluidStack vaporize Sound",
    "fluidStack fluidStack Vaporize sound",
    "fluidStack fluidStack Vaporize Sound",
    "fluidStack FluidStack vaporize sound",
    "fluidStack FluidStack vaporize Sound",
    "fluidStack FluidStack Vaporize sound",
    "fluidStack FluidStack Vaporize Sound",
    "FluidStack fluidstack vaporize sound",
    "FluidStack fluidstack vaporize Sound",
    "FluidStack fluidstack Vaporize sound",
    "FluidStack fluidstack Vaporize Sound",
    "FluidStack Fluidstack vaporize sound",
    "FluidStack Fluidstack vaporize Sound",
    "FluidStack Fluidstack Vaporize sound",
    "FluidStack Fluidstack Vaporize Sound",
    "FluidStack fluidStack vaporize sound",
    "FluidStack fluidStack vaporize Sound",
    "FluidStack fluidStack Vaporize sound",
    "FluidStack fluidStack Vaporize Sound",
    "FluidStack FluidStack vaporize sound",
    "FluidStack FluidStack vaporize Sound",
    "FluidStack FluidStack Vaporize sound",
    "FluidStack FluidStack Vaporize Sound",
    "fluid vaporize sound",
    "fluid vaporize Sound",
    "fluid Vaporize sound",
    "fluid Vaporize Sound",
    "Fluid vaporize sound",
    "Fluid vaporize Sound",
    "Fluid Vaporize sound",
    "Fluid Vaporize Sound",
    "fluidstack vaporize sound",
    "fluidstack vaporize Sound",
    "fluidstack Vaporize sound",
    "fluidstack Vaporize Sound",
    "Fluidstack vaporize sound",
    "Fluidstack vaporize Sound",
    "Fluidstack Vaporize sound",
    "Fluidstack Vaporize Sound",
    "fluidStack vaporize sound",
    "fluidStack vaporize Sound",
    "fluidStack Vaporize sound",
    "fluidStack Vaporize Sound",
    "FluidStack vaporize sound",
    "FluidStack vaporize Sound",
    "FluidStack Vaporize sound",
    "FluidStack Vaporize Sound",
  ];
  static override kind = "fluidstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: {
            type: "String",
          },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): iString => {
        return fluid.getFluidVaporizeSound();
      },
    });
  }
}
