import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";
import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { Properties } from "lib/IntegratedDynamicsClasses/Properties";

export class OPERATOR_OBJECT_FLUIDSTACK_WITH_NBT extends BaseOperator<
  Fluid,
  CompoundTag
> {
  static override internalName =
    "integrateddynamics:fluidstack_withnbt" as const;
  static override numericID = 300;
  static override nicknames = [
    "fluidstackFluidwithtag",
    "fluidstackWithNBT",
    "fluidStackWithNbt",
    "fluidStackWithNBT",
    "fluidWithNBT",
    "fluidwithtag",
    "fluid_stack_with_n_b_t",
    "fluid_stack_with_nbt",
    "fluid_with_n_b_t",
    "fluidstack_fluidwithtag",
    "fluidstack_with_n_b_t",
  ];
  static override symbol = "with_nbt";
  static override interactName = "fluidstackWithNBT";
  static override operatorName = "fluidwithtag" as const;
  static override displayName = "Fluid With Tag" as const;
  static override fullDisplayName = "Fluid Fluid With Tag" as const;
  static override stringDisplayNames = [
    "fluid fluid with tag",
    "fluid fluid with Tag",
    "fluid fluid With tag",
    "fluid fluid With Tag",
    "fluid Fluid with tag",
    "fluid Fluid with Tag",
    "fluid Fluid With tag",
    "fluid Fluid With Tag",
    "Fluid fluid with tag",
    "Fluid fluid with Tag",
    "Fluid fluid With tag",
    "Fluid fluid With Tag",
    "Fluid Fluid with tag",
    "Fluid Fluid with Tag",
    "Fluid Fluid With tag",
    "Fluid Fluid With Tag",
    "fluid fluidstack with tag",
    "fluid fluidstack with Tag",
    "fluid fluidstack With tag",
    "fluid fluidstack With Tag",
    "fluid Fluidstack with tag",
    "fluid Fluidstack with Tag",
    "fluid Fluidstack With tag",
    "fluid Fluidstack With Tag",
    "fluid fluidStack with tag",
    "fluid fluidStack with Tag",
    "fluid fluidStack With tag",
    "fluid fluidStack With Tag",
    "fluid FluidStack with tag",
    "fluid FluidStack with Tag",
    "fluid FluidStack With tag",
    "fluid FluidStack With Tag",
    "Fluid fluidstack with tag",
    "Fluid fluidstack with Tag",
    "Fluid fluidstack With tag",
    "Fluid fluidstack With Tag",
    "Fluid Fluidstack with tag",
    "Fluid Fluidstack with Tag",
    "Fluid Fluidstack With tag",
    "Fluid Fluidstack With Tag",
    "Fluid fluidStack with tag",
    "Fluid fluidStack with Tag",
    "Fluid fluidStack With tag",
    "Fluid fluidStack With Tag",
    "Fluid FluidStack with tag",
    "Fluid FluidStack with Tag",
    "Fluid FluidStack With tag",
    "Fluid FluidStack With Tag",
    "fluidstack fluid with tag",
    "fluidstack fluid with Tag",
    "fluidstack fluid With tag",
    "fluidstack fluid With Tag",
    "fluidstack Fluid with tag",
    "fluidstack Fluid with Tag",
    "fluidstack Fluid With tag",
    "fluidstack Fluid With Tag",
    "Fluidstack fluid with tag",
    "Fluidstack fluid with Tag",
    "Fluidstack fluid With tag",
    "Fluidstack fluid With Tag",
    "Fluidstack Fluid with tag",
    "Fluidstack Fluid with Tag",
    "Fluidstack Fluid With tag",
    "Fluidstack Fluid With Tag",
    "fluidStack fluid with tag",
    "fluidStack fluid with Tag",
    "fluidStack fluid With tag",
    "fluidStack fluid With Tag",
    "fluidStack Fluid with tag",
    "fluidStack Fluid with Tag",
    "fluidStack Fluid With tag",
    "fluidStack Fluid With Tag",
    "FluidStack fluid with tag",
    "FluidStack fluid with Tag",
    "FluidStack fluid With tag",
    "FluidStack fluid With Tag",
    "FluidStack Fluid with tag",
    "FluidStack Fluid with Tag",
    "FluidStack Fluid With tag",
    "FluidStack Fluid With Tag",
    "fluidstack fluidstack with tag",
    "fluidstack fluidstack with Tag",
    "fluidstack fluidstack With tag",
    "fluidstack fluidstack With Tag",
    "fluidstack Fluidstack with tag",
    "fluidstack Fluidstack with Tag",
    "fluidstack Fluidstack With tag",
    "fluidstack Fluidstack With Tag",
    "fluidstack fluidStack with tag",
    "fluidstack fluidStack with Tag",
    "fluidstack fluidStack With tag",
    "fluidstack fluidStack With Tag",
    "fluidstack FluidStack with tag",
    "fluidstack FluidStack with Tag",
    "fluidstack FluidStack With tag",
    "fluidstack FluidStack With Tag",
    "Fluidstack fluidstack with tag",
    "Fluidstack fluidstack with Tag",
    "Fluidstack fluidstack With tag",
    "Fluidstack fluidstack With Tag",
    "Fluidstack Fluidstack with tag",
    "Fluidstack Fluidstack with Tag",
    "Fluidstack Fluidstack With tag",
    "Fluidstack Fluidstack With Tag",
    "Fluidstack fluidStack with tag",
    "Fluidstack fluidStack with Tag",
    "Fluidstack fluidStack With tag",
    "Fluidstack fluidStack With Tag",
    "Fluidstack FluidStack with tag",
    "Fluidstack FluidStack with Tag",
    "Fluidstack FluidStack With tag",
    "Fluidstack FluidStack With Tag",
    "fluidStack fluidstack with tag",
    "fluidStack fluidstack with Tag",
    "fluidStack fluidstack With tag",
    "fluidStack fluidstack With Tag",
    "fluidStack Fluidstack with tag",
    "fluidStack Fluidstack with Tag",
    "fluidStack Fluidstack With tag",
    "fluidStack Fluidstack With Tag",
    "fluidStack fluidStack with tag",
    "fluidStack fluidStack with Tag",
    "fluidStack fluidStack With tag",
    "fluidStack fluidStack With Tag",
    "fluidStack FluidStack with tag",
    "fluidStack FluidStack with Tag",
    "fluidStack FluidStack With tag",
    "fluidStack FluidStack With Tag",
    "FluidStack fluidstack with tag",
    "FluidStack fluidstack with Tag",
    "FluidStack fluidstack With tag",
    "FluidStack fluidstack With Tag",
    "FluidStack Fluidstack with tag",
    "FluidStack Fluidstack with Tag",
    "FluidStack Fluidstack With tag",
    "FluidStack Fluidstack With Tag",
    "FluidStack fluidStack with tag",
    "FluidStack fluidStack with Tag",
    "FluidStack fluidStack With tag",
    "FluidStack fluidStack With Tag",
    "FluidStack FluidStack with tag",
    "FluidStack FluidStack with Tag",
    "FluidStack FluidStack With tag",
    "FluidStack FluidStack With Tag",
    "fluid with tag",
    "fluid with Tag",
    "fluid With tag",
    "fluid With Tag",
    "Fluid with tag",
    "Fluid with Tag",
    "Fluid With tag",
    "Fluid With Tag",
    "fluidstack with tag",
    "fluidstack with Tag",
    "fluidstack With tag",
    "fluidstack With Tag",
    "Fluidstack with tag",
    "Fluidstack with Tag",
    "Fluidstack With tag",
    "Fluidstack With Tag",
    "fluidStack with tag",
    "fluidStack with Tag",
    "fluidStack With tag",
    "fluidStack With Tag",
    "FluidStack with tag",
    "FluidStack with Tag",
    "FluidStack With tag",
    "FluidStack With Tag",
  ];
  static override kind = "fluidstack" as const;
  static override renderPattern = "INFIX_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: {
            type: "Function",
            from: {
              type: "NBT",
            },
            to: {
              type: "Fluid",
            },
          },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): TypeLambda<CompoundTag, Fluid> => {
        return (nbt: CompoundTag): Fluid => {
          return new Fluid(new Properties({ nbt: nbt }), fluid);
        };
      },
    });
  }
}
