import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";
import { Integer } from "lib/JavaNumberClasses/Integer";
import { Properties } from "lib/IntegratedDynamicsClasses/Properties";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";

export class OPERATOR_OBJECT_FLUIDSTACK_WITH_AMOUNT extends BaseOperator<
  Fluid,
  Operator<Integer, Fluid>
> {
  static override internalName =
    "integrateddynamics:fluidstack_with_amount" as const;
  static override numericID = 266;
  static override nicknames = [
    "fluidstackWithAmount",
    "fluidStackWithAmount",
    "FluidstackWithAmount",
    "fluidWithAmount",
    "withAmount",
    "fluid_stack_with_amount",
    "fluid_with_amount",
    "fluidstack_with_amount",
    "fluidstackWith_amount",
    "with_amount",
  ];
  static override symbol = "with_amount";
  static override interactName = "fluidstackWithAmount";
  static override operatorName = "with_amount" as const;
  static override displayName = "Fluid With Amount" as const;
  static override fullDisplayName = "Fluid Fluid With Amount" as const;
  static override stringDisplayNames = [
    "fluid fluid with amount",
    "fluid fluid with Amount",
    "fluid fluid With amount",
    "fluid fluid With Amount",
    "fluid Fluid with amount",
    "fluid Fluid with Amount",
    "fluid Fluid With amount",
    "fluid Fluid With Amount",
    "Fluid fluid with amount",
    "Fluid fluid with Amount",
    "Fluid fluid With amount",
    "Fluid fluid With Amount",
    "Fluid Fluid with amount",
    "Fluid Fluid with Amount",
    "Fluid Fluid With amount",
    "Fluid Fluid With Amount",
    "fluid fluidstack with amount",
    "fluid fluidstack with Amount",
    "fluid fluidstack With amount",
    "fluid fluidstack With Amount",
    "fluid Fluidstack with amount",
    "fluid Fluidstack with Amount",
    "fluid Fluidstack With amount",
    "fluid Fluidstack With Amount",
    "fluid fluidStack with amount",
    "fluid fluidStack with Amount",
    "fluid fluidStack With amount",
    "fluid fluidStack With Amount",
    "fluid FluidStack with amount",
    "fluid FluidStack with Amount",
    "fluid FluidStack With amount",
    "fluid FluidStack With Amount",
    "Fluid fluidstack with amount",
    "Fluid fluidstack with Amount",
    "Fluid fluidstack With amount",
    "Fluid fluidstack With Amount",
    "Fluid Fluidstack with amount",
    "Fluid Fluidstack with Amount",
    "Fluid Fluidstack With amount",
    "Fluid Fluidstack With Amount",
    "Fluid fluidStack with amount",
    "Fluid fluidStack with Amount",
    "Fluid fluidStack With amount",
    "Fluid fluidStack With Amount",
    "Fluid FluidStack with amount",
    "Fluid FluidStack with Amount",
    "Fluid FluidStack With amount",
    "Fluid FluidStack With Amount",
    "fluidstack fluid with amount",
    "fluidstack fluid with Amount",
    "fluidstack fluid With amount",
    "fluidstack fluid With Amount",
    "fluidstack Fluid with amount",
    "fluidstack Fluid with Amount",
    "fluidstack Fluid With amount",
    "fluidstack Fluid With Amount",
    "Fluidstack fluid with amount",
    "Fluidstack fluid with Amount",
    "Fluidstack fluid With amount",
    "Fluidstack fluid With Amount",
    "Fluidstack Fluid with amount",
    "Fluidstack Fluid with Amount",
    "Fluidstack Fluid With amount",
    "Fluidstack Fluid With Amount",
    "fluidStack fluid with amount",
    "fluidStack fluid with Amount",
    "fluidStack fluid With amount",
    "fluidStack fluid With Amount",
    "fluidStack Fluid with amount",
    "fluidStack Fluid with Amount",
    "fluidStack Fluid With amount",
    "fluidStack Fluid With Amount",
    "FluidStack fluid with amount",
    "FluidStack fluid with Amount",
    "FluidStack fluid With amount",
    "FluidStack fluid With Amount",
    "FluidStack Fluid with amount",
    "FluidStack Fluid with Amount",
    "FluidStack Fluid With amount",
    "FluidStack Fluid With Amount",
    "fluidstack fluidstack with amount",
    "fluidstack fluidstack with Amount",
    "fluidstack fluidstack With amount",
    "fluidstack fluidstack With Amount",
    "fluidstack Fluidstack with amount",
    "fluidstack Fluidstack with Amount",
    "fluidstack Fluidstack With amount",
    "fluidstack Fluidstack With Amount",
    "fluidstack fluidStack with amount",
    "fluidstack fluidStack with Amount",
    "fluidstack fluidStack With amount",
    "fluidstack fluidStack With Amount",
    "fluidstack FluidStack with amount",
    "fluidstack FluidStack with Amount",
    "fluidstack FluidStack With amount",
    "fluidstack FluidStack With Amount",
    "Fluidstack fluidstack with amount",
    "Fluidstack fluidstack with Amount",
    "Fluidstack fluidstack With amount",
    "Fluidstack fluidstack With Amount",
    "Fluidstack Fluidstack with amount",
    "Fluidstack Fluidstack with Amount",
    "Fluidstack Fluidstack With amount",
    "Fluidstack Fluidstack With Amount",
    "Fluidstack fluidStack with amount",
    "Fluidstack fluidStack with Amount",
    "Fluidstack fluidStack With amount",
    "Fluidstack fluidStack With Amount",
    "Fluidstack FluidStack with amount",
    "Fluidstack FluidStack with Amount",
    "Fluidstack FluidStack With amount",
    "Fluidstack FluidStack With Amount",
    "fluidStack fluidstack with amount",
    "fluidStack fluidstack with Amount",
    "fluidStack fluidstack With amount",
    "fluidStack fluidstack With Amount",
    "fluidStack Fluidstack with amount",
    "fluidStack Fluidstack with Amount",
    "fluidStack Fluidstack With amount",
    "fluidStack Fluidstack With Amount",
    "fluidStack fluidStack with amount",
    "fluidStack fluidStack with Amount",
    "fluidStack fluidStack With amount",
    "fluidStack fluidStack With Amount",
    "fluidStack FluidStack with amount",
    "fluidStack FluidStack with Amount",
    "fluidStack FluidStack With amount",
    "fluidStack FluidStack With Amount",
    "FluidStack fluidstack with amount",
    "FluidStack fluidstack with Amount",
    "FluidStack fluidstack With amount",
    "FluidStack fluidstack With Amount",
    "FluidStack Fluidstack with amount",
    "FluidStack Fluidstack with Amount",
    "FluidStack Fluidstack With amount",
    "FluidStack Fluidstack With Amount",
    "FluidStack fluidStack with amount",
    "FluidStack fluidStack with Amount",
    "FluidStack fluidStack With amount",
    "FluidStack fluidStack With Amount",
    "FluidStack FluidStack with amount",
    "FluidStack FluidStack with Amount",
    "FluidStack FluidStack With amount",
    "FluidStack FluidStack With Amount",
    "fluid with amount",
    "fluid with Amount",
    "fluid With amount",
    "fluid With Amount",
    "Fluid with amount",
    "Fluid with Amount",
    "Fluid With amount",
    "Fluid With Amount",
    "fluidstack with amount",
    "fluidstack with Amount",
    "fluidstack With amount",
    "fluidstack With Amount",
    "Fluidstack with amount",
    "Fluidstack with Amount",
    "Fluidstack With amount",
    "Fluidstack With Amount",
    "fluidStack with amount",
    "fluidStack with Amount",
    "fluidStack With amount",
    "fluidStack With Amount",
    "FluidStack with amount",
    "FluidStack with Amount",
    "FluidStack With amount",
    "FluidStack With Amount",
  ];
  static override tooltipInfo =
    "Copy the given fluid with the given amount" as const;

  static override kind = "fluidstack" as const;
  static override renderPattern = "INFIX" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: {
            type: "Function",
            from: {
              type: "Integer",
            },
            to: {
              type: "Fluid",
            },
          },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): TypeLambda<Integer, Fluid> => {
        return (amount: Integer): Fluid => {
          return new Fluid(new Properties({ amount }), fluid);
        };
      },
    });
  }
}
