import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";
import { RegistryHub } from "lib/IntegratedDynamicsClasses/registries/registryHub";
import { Properties } from "lib/IntegratedDynamicsClasses/Properties";

export class OPERATOR_OBJECT_FLUIDSTACK_BY_NAME extends BaseOperator<
  iString,
  Fluid
> {
  static override internalName =
    "integrateddynamics:fluidstack_by_name" as const;
  static override numericID = 303;
  static override nicknames = [
    "fluidbyname",
    "fluidByName",
    "fluidstackByName",
    "FluidstackByName",
    "fluidstackFluidbyname",
    "stringFluidByName",
    "fluid_by_name",
    "fluidstack_by_name",
    "fluidstack_fluidbyname",
    "string_fluid_by_name",
  ];
  static override symbol = "fluid_by_name";
  static override interactName = "stringFluidByName";
  static override operatorName = "fluidbyname" as const;
  static override displayName = "Fluid By Name" as const;
  static override fullDisplayName = "Fluid Fluid By Name" as const;
  static override stringDisplayNames = [
    "fluid fluid by name",
    "fluid fluid by Name",
    "fluid fluid By name",
    "fluid fluid By Name",
    "fluid Fluid by name",
    "fluid Fluid by Name",
    "fluid Fluid By name",
    "fluid Fluid By Name",
    "Fluid fluid by name",
    "Fluid fluid by Name",
    "Fluid fluid By name",
    "Fluid fluid By Name",
    "Fluid Fluid by name",
    "Fluid Fluid by Name",
    "Fluid Fluid By name",
    "Fluid Fluid By Name",
    "fluid fluidstack by name",
    "fluid fluidstack by Name",
    "fluid fluidstack By name",
    "fluid fluidstack By Name",
    "fluid Fluidstack by name",
    "fluid Fluidstack by Name",
    "fluid Fluidstack By name",
    "fluid Fluidstack By Name",
    "fluid fluidStack by name",
    "fluid fluidStack by Name",
    "fluid fluidStack By name",
    "fluid fluidStack By Name",
    "fluid FluidStack by name",
    "fluid FluidStack by Name",
    "fluid FluidStack By name",
    "fluid FluidStack By Name",
    "Fluid fluidstack by name",
    "Fluid fluidstack by Name",
    "Fluid fluidstack By name",
    "Fluid fluidstack By Name",
    "Fluid Fluidstack by name",
    "Fluid Fluidstack by Name",
    "Fluid Fluidstack By name",
    "Fluid Fluidstack By Name",
    "Fluid fluidStack by name",
    "Fluid fluidStack by Name",
    "Fluid fluidStack By name",
    "Fluid fluidStack By Name",
    "Fluid FluidStack by name",
    "Fluid FluidStack by Name",
    "Fluid FluidStack By name",
    "Fluid FluidStack By Name",
    "fluidstack fluid by name",
    "fluidstack fluid by Name",
    "fluidstack fluid By name",
    "fluidstack fluid By Name",
    "fluidstack Fluid by name",
    "fluidstack Fluid by Name",
    "fluidstack Fluid By name",
    "fluidstack Fluid By Name",
    "Fluidstack fluid by name",
    "Fluidstack fluid by Name",
    "Fluidstack fluid By name",
    "Fluidstack fluid By Name",
    "Fluidstack Fluid by name",
    "Fluidstack Fluid by Name",
    "Fluidstack Fluid By name",
    "Fluidstack Fluid By Name",
    "fluidStack fluid by name",
    "fluidStack fluid by Name",
    "fluidStack fluid By name",
    "fluidStack fluid By Name",
    "fluidStack Fluid by name",
    "fluidStack Fluid by Name",
    "fluidStack Fluid By name",
    "fluidStack Fluid By Name",
    "FluidStack fluid by name",
    "FluidStack fluid by Name",
    "FluidStack fluid By name",
    "FluidStack fluid By Name",
    "FluidStack Fluid by name",
    "FluidStack Fluid by Name",
    "FluidStack Fluid By name",
    "FluidStack Fluid By Name",
    "fluidstack fluidstack by name",
    "fluidstack fluidstack by Name",
    "fluidstack fluidstack By name",
    "fluidstack fluidstack By Name",
    "fluidstack Fluidstack by name",
    "fluidstack Fluidstack by Name",
    "fluidstack Fluidstack By name",
    "fluidstack Fluidstack By Name",
    "fluidstack fluidStack by name",
    "fluidstack fluidStack by Name",
    "fluidstack fluidStack By name",
    "fluidstack fluidStack By Name",
    "fluidstack FluidStack by name",
    "fluidstack FluidStack by Name",
    "fluidstack FluidStack By name",
    "fluidstack FluidStack By Name",
    "Fluidstack fluidstack by name",
    "Fluidstack fluidstack by Name",
    "Fluidstack fluidstack By name",
    "Fluidstack fluidstack By Name",
    "Fluidstack Fluidstack by name",
    "Fluidstack Fluidstack by Name",
    "Fluidstack Fluidstack By name",
    "Fluidstack Fluidstack By Name",
    "Fluidstack fluidStack by name",
    "Fluidstack fluidStack by Name",
    "Fluidstack fluidStack By name",
    "Fluidstack fluidStack By Name",
    "Fluidstack FluidStack by name",
    "Fluidstack FluidStack by Name",
    "Fluidstack FluidStack By name",
    "Fluidstack FluidStack By Name",
    "fluidStack fluidstack by name",
    "fluidStack fluidstack by Name",
    "fluidStack fluidstack By name",
    "fluidStack fluidstack By Name",
    "fluidStack Fluidstack by name",
    "fluidStack Fluidstack by Name",
    "fluidStack Fluidstack By name",
    "fluidStack Fluidstack By Name",
    "fluidStack fluidStack by name",
    "fluidStack fluidStack by Name",
    "fluidStack fluidStack By name",
    "fluidStack fluidStack By Name",
    "fluidStack FluidStack by name",
    "fluidStack FluidStack by Name",
    "fluidStack FluidStack By name",
    "fluidStack FluidStack By Name",
    "FluidStack fluidstack by name",
    "FluidStack fluidstack by Name",
    "FluidStack fluidstack By name",
    "FluidStack fluidstack By Name",
    "FluidStack Fluidstack by name",
    "FluidStack Fluidstack by Name",
    "FluidStack Fluidstack By name",
    "FluidStack Fluidstack By Name",
    "FluidStack fluidStack by name",
    "FluidStack fluidStack by Name",
    "FluidStack fluidStack By name",
    "FluidStack fluidStack By Name",
    "FluidStack FluidStack by name",
    "FluidStack FluidStack by Name",
    "FluidStack FluidStack By name",
    "FluidStack FluidStack By Name",
    "fluid by name",
    "fluid by Name",
    "fluid By name",
    "fluid By Name",
    "Fluid by name",
    "Fluid by Name",
    "Fluid By name",
    "Fluid By Name",
    "fluidstack by name",
    "fluidstack by Name",
    "fluidstack By name",
    "fluidstack By Name",
    "Fluidstack by name",
    "Fluidstack by Name",
    "Fluidstack By name",
    "Fluidstack By Name",
    "fluidStack by name",
    "fluidStack by Name",
    "fluidStack By name",
    "fluidStack By Name",
    "FluidStack by name",
    "FluidStack by Name",
    "FluidStack By name",
    "FluidStack By Name",
  ];
  static override kind = "fluidstack" as const;
  static override renderPattern = "PREFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "String",
          },
          to: {
            type: "Fluid",
          },
        },
        normalizeSignature
      ),
      function: (name: iString): Fluid => {
        const fluidRegistry = RegistryHub.fluidRegistry;
        const key = name.valueOf().toLowerCase();
        const FluidConstructor =
          fluidRegistry.items[key as keyof typeof fluidRegistry.items];
        if (!FluidConstructor) return new Fluid(new Properties({}));
        return new FluidConstructor();
      },
    });
  }
}
