import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Integer } from "lib/JavaNumberClasses/Integer";
import { Item } from "lib/IntegratedDynamicsClasses/Item";

export class OPERATOR_OBJECT_ITEMSTACK_INVENTORYSIZE extends BaseOperator<
  Item,
  Integer
> {
  static override internalName =
    "integrateddynamics:itemstack_inventorysize" as const;
  static override numericID = 135;
  static override nicknames = [
    "inventorysize",
    "inventorySize",
    "itemInventorySize",
    "itemstackInventorysize",
    "itemstackInventorySize",
    "ItemstackInventorysize",
    "inventory_size",
    "item_inventory_size",
    "itemstack_inventory_size",
    "itemstack_inventorysize",
  ];
  static override symbol = "inventory_size";
  static override interactName = "itemstackInventorySize";
  static override operatorName = "inventorysize" as const;
  static override displayName = "Item Inventory Size" as const;
  static override fullDisplayName = "Item Item Inventory Size" as const;
  static override stringDisplayNames = [
    "item item inventory size",
    "item item inventory Size",
    "item item Inventory size",
    "item item Inventory Size",
    "item Item inventory size",
    "item Item inventory Size",
    "item Item Inventory size",
    "item Item Inventory Size",
    "Item item inventory size",
    "Item item inventory Size",
    "Item item Inventory size",
    "Item item Inventory Size",
    "Item Item inventory size",
    "Item Item inventory Size",
    "Item Item Inventory size",
    "Item Item Inventory Size",
    "item itemstack inventory size",
    "item itemstack inventory Size",
    "item itemstack Inventory size",
    "item itemstack Inventory Size",
    "item Itemstack inventory size",
    "item Itemstack inventory Size",
    "item Itemstack Inventory size",
    "item Itemstack Inventory Size",
    "item itemStack inventory size",
    "item itemStack inventory Size",
    "item itemStack Inventory size",
    "item itemStack Inventory Size",
    "item ItemStack inventory size",
    "item ItemStack inventory Size",
    "item ItemStack Inventory size",
    "item ItemStack Inventory Size",
    "Item itemstack inventory size",
    "Item itemstack inventory Size",
    "Item itemstack Inventory size",
    "Item itemstack Inventory Size",
    "Item Itemstack inventory size",
    "Item Itemstack inventory Size",
    "Item Itemstack Inventory size",
    "Item Itemstack Inventory Size",
    "Item itemStack inventory size",
    "Item itemStack inventory Size",
    "Item itemStack Inventory size",
    "Item itemStack Inventory Size",
    "Item ItemStack inventory size",
    "Item ItemStack inventory Size",
    "Item ItemStack Inventory size",
    "Item ItemStack Inventory Size",
    "itemstack item inventory size",
    "itemstack item inventory Size",
    "itemstack item Inventory size",
    "itemstack item Inventory Size",
    "itemstack Item inventory size",
    "itemstack Item inventory Size",
    "itemstack Item Inventory size",
    "itemstack Item Inventory Size",
    "Itemstack item inventory size",
    "Itemstack item inventory Size",
    "Itemstack item Inventory size",
    "Itemstack item Inventory Size",
    "Itemstack Item inventory size",
    "Itemstack Item inventory Size",
    "Itemstack Item Inventory size",
    "Itemstack Item Inventory Size",
    "itemStack item inventory size",
    "itemStack item inventory Size",
    "itemStack item Inventory size",
    "itemStack item Inventory Size",
    "itemStack Item inventory size",
    "itemStack Item inventory Size",
    "itemStack Item Inventory size",
    "itemStack Item Inventory Size",
    "ItemStack item inventory size",
    "ItemStack item inventory Size",
    "ItemStack item Inventory size",
    "ItemStack item Inventory Size",
    "ItemStack Item inventory size",
    "ItemStack Item inventory Size",
    "ItemStack Item Inventory size",
    "ItemStack Item Inventory Size",
    "itemstack itemstack inventory size",
    "itemstack itemstack inventory Size",
    "itemstack itemstack Inventory size",
    "itemstack itemstack Inventory Size",
    "itemstack Itemstack inventory size",
    "itemstack Itemstack inventory Size",
    "itemstack Itemstack Inventory size",
    "itemstack Itemstack Inventory Size",
    "itemstack itemStack inventory size",
    "itemstack itemStack inventory Size",
    "itemstack itemStack Inventory size",
    "itemstack itemStack Inventory Size",
    "itemstack ItemStack inventory size",
    "itemstack ItemStack inventory Size",
    "itemstack ItemStack Inventory size",
    "itemstack ItemStack Inventory Size",
    "Itemstack itemstack inventory size",
    "Itemstack itemstack inventory Size",
    "Itemstack itemstack Inventory size",
    "Itemstack itemstack Inventory Size",
    "Itemstack Itemstack inventory size",
    "Itemstack Itemstack inventory Size",
    "Itemstack Itemstack Inventory size",
    "Itemstack Itemstack Inventory Size",
    "Itemstack itemStack inventory size",
    "Itemstack itemStack inventory Size",
    "Itemstack itemStack Inventory size",
    "Itemstack itemStack Inventory Size",
    "Itemstack ItemStack inventory size",
    "Itemstack ItemStack inventory Size",
    "Itemstack ItemStack Inventory size",
    "Itemstack ItemStack Inventory Size",
    "itemStack itemstack inventory size",
    "itemStack itemstack inventory Size",
    "itemStack itemstack Inventory size",
    "itemStack itemstack Inventory Size",
    "itemStack Itemstack inventory size",
    "itemStack Itemstack inventory Size",
    "itemStack Itemstack Inventory size",
    "itemStack Itemstack Inventory Size",
    "itemStack itemStack inventory size",
    "itemStack itemStack inventory Size",
    "itemStack itemStack Inventory size",
    "itemStack itemStack Inventory Size",
    "itemStack ItemStack inventory size",
    "itemStack ItemStack inventory Size",
    "itemStack ItemStack Inventory size",
    "itemStack ItemStack Inventory Size",
    "ItemStack itemstack inventory size",
    "ItemStack itemstack inventory Size",
    "ItemStack itemstack Inventory size",
    "ItemStack itemstack Inventory Size",
    "ItemStack Itemstack inventory size",
    "ItemStack Itemstack inventory Size",
    "ItemStack Itemstack Inventory size",
    "ItemStack Itemstack Inventory Size",
    "ItemStack itemStack inventory size",
    "ItemStack itemStack inventory Size",
    "ItemStack itemStack Inventory size",
    "ItemStack itemStack Inventory Size",
    "ItemStack ItemStack inventory size",
    "ItemStack ItemStack inventory Size",
    "ItemStack ItemStack Inventory size",
    "ItemStack ItemStack Inventory Size",
    "item inventory size",
    "item inventory Size",
    "item Inventory size",
    "item Inventory Size",
    "Item inventory size",
    "Item inventory Size",
    "Item Inventory size",
    "Item Inventory Size",
    "itemstack inventory size",
    "itemstack inventory Size",
    "itemstack Inventory size",
    "itemstack Inventory Size",
    "Itemstack inventory size",
    "Itemstack inventory Size",
    "Itemstack Inventory size",
    "Itemstack Inventory Size",
    "itemStack inventory size",
    "itemStack inventory Size",
    "itemStack Inventory size",
    "itemStack Inventory Size",
    "ItemStack inventory size",
    "ItemStack inventory Size",
    "ItemStack Inventory size",
    "ItemStack Inventory Size",
  ];
  static override tooltipInfo =
    "Retrieve the inventory size of the given item handler contents" as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Integer",
          },
        },
        normalizeSignature
      ),
      function: (item: Item): Integer => {
        return item.getInventorySize();
      },
    });
  }
}
