import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { NullTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/NullTag";

export class OPERATOR_OBJECT_FLUIDSTACK_DATA_VALUE extends BaseOperator<
  Fluid,
  Operator<iString, Tag<IntegratedValue>>
> {
  static override internalName =
    "integrateddynamics:fluidstack_datavalue" as const;
  static override numericID = 285;
  static override nicknames = [
    "fluidDataValue",
    "fluidNBTValue",
    "fluidstackDatavalue",
    "fluidstackDataValue",
    "fluidStackDataValue",
    "FluidstackDataValue",
    "fluidstackFluidstackDatavalue",
    "fluidStackNBTValue",
    "fluid_data_value",
    "fluid_n_b_t_value",
    "fluid_NBT_value",
    "fluid_stack_data_value",
    "fluid_stack_n_b_t_value",
    "fluid_stack_NBT_value",
    "fluidstack_data_value",
    "fluidstack_datavalue",
    "fluidstack_NBT_value",
    "fluidstackFluidstack_datavalue",
  ];
  static override symbol = "data_value";
  static override interactName = "fluidstackDataValue";
  static override operatorName = "fluidstack_datavalue" as const;
  static override displayName = "Fluid Data Value" as const;
  static override fullDisplayName = "Fluid Fluid Data Value" as const;
  static override stringDisplayNames = [
    "fluid fluid data value",
    "fluid fluid data Value",
    "fluid fluid Data value",
    "fluid fluid Data Value",
    "fluid Fluid data value",
    "fluid Fluid data Value",
    "fluid Fluid Data value",
    "fluid Fluid Data Value",
    "Fluid fluid data value",
    "Fluid fluid data Value",
    "Fluid fluid Data value",
    "Fluid fluid Data Value",
    "Fluid Fluid data value",
    "Fluid Fluid data Value",
    "Fluid Fluid Data value",
    "Fluid Fluid Data Value",
    "fluid fluidstack data value",
    "fluid fluidstack data Value",
    "fluid fluidstack Data value",
    "fluid fluidstack Data Value",
    "fluid Fluidstack data value",
    "fluid Fluidstack data Value",
    "fluid Fluidstack Data value",
    "fluid Fluidstack Data Value",
    "fluid fluidStack data value",
    "fluid fluidStack data Value",
    "fluid fluidStack Data value",
    "fluid fluidStack Data Value",
    "fluid FluidStack data value",
    "fluid FluidStack data Value",
    "fluid FluidStack Data value",
    "fluid FluidStack Data Value",
    "Fluid fluidstack data value",
    "Fluid fluidstack data Value",
    "Fluid fluidstack Data value",
    "Fluid fluidstack Data Value",
    "Fluid Fluidstack data value",
    "Fluid Fluidstack data Value",
    "Fluid Fluidstack Data value",
    "Fluid Fluidstack Data Value",
    "Fluid fluidStack data value",
    "Fluid fluidStack data Value",
    "Fluid fluidStack Data value",
    "Fluid fluidStack Data Value",
    "Fluid FluidStack data value",
    "Fluid FluidStack data Value",
    "Fluid FluidStack Data value",
    "Fluid FluidStack Data Value",
    "fluidstack fluid data value",
    "fluidstack fluid data Value",
    "fluidstack fluid Data value",
    "fluidstack fluid Data Value",
    "fluidstack Fluid data value",
    "fluidstack Fluid data Value",
    "fluidstack Fluid Data value",
    "fluidstack Fluid Data Value",
    "Fluidstack fluid data value",
    "Fluidstack fluid data Value",
    "Fluidstack fluid Data value",
    "Fluidstack fluid Data Value",
    "Fluidstack Fluid data value",
    "Fluidstack Fluid data Value",
    "Fluidstack Fluid Data value",
    "Fluidstack Fluid Data Value",
    "fluidStack fluid data value",
    "fluidStack fluid data Value",
    "fluidStack fluid Data value",
    "fluidStack fluid Data Value",
    "fluidStack Fluid data value",
    "fluidStack Fluid data Value",
    "fluidStack Fluid Data value",
    "fluidStack Fluid Data Value",
    "FluidStack fluid data value",
    "FluidStack fluid data Value",
    "FluidStack fluid Data value",
    "FluidStack fluid Data Value",
    "FluidStack Fluid data value",
    "FluidStack Fluid data Value",
    "FluidStack Fluid Data value",
    "FluidStack Fluid Data Value",
    "fluidstack fluidstack data value",
    "fluidstack fluidstack data Value",
    "fluidstack fluidstack Data value",
    "fluidstack fluidstack Data Value",
    "fluidstack Fluidstack data value",
    "fluidstack Fluidstack data Value",
    "fluidstack Fluidstack Data value",
    "fluidstack Fluidstack Data Value",
    "fluidstack fluidStack data value",
    "fluidstack fluidStack data Value",
    "fluidstack fluidStack Data value",
    "fluidstack fluidStack Data Value",
    "fluidstack FluidStack data value",
    "fluidstack FluidStack data Value",
    "fluidstack FluidStack Data value",
    "fluidstack FluidStack Data Value",
    "Fluidstack fluidstack data value",
    "Fluidstack fluidstack data Value",
    "Fluidstack fluidstack Data value",
    "Fluidstack fluidstack Data Value",
    "Fluidstack Fluidstack data value",
    "Fluidstack Fluidstack data Value",
    "Fluidstack Fluidstack Data value",
    "Fluidstack Fluidstack Data Value",
    "Fluidstack fluidStack data value",
    "Fluidstack fluidStack data Value",
    "Fluidstack fluidStack Data value",
    "Fluidstack fluidStack Data Value",
    "Fluidstack FluidStack data value",
    "Fluidstack FluidStack data Value",
    "Fluidstack FluidStack Data value",
    "Fluidstack FluidStack Data Value",
    "fluidStack fluidstack data value",
    "fluidStack fluidstack data Value",
    "fluidStack fluidstack Data value",
    "fluidStack fluidstack Data Value",
    "fluidStack Fluidstack data value",
    "fluidStack Fluidstack data Value",
    "fluidStack Fluidstack Data value",
    "fluidStack Fluidstack Data Value",
    "fluidStack fluidStack data value",
    "fluidStack fluidStack data Value",
    "fluidStack fluidStack Data value",
    "fluidStack fluidStack Data Value",
    "fluidStack FluidStack data value",
    "fluidStack FluidStack data Value",
    "fluidStack FluidStack Data value",
    "fluidStack FluidStack Data Value",
    "FluidStack fluidstack data value",
    "FluidStack fluidstack data Value",
    "FluidStack fluidstack Data value",
    "FluidStack fluidstack Data Value",
    "FluidStack Fluidstack data value",
    "FluidStack Fluidstack data Value",
    "FluidStack Fluidstack Data value",
    "FluidStack Fluidstack Data Value",
    "FluidStack fluidStack data value",
    "FluidStack fluidStack data Value",
    "FluidStack fluidStack Data value",
    "FluidStack fluidStack Data Value",
    "FluidStack FluidStack data value",
    "FluidStack FluidStack data Value",
    "FluidStack FluidStack Data value",
    "FluidStack FluidStack Data Value",
    "fluid data value",
    "fluid data Value",
    "fluid Data value",
    "fluid Data Value",
    "Fluid data value",
    "Fluid data Value",
    "Fluid Data value",
    "Fluid Data Value",
    "fluidstack data value",
    "fluidstack data Value",
    "fluidstack Data value",
    "fluidstack Data Value",
    "Fluidstack data value",
    "Fluidstack data Value",
    "Fluidstack Data value",
    "Fluidstack Data Value",
    "fluidStack data value",
    "fluidStack data Value",
    "fluidStack Data value",
    "fluidStack Data Value",
    "FluidStack data value",
    "FluidStack data Value",
    "FluidStack Data value",
    "FluidStack Data Value",
  ];
  static override kind = "fluidstack" as const;
  static override renderPattern = "INFIX_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: {
            type: "Function",
            from: {
              type: "String",
            },
            to: {
              type: "NBT",
            },
          },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): TypeLambda<iString, Tag<IntegratedValue>> => {
        return (key: iString): Tag<IntegratedValue> => {
          const nbt = fluid.getNBT();
          if (!(nbt instanceof CompoundTag) || !nbt.has(key)) {
            return new NullTag();
          }
          return nbt.get(key);
        };
      },
    });
  }
}
