import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Item } from "lib/IntegratedDynamicsClasses/Item";

export class OPERATOR_OBJECT_ITEMSTACK_PLANTTYPE extends BaseOperator<
  Item,
  iString
> {
  static override internalName =
    "integrateddynamics:itemstack_plant_type" as const;
  static override numericID = 125;
  static override nicknames = [
    "itemPlantType",
    "itemstackPlantType",
    "itemstackPlanttype",
    "item_plant_type",
    "itemstack_planttype",
    "itemstack_plant_type",
  ];
  static override symbol = "plant_type";
  static override interactName = "plantType";
  static override operatorName = "planttype" as const;
  static override displayName = "Item Plant Type" as const;
  static override fullDisplayName = "Item Item Plant Type" as const;
  static override stringDisplayNames = [
    "item item plant type",
    "item item plant Type",
    "item item Plant type",
    "item item Plant Type",
    "item Item plant type",
    "item Item plant Type",
    "item Item Plant type",
    "item Item Plant Type",
    "Item item plant type",
    "Item item plant Type",
    "Item item Plant type",
    "Item item Plant Type",
    "Item Item plant type",
    "Item Item plant Type",
    "Item Item Plant type",
    "Item Item Plant Type",
    "item itemstack plant type",
    "item itemstack plant Type",
    "item itemstack Plant type",
    "item itemstack Plant Type",
    "item Itemstack plant type",
    "item Itemstack plant Type",
    "item Itemstack Plant type",
    "item Itemstack Plant Type",
    "item itemStack plant type",
    "item itemStack plant Type",
    "item itemStack Plant type",
    "item itemStack Plant Type",
    "item ItemStack plant type",
    "item ItemStack plant Type",
    "item ItemStack Plant type",
    "item ItemStack Plant Type",
    "Item itemstack plant type",
    "Item itemstack plant Type",
    "Item itemstack Plant type",
    "Item itemstack Plant Type",
    "Item Itemstack plant type",
    "Item Itemstack plant Type",
    "Item Itemstack Plant type",
    "Item Itemstack Plant Type",
    "Item itemStack plant type",
    "Item itemStack plant Type",
    "Item itemStack Plant type",
    "Item itemStack Plant Type",
    "Item ItemStack plant type",
    "Item ItemStack plant Type",
    "Item ItemStack Plant type",
    "Item ItemStack Plant Type",
    "itemstack item plant type",
    "itemstack item plant Type",
    "itemstack item Plant type",
    "itemstack item Plant Type",
    "itemstack Item plant type",
    "itemstack Item plant Type",
    "itemstack Item Plant type",
    "itemstack Item Plant Type",
    "Itemstack item plant type",
    "Itemstack item plant Type",
    "Itemstack item Plant type",
    "Itemstack item Plant Type",
    "Itemstack Item plant type",
    "Itemstack Item plant Type",
    "Itemstack Item Plant type",
    "Itemstack Item Plant Type",
    "itemStack item plant type",
    "itemStack item plant Type",
    "itemStack item Plant type",
    "itemStack item Plant Type",
    "itemStack Item plant type",
    "itemStack Item plant Type",
    "itemStack Item Plant type",
    "itemStack Item Plant Type",
    "ItemStack item plant type",
    "ItemStack item plant Type",
    "ItemStack item Plant type",
    "ItemStack item Plant Type",
    "ItemStack Item plant type",
    "ItemStack Item plant Type",
    "ItemStack Item Plant type",
    "ItemStack Item Plant Type",
    "itemstack itemstack plant type",
    "itemstack itemstack plant Type",
    "itemstack itemstack Plant type",
    "itemstack itemstack Plant Type",
    "itemstack Itemstack plant type",
    "itemstack Itemstack plant Type",
    "itemstack Itemstack Plant type",
    "itemstack Itemstack Plant Type",
    "itemstack itemStack plant type",
    "itemstack itemStack plant Type",
    "itemstack itemStack Plant type",
    "itemstack itemStack Plant Type",
    "itemstack ItemStack plant type",
    "itemstack ItemStack plant Type",
    "itemstack ItemStack Plant type",
    "itemstack ItemStack Plant Type",
    "Itemstack itemstack plant type",
    "Itemstack itemstack plant Type",
    "Itemstack itemstack Plant type",
    "Itemstack itemstack Plant Type",
    "Itemstack Itemstack plant type",
    "Itemstack Itemstack plant Type",
    "Itemstack Itemstack Plant type",
    "Itemstack Itemstack Plant Type",
    "Itemstack itemStack plant type",
    "Itemstack itemStack plant Type",
    "Itemstack itemStack Plant type",
    "Itemstack itemStack Plant Type",
    "Itemstack ItemStack plant type",
    "Itemstack ItemStack plant Type",
    "Itemstack ItemStack Plant type",
    "Itemstack ItemStack Plant Type",
    "itemStack itemstack plant type",
    "itemStack itemstack plant Type",
    "itemStack itemstack Plant type",
    "itemStack itemstack Plant Type",
    "itemStack Itemstack plant type",
    "itemStack Itemstack plant Type",
    "itemStack Itemstack Plant type",
    "itemStack Itemstack Plant Type",
    "itemStack itemStack plant type",
    "itemStack itemStack plant Type",
    "itemStack itemStack Plant type",
    "itemStack itemStack Plant Type",
    "itemStack ItemStack plant type",
    "itemStack ItemStack plant Type",
    "itemStack ItemStack Plant type",
    "itemStack ItemStack Plant Type",
    "ItemStack itemstack plant type",
    "ItemStack itemstack plant Type",
    "ItemStack itemstack Plant type",
    "ItemStack itemstack Plant Type",
    "ItemStack Itemstack plant type",
    "ItemStack Itemstack plant Type",
    "ItemStack Itemstack Plant type",
    "ItemStack Itemstack Plant Type",
    "ItemStack itemStack plant type",
    "ItemStack itemStack plant Type",
    "ItemStack itemStack Plant type",
    "ItemStack itemStack Plant Type",
    "ItemStack ItemStack plant type",
    "ItemStack ItemStack plant Type",
    "ItemStack ItemStack Plant type",
    "ItemStack ItemStack Plant Type",
    "item plant type",
    "item plant Type",
    "item Plant type",
    "item Plant Type",
    "Item plant type",
    "Item plant Type",
    "Item Plant type",
    "Item Plant Type",
    "itemstack plant type",
    "itemstack plant Type",
    "itemstack Plant type",
    "itemstack Plant Type",
    "Itemstack plant type",
    "Itemstack plant Type",
    "Itemstack Plant type",
    "Itemstack Plant Type",
    "itemStack plant type",
    "itemStack plant Type",
    "itemStack Plant type",
    "itemStack Plant Type",
    "ItemStack plant type",
    "ItemStack plant Type",
    "ItemStack Plant type",
    "ItemStack Plant Type",
  ];
  static override tooltipInfo = "The plant type of the given item" as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "String",
          },
        },
        normalizeSignature
      ),
      function: (item: Item): iString => {
        return item.getPlantType();
      },
    });
  }
}
