import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { Integer } from "lib/JavaNumberClasses/Integer";
import { Properties } from "lib/IntegratedDynamicsClasses/Properties";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";

export class OPERATOR_OBJECT_ITEMSTACK_WITHSIZE extends BaseOperator<
  Item,
  Operator<Integer, Item>
> {
  static override internalName =
    "integrateddynamics:itemstack_withsize" as const;
  static override numericID = 108;
  static override nicknames = [
    "itemstackWithsize",
    "itemstackWithSize",
    "ItemstackWithSize",
    "itemWithSize",
    "withsize",
    "item_with_size",
    "itemstack_with_size",
    "itemstack_withsize",
  ];
  static override symbol = "with_size";
  static override interactName = "itemstackWithSize";
  static override operatorName = "withsize" as const;
  static override displayName = "Item With Stacksize" as const;
  static override fullDisplayName = "Item Item With Stacksize" as const;
  static override stringDisplayNames = [
    "item item with stacksize",
    "item item with Stacksize",
    "item item With stacksize",
    "item item With Stacksize",
    "item Item with stacksize",
    "item Item with Stacksize",
    "item Item With stacksize",
    "item Item With Stacksize",
    "Item item with stacksize",
    "Item item with Stacksize",
    "Item item With stacksize",
    "Item item With Stacksize",
    "Item Item with stacksize",
    "Item Item with Stacksize",
    "Item Item With stacksize",
    "Item Item With Stacksize",
    "item itemstack with stacksize",
    "item itemstack with Stacksize",
    "item itemstack With stacksize",
    "item itemstack With Stacksize",
    "item Itemstack with stacksize",
    "item Itemstack with Stacksize",
    "item Itemstack With stacksize",
    "item Itemstack With Stacksize",
    "item itemStack with stacksize",
    "item itemStack with Stacksize",
    "item itemStack With stacksize",
    "item itemStack With Stacksize",
    "item ItemStack with stacksize",
    "item ItemStack with Stacksize",
    "item ItemStack With stacksize",
    "item ItemStack With Stacksize",
    "Item itemstack with stacksize",
    "Item itemstack with Stacksize",
    "Item itemstack With stacksize",
    "Item itemstack With Stacksize",
    "Item Itemstack with stacksize",
    "Item Itemstack with Stacksize",
    "Item Itemstack With stacksize",
    "Item Itemstack With Stacksize",
    "Item itemStack with stacksize",
    "Item itemStack with Stacksize",
    "Item itemStack With stacksize",
    "Item itemStack With Stacksize",
    "Item ItemStack with stacksize",
    "Item ItemStack with Stacksize",
    "Item ItemStack With stacksize",
    "Item ItemStack With Stacksize",
    "itemstack item with stacksize",
    "itemstack item with Stacksize",
    "itemstack item With stacksize",
    "itemstack item With Stacksize",
    "itemstack Item with stacksize",
    "itemstack Item with Stacksize",
    "itemstack Item With stacksize",
    "itemstack Item With Stacksize",
    "Itemstack item with stacksize",
    "Itemstack item with Stacksize",
    "Itemstack item With stacksize",
    "Itemstack item With Stacksize",
    "Itemstack Item with stacksize",
    "Itemstack Item with Stacksize",
    "Itemstack Item With stacksize",
    "Itemstack Item With Stacksize",
    "itemStack item with stacksize",
    "itemStack item with Stacksize",
    "itemStack item With stacksize",
    "itemStack item With Stacksize",
    "itemStack Item with stacksize",
    "itemStack Item with Stacksize",
    "itemStack Item With stacksize",
    "itemStack Item With Stacksize",
    "ItemStack item with stacksize",
    "ItemStack item with Stacksize",
    "ItemStack item With stacksize",
    "ItemStack item With Stacksize",
    "ItemStack Item with stacksize",
    "ItemStack Item with Stacksize",
    "ItemStack Item With stacksize",
    "ItemStack Item With Stacksize",
    "itemstack itemstack with stacksize",
    "itemstack itemstack with Stacksize",
    "itemstack itemstack With stacksize",
    "itemstack itemstack With Stacksize",
    "itemstack Itemstack with stacksize",
    "itemstack Itemstack with Stacksize",
    "itemstack Itemstack With stacksize",
    "itemstack Itemstack With Stacksize",
    "itemstack itemStack with stacksize",
    "itemstack itemStack with Stacksize",
    "itemstack itemStack With stacksize",
    "itemstack itemStack With Stacksize",
    "itemstack ItemStack with stacksize",
    "itemstack ItemStack with Stacksize",
    "itemstack ItemStack With stacksize",
    "itemstack ItemStack With Stacksize",
    "Itemstack itemstack with stacksize",
    "Itemstack itemstack with Stacksize",
    "Itemstack itemstack With stacksize",
    "Itemstack itemstack With Stacksize",
    "Itemstack Itemstack with stacksize",
    "Itemstack Itemstack with Stacksize",
    "Itemstack Itemstack With stacksize",
    "Itemstack Itemstack With Stacksize",
    "Itemstack itemStack with stacksize",
    "Itemstack itemStack with Stacksize",
    "Itemstack itemStack With stacksize",
    "Itemstack itemStack With Stacksize",
    "Itemstack ItemStack with stacksize",
    "Itemstack ItemStack with Stacksize",
    "Itemstack ItemStack With stacksize",
    "Itemstack ItemStack With Stacksize",
    "itemStack itemstack with stacksize",
    "itemStack itemstack with Stacksize",
    "itemStack itemstack With stacksize",
    "itemStack itemstack With Stacksize",
    "itemStack Itemstack with stacksize",
    "itemStack Itemstack with Stacksize",
    "itemStack Itemstack With stacksize",
    "itemStack Itemstack With Stacksize",
    "itemStack itemStack with stacksize",
    "itemStack itemStack with Stacksize",
    "itemStack itemStack With stacksize",
    "itemStack itemStack With Stacksize",
    "itemStack ItemStack with stacksize",
    "itemStack ItemStack with Stacksize",
    "itemStack ItemStack With stacksize",
    "itemStack ItemStack With Stacksize",
    "ItemStack itemstack with stacksize",
    "ItemStack itemstack with Stacksize",
    "ItemStack itemstack With stacksize",
    "ItemStack itemstack With Stacksize",
    "ItemStack Itemstack with stacksize",
    "ItemStack Itemstack with Stacksize",
    "ItemStack Itemstack With stacksize",
    "ItemStack Itemstack With Stacksize",
    "ItemStack itemStack with stacksize",
    "ItemStack itemStack with Stacksize",
    "ItemStack itemStack With stacksize",
    "ItemStack itemStack With Stacksize",
    "ItemStack ItemStack with stacksize",
    "ItemStack ItemStack with Stacksize",
    "ItemStack ItemStack With stacksize",
    "ItemStack ItemStack With Stacksize",
    "item with stacksize",
    "item with Stacksize",
    "item With stacksize",
    "item With Stacksize",
    "Item with stacksize",
    "Item with Stacksize",
    "Item With stacksize",
    "Item With Stacksize",
    "itemstack with stacksize",
    "itemstack with Stacksize",
    "itemstack With stacksize",
    "itemstack With Stacksize",
    "Itemstack with stacksize",
    "Itemstack with Stacksize",
    "Itemstack With stacksize",
    "Itemstack With Stacksize",
    "itemStack with stacksize",
    "itemStack with Stacksize",
    "itemStack With stacksize",
    "itemStack With Stacksize",
    "ItemStack with stacksize",
    "ItemStack with Stacksize",
    "ItemStack With stacksize",
    "ItemStack With Stacksize",
  ];
  static override tooltipInfo = "Set the stacksize for the given item" as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "INFIX" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Function",
            from: {
              type: "Integer",
            },
            to: {
              type: "Item",
            },
          },
        },
        normalizeSignature
      ),
      function: (item: Item): TypeLambda<Integer, Item> => {
        return (size: Integer): Item => {
          return new Item(new Properties({ size }), item);
        };
      },
    });
  }
}
