import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";
import { iBoolean } from "lib/IntegratedDynamicsClasses/typeWrappers/iBoolean";

export class OPERATOR_OBJECT_ITEMSTACK_ISITEMEQUALNODATA extends BaseOperator<
  Item,
  Operator<Item, iBoolean>
> {
  static override internalName =
    "integrateddynamics:itemstack_isitemequalnodata" as const;
  static override numericID = 282;
  static override nicknames = [
    "isitemequalnonbt",
    "isItemEqualNonNbt",
    "isItemEqualNonNBT",
    "isEqualNoNBT",
    "itemstackIsItemequalnodata",
    "ItemstackIsitemequalnodata",
    "itemstackIsitemequalnonbt",
    "itemstackIsEqualNonNbt",
    "itemstack_is_itemequalnodata",
    "itemstack_isitemequalnodata",
    "itemstack_isitemequalnonbt",
    "is_item_equal_no_nbt",
    "is_equal_no_nbt",
  ];
  static override symbol = "=NoNBT=";
  static override interactName = "itemstackIsEqualNonNbt";
  static override operatorName = "isitemequalnonnbt" as const;
  static override displayName = "Raw item equals no NBT" as const;
  static override fullDisplayName = "Item Raw item equals no NBT" as const;
  static override stringDisplayNames = [
    "item raw item equals no nbt",
    "item raw item equals no Nbt",
    "item raw item equals No nbt",
    "item raw item equals No Nbt",
    "item raw item Equals no nbt",
    "item raw item Equals no Nbt",
    "item raw item Equals No nbt",
    "item raw item Equals No Nbt",
    "item raw Item equals no nbt",
    "item raw Item equals no Nbt",
    "item raw Item equals No nbt",
    "item raw Item equals No Nbt",
    "item raw Item Equals no nbt",
    "item raw Item Equals no Nbt",
    "item raw Item Equals No nbt",
    "item raw Item Equals No Nbt",
    "item Raw item equals no nbt",
    "item Raw item equals no Nbt",
    "item Raw item equals No nbt",
    "item Raw item equals No Nbt",
    "item Raw item Equals no nbt",
    "item Raw item Equals no Nbt",
    "item Raw item Equals No nbt",
    "item Raw item Equals No Nbt",
    "item Raw Item equals no nbt",
    "item Raw Item equals no Nbt",
    "item Raw Item equals No nbt",
    "item Raw Item equals No Nbt",
    "item Raw Item Equals no nbt",
    "item Raw Item Equals no Nbt",
    "item Raw Item Equals No nbt",
    "item Raw Item Equals No Nbt",
    "Item raw item equals no nbt",
    "Item raw item equals no Nbt",
    "Item raw item equals No nbt",
    "Item raw item equals No Nbt",
    "Item raw item Equals no nbt",
    "Item raw item Equals no Nbt",
    "Item raw item Equals No nbt",
    "Item raw item Equals No Nbt",
    "Item raw Item equals no nbt",
    "Item raw Item equals no Nbt",
    "Item raw Item equals No nbt",
    "Item raw Item equals No Nbt",
    "Item raw Item Equals no nbt",
    "Item raw Item Equals no Nbt",
    "Item raw Item Equals No nbt",
    "Item raw Item Equals No Nbt",
    "Item Raw item equals no nbt",
    "Item Raw item equals no Nbt",
    "Item Raw item equals No nbt",
    "Item Raw item equals No Nbt",
    "Item Raw item Equals no nbt",
    "Item Raw item Equals no Nbt",
    "Item Raw item Equals No nbt",
    "Item Raw item Equals No Nbt",
    "Item Raw Item equals no nbt",
    "Item Raw Item equals no Nbt",
    "Item Raw Item equals No nbt",
    "Item Raw Item equals No Nbt",
    "Item Raw Item Equals no nbt",
    "Item Raw Item Equals no Nbt",
    "Item Raw Item Equals No nbt",
    "Item Raw Item Equals No Nbt",
    "item raw item equals no NBT",
    "item raw item equals No NBT",
    "item raw item Equals no NBT",
    "item raw item Equals No NBT",
    "item raw Item equals no NBT",
    "item raw Item equals No NBT",
    "item raw Item Equals no NBT",
    "item raw Item Equals No NBT",
    "item Raw item equals no NBT",
    "item Raw item equals No NBT",
    "item Raw item Equals no NBT",
    "item Raw item Equals No NBT",
    "item Raw Item equals no NBT",
    "item Raw Item equals No NBT",
    "item Raw Item Equals no NBT",
    "item Raw Item Equals No NBT",
    "Item raw item equals no NBT",
    "Item raw item equals No NBT",
    "Item raw item Equals no NBT",
    "Item raw item Equals No NBT",
    "Item raw Item equals no NBT",
    "Item raw Item equals No NBT",
    "Item raw Item Equals no NBT",
    "Item raw Item Equals No NBT",
    "Item Raw item equals no NBT",
    "Item Raw item equals No NBT",
    "Item Raw item Equals no NBT",
    "Item Raw item Equals No NBT",
    "Item Raw Item equals no NBT",
    "Item Raw Item equals No NBT",
    "Item Raw Item Equals no NBT",
    "Item Raw Item Equals No NBT",
    "item raw itemstack equals no nbt",
    "item raw itemstack equals no Nbt",
    "item raw itemstack equals No nbt",
    "item raw itemstack equals No Nbt",
    "item raw itemstack Equals no nbt",
    "item raw itemstack Equals no Nbt",
    "item raw itemstack Equals No nbt",
    "item raw itemstack Equals No Nbt",
    "item raw Itemstack equals no nbt",
    "item raw Itemstack equals no Nbt",
    "item raw Itemstack equals No nbt",
    "item raw Itemstack equals No Nbt",
    "item raw Itemstack Equals no nbt",
    "item raw Itemstack Equals no Nbt",
    "item raw Itemstack Equals No nbt",
    "item raw Itemstack Equals No Nbt",
    "item raw itemStack equals no nbt",
    "item raw itemStack equals no Nbt",
    "item raw itemStack equals No nbt",
    "item raw itemStack equals No Nbt",
    "item raw itemStack Equals no nbt",
    "item raw itemStack Equals no Nbt",
    "item raw itemStack Equals No nbt",
    "item raw itemStack Equals No Nbt",
    "item raw ItemStack equals no nbt",
    "item raw ItemStack equals no Nbt",
    "item raw ItemStack equals No nbt",
    "item raw ItemStack equals No Nbt",
    "item raw ItemStack Equals no nbt",
    "item raw ItemStack Equals no Nbt",
    "item raw ItemStack Equals No nbt",
    "item raw ItemStack Equals No Nbt",
    "item Raw itemstack equals no nbt",
    "item Raw itemstack equals no Nbt",
    "item Raw itemstack equals No nbt",
    "item Raw itemstack equals No Nbt",
    "item Raw itemstack Equals no nbt",
    "item Raw itemstack Equals no Nbt",
    "item Raw itemstack Equals No nbt",
    "item Raw itemstack Equals No Nbt",
    "item Raw Itemstack equals no nbt",
    "item Raw Itemstack equals no Nbt",
    "item Raw Itemstack equals No nbt",
    "item Raw Itemstack equals No Nbt",
    "item Raw Itemstack Equals no nbt",
    "item Raw Itemstack Equals no Nbt",
    "item Raw Itemstack Equals No nbt",
    "item Raw Itemstack Equals No Nbt",
    "item Raw itemStack equals no nbt",
    "item Raw itemStack equals no Nbt",
    "item Raw itemStack equals No nbt",
    "item Raw itemStack equals No Nbt",
    "item Raw itemStack Equals no nbt",
    "item Raw itemStack Equals no Nbt",
    "item Raw itemStack Equals No nbt",
    "item Raw itemStack Equals No Nbt",
    "item Raw ItemStack equals no nbt",
    "item Raw ItemStack equals no Nbt",
    "item Raw ItemStack equals No nbt",
    "item Raw ItemStack equals No Nbt",
    "item Raw ItemStack Equals no nbt",
    "item Raw ItemStack Equals no Nbt",
    "item Raw ItemStack Equals No nbt",
    "item Raw ItemStack Equals No Nbt",
    "Item raw itemstack equals no nbt",
    "Item raw itemstack equals no Nbt",
    "Item raw itemstack equals No nbt",
    "Item raw itemstack equals No Nbt",
    "Item raw itemstack Equals no nbt",
    "Item raw itemstack Equals no Nbt",
    "Item raw itemstack Equals No nbt",
    "Item raw itemstack Equals No Nbt",
    "Item raw Itemstack equals no nbt",
    "Item raw Itemstack equals no Nbt",
    "Item raw Itemstack equals No nbt",
    "Item raw Itemstack equals No Nbt",
    "Item raw Itemstack Equals no nbt",
    "Item raw Itemstack Equals no Nbt",
    "Item raw Itemstack Equals No nbt",
    "Item raw Itemstack Equals No Nbt",
    "Item raw itemStack equals no nbt",
    "Item raw itemStack equals no Nbt",
    "Item raw itemStack equals No nbt",
    "Item raw itemStack equals No Nbt",
    "Item raw itemStack Equals no nbt",
    "Item raw itemStack Equals no Nbt",
    "Item raw itemStack Equals No nbt",
    "Item raw itemStack Equals No Nbt",
    "Item raw ItemStack equals no nbt",
    "Item raw ItemStack equals no Nbt",
    "Item raw ItemStack equals No nbt",
    "Item raw ItemStack equals No Nbt",
    "Item raw ItemStack Equals no nbt",
    "Item raw ItemStack Equals no Nbt",
    "Item raw ItemStack Equals No nbt",
    "Item raw ItemStack Equals No Nbt",
    "Item Raw itemstack equals no nbt",
    "Item Raw itemstack equals no Nbt",
    "Item Raw itemstack equals No nbt",
    "Item Raw itemstack equals No Nbt",
    "Item Raw itemstack Equals no nbt",
    "Item Raw itemstack Equals no Nbt",
    "Item Raw itemstack Equals No nbt",
    "Item Raw itemstack Equals No Nbt",
    "Item Raw Itemstack equals no nbt",
    "Item Raw Itemstack equals no Nbt",
    "Item Raw Itemstack equals No nbt",
    "Item Raw Itemstack equals No Nbt",
    "Item Raw Itemstack Equals no nbt",
    "Item Raw Itemstack Equals no Nbt",
    "Item Raw Itemstack Equals No nbt",
    "Item Raw Itemstack Equals No Nbt",
    "Item Raw itemStack equals no nbt",
    "Item Raw itemStack equals no Nbt",
    "Item Raw itemStack equals No nbt",
    "Item Raw itemStack equals No Nbt",
    "Item Raw itemStack Equals no nbt",
    "Item Raw itemStack Equals no Nbt",
    "Item Raw itemStack Equals No nbt",
    "Item Raw itemStack Equals No Nbt",
    "Item Raw ItemStack equals no nbt",
    "Item Raw ItemStack equals no Nbt",
    "Item Raw ItemStack equals No nbt",
    "Item Raw ItemStack equals No Nbt",
    "Item Raw ItemStack Equals no nbt",
    "Item Raw ItemStack Equals no Nbt",
    "Item Raw ItemStack Equals No nbt",
    "Item Raw ItemStack Equals No Nbt",
    "item raw itemstack equals no NBT",
    "item raw itemstack equals No NBT",
    "item raw itemstack Equals no NBT",
    "item raw itemstack Equals No NBT",
    "item raw Itemstack equals no NBT",
    "item raw Itemstack equals No NBT",
    "item raw Itemstack Equals no NBT",
    "item raw Itemstack Equals No NBT",
    "item raw itemStack equals no NBT",
    "item raw itemStack equals No NBT",
    "item raw itemStack Equals no NBT",
    "item raw itemStack Equals No NBT",
    "item raw ItemStack equals no NBT",
    "item raw ItemStack equals No NBT",
    "item raw ItemStack Equals no NBT",
    "item raw ItemStack Equals No NBT",
    "item Raw itemstack equals no NBT",
    "item Raw itemstack equals No NBT",
    "item Raw itemstack Equals no NBT",
    "item Raw itemstack Equals No NBT",
    "item Raw Itemstack equals no NBT",
    "item Raw Itemstack equals No NBT",
    "item Raw Itemstack Equals no NBT",
    "item Raw Itemstack Equals No NBT",
    "item Raw itemStack equals no NBT",
    "item Raw itemStack equals No NBT",
    "item Raw itemStack Equals no NBT",
    "item Raw itemStack Equals No NBT",
    "item Raw ItemStack equals no NBT",
    "item Raw ItemStack equals No NBT",
    "item Raw ItemStack Equals no NBT",
    "item Raw ItemStack Equals No NBT",
    "Item raw itemstack equals no NBT",
    "Item raw itemstack equals No NBT",
    "Item raw itemstack Equals no NBT",
    "Item raw itemstack Equals No NBT",
    "Item raw Itemstack equals no NBT",
    "Item raw Itemstack equals No NBT",
    "Item raw Itemstack Equals no NBT",
    "Item raw Itemstack Equals No NBT",
    "Item raw itemStack equals no NBT",
    "Item raw itemStack equals No NBT",
    "Item raw itemStack Equals no NBT",
    "Item raw itemStack Equals No NBT",
    "Item raw ItemStack equals no NBT",
    "Item raw ItemStack equals No NBT",
    "Item raw ItemStack Equals no NBT",
    "Item raw ItemStack Equals No NBT",
    "Item Raw itemstack equals no NBT",
    "Item Raw itemstack equals No NBT",
    "Item Raw itemstack Equals no NBT",
    "Item Raw itemstack Equals No NBT",
    "Item Raw Itemstack equals no NBT",
    "Item Raw Itemstack equals No NBT",
    "Item Raw Itemstack Equals no NBT",
    "Item Raw Itemstack Equals No NBT",
    "Item Raw itemStack equals no NBT",
    "Item Raw itemStack equals No NBT",
    "Item Raw itemStack Equals no NBT",
    "Item Raw itemStack Equals No NBT",
    "Item Raw ItemStack equals no NBT",
    "Item Raw ItemStack equals No NBT",
    "Item Raw ItemStack Equals no NBT",
    "Item Raw ItemStack Equals No NBT",
    "itemstack raw item equals no nbt",
    "itemstack raw item equals no Nbt",
    "itemstack raw item equals No nbt",
    "itemstack raw item equals No Nbt",
    "itemstack raw item Equals no nbt",
    "itemstack raw item Equals no Nbt",
    "itemstack raw item Equals No nbt",
    "itemstack raw item Equals No Nbt",
    "itemstack raw Item equals no nbt",
    "itemstack raw Item equals no Nbt",
    "itemstack raw Item equals No nbt",
    "itemstack raw Item equals No Nbt",
    "itemstack raw Item Equals no nbt",
    "itemstack raw Item Equals no Nbt",
    "itemstack raw Item Equals No nbt",
    "itemstack raw Item Equals No Nbt",
    "itemstack Raw item equals no nbt",
    "itemstack Raw item equals no Nbt",
    "itemstack Raw item equals No nbt",
    "itemstack Raw item equals No Nbt",
    "itemstack Raw item Equals no nbt",
    "itemstack Raw item Equals no Nbt",
    "itemstack Raw item Equals No nbt",
    "itemstack Raw item Equals No Nbt",
    "itemstack Raw Item equals no nbt",
    "itemstack Raw Item equals no Nbt",
    "itemstack Raw Item equals No nbt",
    "itemstack Raw Item equals No Nbt",
    "itemstack Raw Item Equals no nbt",
    "itemstack Raw Item Equals no Nbt",
    "itemstack Raw Item Equals No nbt",
    "itemstack Raw Item Equals No Nbt",
    "Itemstack raw item equals no nbt",
    "Itemstack raw item equals no Nbt",
    "Itemstack raw item equals No nbt",
    "Itemstack raw item equals No Nbt",
    "Itemstack raw item Equals no nbt",
    "Itemstack raw item Equals no Nbt",
    "Itemstack raw item Equals No nbt",
    "Itemstack raw item Equals No Nbt",
    "Itemstack raw Item equals no nbt",
    "Itemstack raw Item equals no Nbt",
    "Itemstack raw Item equals No nbt",
    "Itemstack raw Item equals No Nbt",
    "Itemstack raw Item Equals no nbt",
    "Itemstack raw Item Equals no Nbt",
    "Itemstack raw Item Equals No nbt",
    "Itemstack raw Item Equals No Nbt",
    "Itemstack Raw item equals no nbt",
    "Itemstack Raw item equals no Nbt",
    "Itemstack Raw item equals No nbt",
    "Itemstack Raw item equals No Nbt",
    "Itemstack Raw item Equals no nbt",
    "Itemstack Raw item Equals no Nbt",
    "Itemstack Raw item Equals No nbt",
    "Itemstack Raw item Equals No Nbt",
    "Itemstack Raw Item equals no nbt",
    "Itemstack Raw Item equals no Nbt",
    "Itemstack Raw Item equals No nbt",
    "Itemstack Raw Item equals No Nbt",
    "Itemstack Raw Item Equals no nbt",
    "Itemstack Raw Item Equals no Nbt",
    "Itemstack Raw Item Equals No nbt",
    "Itemstack Raw Item Equals No Nbt",
    "itemStack raw item equals no nbt",
    "itemStack raw item equals no Nbt",
    "itemStack raw item equals No nbt",
    "itemStack raw item equals No Nbt",
    "itemStack raw item Equals no nbt",
    "itemStack raw item Equals no Nbt",
    "itemStack raw item Equals No nbt",
    "itemStack raw item Equals No Nbt",
    "itemStack raw Item equals no nbt",
    "itemStack raw Item equals no Nbt",
    "itemStack raw Item equals No nbt",
    "itemStack raw Item equals No Nbt",
    "itemStack raw Item Equals no nbt",
    "itemStack raw Item Equals no Nbt",
    "itemStack raw Item Equals No nbt",
    "itemStack raw Item Equals No Nbt",
    "itemStack Raw item equals no nbt",
    "itemStack Raw item equals no Nbt",
    "itemStack Raw item equals No nbt",
    "itemStack Raw item equals No Nbt",
    "itemStack Raw item Equals no nbt",
    "itemStack Raw item Equals no Nbt",
    "itemStack Raw item Equals No nbt",
    "itemStack Raw item Equals No Nbt",
    "itemStack Raw Item equals no nbt",
    "itemStack Raw Item equals no Nbt",
    "itemStack Raw Item equals No nbt",
    "itemStack Raw Item equals No Nbt",
    "itemStack Raw Item Equals no nbt",
    "itemStack Raw Item Equals no Nbt",
    "itemStack Raw Item Equals No nbt",
    "itemStack Raw Item Equals No Nbt",
    "ItemStack raw item equals no nbt",
    "ItemStack raw item equals no Nbt",
    "ItemStack raw item equals No nbt",
    "ItemStack raw item equals No Nbt",
    "ItemStack raw item Equals no nbt",
    "ItemStack raw item Equals no Nbt",
    "ItemStack raw item Equals No nbt",
    "ItemStack raw item Equals No Nbt",
    "ItemStack raw Item equals no nbt",
    "ItemStack raw Item equals no Nbt",
    "ItemStack raw Item equals No nbt",
    "ItemStack raw Item equals No Nbt",
    "ItemStack raw Item Equals no nbt",
    "ItemStack raw Item Equals no Nbt",
    "ItemStack raw Item Equals No nbt",
    "ItemStack raw Item Equals No Nbt",
    "ItemStack Raw item equals no nbt",
    "ItemStack Raw item equals no Nbt",
    "ItemStack Raw item equals No nbt",
    "ItemStack Raw item equals No Nbt",
    "ItemStack Raw item Equals no nbt",
    "ItemStack Raw item Equals no Nbt",
    "ItemStack Raw item Equals No nbt",
    "ItemStack Raw item Equals No Nbt",
    "ItemStack Raw Item equals no nbt",
    "ItemStack Raw Item equals no Nbt",
    "ItemStack Raw Item equals No nbt",
    "ItemStack Raw Item equals No Nbt",
    "ItemStack Raw Item Equals no nbt",
    "ItemStack Raw Item Equals no Nbt",
    "ItemStack Raw Item Equals No nbt",
    "ItemStack Raw Item Equals No Nbt",
    "itemstack raw item equals no NBT",
    "itemstack raw item equals No NBT",
    "itemstack raw item Equals no NBT",
    "itemstack raw item Equals No NBT",
    "itemstack raw Item equals no NBT",
    "itemstack raw Item equals No NBT",
    "itemstack raw Item Equals no NBT",
    "itemstack raw Item Equals No NBT",
    "itemstack Raw item equals no NBT",
    "itemstack Raw item equals No NBT",
    "itemstack Raw item Equals no NBT",
    "itemstack Raw item Equals No NBT",
    "itemstack Raw Item equals no NBT",
    "itemstack Raw Item equals No NBT",
    "itemstack Raw Item Equals no NBT",
    "itemstack Raw Item Equals No NBT",
    "Itemstack raw item equals no NBT",
    "Itemstack raw item equals No NBT",
    "Itemstack raw item Equals no NBT",
    "Itemstack raw item Equals No NBT",
    "Itemstack raw Item equals no NBT",
    "Itemstack raw Item equals No NBT",
    "Itemstack raw Item Equals no NBT",
    "Itemstack raw Item Equals No NBT",
    "Itemstack Raw item equals no NBT",
    "Itemstack Raw item equals No NBT",
    "Itemstack Raw item Equals no NBT",
    "Itemstack Raw item Equals No NBT",
    "Itemstack Raw Item equals no NBT",
    "Itemstack Raw Item equals No NBT",
    "Itemstack Raw Item Equals no NBT",
    "Itemstack Raw Item Equals No NBT",
    "itemStack raw item equals no NBT",
    "itemStack raw item equals No NBT",
    "itemStack raw item Equals no NBT",
    "itemStack raw item Equals No NBT",
    "itemStack raw Item equals no NBT",
    "itemStack raw Item equals No NBT",
    "itemStack raw Item Equals no NBT",
    "itemStack raw Item Equals No NBT",
    "itemStack Raw item equals no NBT",
    "itemStack Raw item equals No NBT",
    "itemStack Raw item Equals no NBT",
    "itemStack Raw item Equals No NBT",
    "itemStack Raw Item equals no NBT",
    "itemStack Raw Item equals No NBT",
    "itemStack Raw Item Equals no NBT",
    "itemStack Raw Item Equals No NBT",
    "ItemStack raw item equals no NBT",
    "ItemStack raw item equals No NBT",
    "ItemStack raw item Equals no NBT",
    "ItemStack raw item Equals No NBT",
    "ItemStack raw Item equals no NBT",
    "ItemStack raw Item equals No NBT",
    "ItemStack raw Item Equals no NBT",
    "ItemStack raw Item Equals No NBT",
    "ItemStack Raw item equals no NBT",
    "ItemStack Raw item equals No NBT",
    "ItemStack Raw item Equals no NBT",
    "ItemStack Raw item Equals No NBT",
    "ItemStack Raw Item equals no NBT",
    "ItemStack Raw Item equals No NBT",
    "ItemStack Raw Item Equals no NBT",
    "ItemStack Raw Item Equals No NBT",
    "itemstack raw itemstack equals no nbt",
    "itemstack raw itemstack equals no Nbt",
    "itemstack raw itemstack equals No nbt",
    "itemstack raw itemstack equals No Nbt",
    "itemstack raw itemstack Equals no nbt",
    "itemstack raw itemstack Equals no Nbt",
    "itemstack raw itemstack Equals No nbt",
    "itemstack raw itemstack Equals No Nbt",
    "itemstack raw Itemstack equals no nbt",
    "itemstack raw Itemstack equals no Nbt",
    "itemstack raw Itemstack equals No nbt",
    "itemstack raw Itemstack equals No Nbt",
    "itemstack raw Itemstack Equals no nbt",
    "itemstack raw Itemstack Equals no Nbt",
    "itemstack raw Itemstack Equals No nbt",
    "itemstack raw Itemstack Equals No Nbt",
    "itemstack raw itemStack equals no nbt",
    "itemstack raw itemStack equals no Nbt",
    "itemstack raw itemStack equals No nbt",
    "itemstack raw itemStack equals No Nbt",
    "itemstack raw itemStack Equals no nbt",
    "itemstack raw itemStack Equals no Nbt",
    "itemstack raw itemStack Equals No nbt",
    "itemstack raw itemStack Equals No Nbt",
    "itemstack raw ItemStack equals no nbt",
    "itemstack raw ItemStack equals no Nbt",
    "itemstack raw ItemStack equals No nbt",
    "itemstack raw ItemStack equals No Nbt",
    "itemstack raw ItemStack Equals no nbt",
    "itemstack raw ItemStack Equals no Nbt",
    "itemstack raw ItemStack Equals No nbt",
    "itemstack raw ItemStack Equals No Nbt",
    "itemstack Raw itemstack equals no nbt",
    "itemstack Raw itemstack equals no Nbt",
    "itemstack Raw itemstack equals No nbt",
    "itemstack Raw itemstack equals No Nbt",
    "itemstack Raw itemstack Equals no nbt",
    "itemstack Raw itemstack Equals no Nbt",
    "itemstack Raw itemstack Equals No nbt",
    "itemstack Raw itemstack Equals No Nbt",
    "itemstack Raw Itemstack equals no nbt",
    "itemstack Raw Itemstack equals no Nbt",
    "itemstack Raw Itemstack equals No nbt",
    "itemstack Raw Itemstack equals No Nbt",
    "itemstack Raw Itemstack Equals no nbt",
    "itemstack Raw Itemstack Equals no Nbt",
    "itemstack Raw Itemstack Equals No nbt",
    "itemstack Raw Itemstack Equals No Nbt",
    "itemstack Raw itemStack equals no nbt",
    "itemstack Raw itemStack equals no Nbt",
    "itemstack Raw itemStack equals No nbt",
    "itemstack Raw itemStack equals No Nbt",
    "itemstack Raw itemStack Equals no nbt",
    "itemstack Raw itemStack Equals no Nbt",
    "itemstack Raw itemStack Equals No nbt",
    "itemstack Raw itemStack Equals No Nbt",
    "itemstack Raw ItemStack equals no nbt",
    "itemstack Raw ItemStack equals no Nbt",
    "itemstack Raw ItemStack equals No nbt",
    "itemstack Raw ItemStack equals No Nbt",
    "itemstack Raw ItemStack Equals no nbt",
    "itemstack Raw ItemStack Equals no Nbt",
    "itemstack Raw ItemStack Equals No nbt",
    "itemstack Raw ItemStack Equals No Nbt",
    "Itemstack raw itemstack equals no nbt",
    "Itemstack raw itemstack equals no Nbt",
    "Itemstack raw itemstack equals No nbt",
    "Itemstack raw itemstack equals No Nbt",
    "Itemstack raw itemstack Equals no nbt",
    "Itemstack raw itemstack Equals no Nbt",
    "Itemstack raw itemstack Equals No nbt",
    "Itemstack raw itemstack Equals No Nbt",
    "Itemstack raw Itemstack equals no nbt",
    "Itemstack raw Itemstack equals no Nbt",
    "Itemstack raw Itemstack equals No nbt",
    "Itemstack raw Itemstack equals No Nbt",
    "Itemstack raw Itemstack Equals no nbt",
    "Itemstack raw Itemstack Equals no Nbt",
    "Itemstack raw Itemstack Equals No nbt",
    "Itemstack raw Itemstack Equals No Nbt",
    "Itemstack raw itemStack equals no nbt",
    "Itemstack raw itemStack equals no Nbt",
    "Itemstack raw itemStack equals No nbt",
    "Itemstack raw itemStack equals No Nbt",
    "Itemstack raw itemStack Equals no nbt",
    "Itemstack raw itemStack Equals no Nbt",
    "Itemstack raw itemStack Equals No nbt",
    "Itemstack raw itemStack Equals No Nbt",
    "Itemstack raw ItemStack equals no nbt",
    "Itemstack raw ItemStack equals no Nbt",
    "Itemstack raw ItemStack equals No nbt",
    "Itemstack raw ItemStack equals No Nbt",
    "Itemstack raw ItemStack Equals no nbt",
    "Itemstack raw ItemStack Equals no Nbt",
    "Itemstack raw ItemStack Equals No nbt",
    "Itemstack raw ItemStack Equals No Nbt",
    "Itemstack Raw itemstack equals no nbt",
    "Itemstack Raw itemstack equals no Nbt",
    "Itemstack Raw itemstack equals No nbt",
    "Itemstack Raw itemstack equals No Nbt",
    "Itemstack Raw itemstack Equals no nbt",
    "Itemstack Raw itemstack Equals no Nbt",
    "Itemstack Raw itemstack Equals No nbt",
    "Itemstack Raw itemstack Equals No Nbt",
    "Itemstack Raw Itemstack equals no nbt",
    "Itemstack Raw Itemstack equals no Nbt",
    "Itemstack Raw Itemstack equals No nbt",
    "Itemstack Raw Itemstack equals No Nbt",
    "Itemstack Raw Itemstack Equals no nbt",
    "Itemstack Raw Itemstack Equals no Nbt",
    "Itemstack Raw Itemstack Equals No nbt",
    "Itemstack Raw Itemstack Equals No Nbt",
    "Itemstack Raw itemStack equals no nbt",
    "Itemstack Raw itemStack equals no Nbt",
    "Itemstack Raw itemStack equals No nbt",
    "Itemstack Raw itemStack equals No Nbt",
    "Itemstack Raw itemStack Equals no nbt",
    "Itemstack Raw itemStack Equals no Nbt",
    "Itemstack Raw itemStack Equals No nbt",
    "Itemstack Raw itemStack Equals No Nbt",
    "Itemstack Raw ItemStack equals no nbt",
    "Itemstack Raw ItemStack equals no Nbt",
    "Itemstack Raw ItemStack equals No nbt",
    "Itemstack Raw ItemStack equals No Nbt",
    "Itemstack Raw ItemStack Equals no nbt",
    "Itemstack Raw ItemStack Equals no Nbt",
    "Itemstack Raw ItemStack Equals No nbt",
    "Itemstack Raw ItemStack Equals No Nbt",
    "itemStack raw itemstack equals no nbt",
    "itemStack raw itemstack equals no Nbt",
    "itemStack raw itemstack equals No nbt",
    "itemStack raw itemstack equals No Nbt",
    "itemStack raw itemstack Equals no nbt",
    "itemStack raw itemstack Equals no Nbt",
    "itemStack raw itemstack Equals No nbt",
    "itemStack raw itemstack Equals No Nbt",
    "itemStack raw Itemstack equals no nbt",
    "itemStack raw Itemstack equals no Nbt",
    "itemStack raw Itemstack equals No nbt",
    "itemStack raw Itemstack equals No Nbt",
    "itemStack raw Itemstack Equals no nbt",
    "itemStack raw Itemstack Equals no Nbt",
    "itemStack raw Itemstack Equals No nbt",
    "itemStack raw Itemstack Equals No Nbt",
    "itemStack raw itemStack equals no nbt",
    "itemStack raw itemStack equals no Nbt",
    "itemStack raw itemStack equals No nbt",
    "itemStack raw itemStack equals No Nbt",
    "itemStack raw itemStack Equals no nbt",
    "itemStack raw itemStack Equals no Nbt",
    "itemStack raw itemStack Equals No nbt",
    "itemStack raw itemStack Equals No Nbt",
    "itemStack raw ItemStack equals no nbt",
    "itemStack raw ItemStack equals no Nbt",
    "itemStack raw ItemStack equals No nbt",
    "itemStack raw ItemStack equals No Nbt",
    "itemStack raw ItemStack Equals no nbt",
    "itemStack raw ItemStack Equals no Nbt",
    "itemStack raw ItemStack Equals No nbt",
    "itemStack raw ItemStack Equals No Nbt",
    "itemStack Raw itemstack equals no nbt",
    "itemStack Raw itemstack equals no Nbt",
    "itemStack Raw itemstack equals No nbt",
    "itemStack Raw itemstack equals No Nbt",
    "itemStack Raw itemstack Equals no nbt",
    "itemStack Raw itemstack Equals no Nbt",
    "itemStack Raw itemstack Equals No nbt",
    "itemStack Raw itemstack Equals No Nbt",
    "itemStack Raw Itemstack equals no nbt",
    "itemStack Raw Itemstack equals no Nbt",
    "itemStack Raw Itemstack equals No nbt",
    "itemStack Raw Itemstack equals No Nbt",
    "itemStack Raw Itemstack Equals no nbt",
    "itemStack Raw Itemstack Equals no Nbt",
    "itemStack Raw Itemstack Equals No nbt",
    "itemStack Raw Itemstack Equals No Nbt",
    "itemStack Raw itemStack equals no nbt",
    "itemStack Raw itemStack equals no Nbt",
    "itemStack Raw itemStack equals No nbt",
    "itemStack Raw itemStack equals No Nbt",
    "itemStack Raw itemStack Equals no nbt",
    "itemStack Raw itemStack Equals no Nbt",
    "itemStack Raw itemStack Equals No nbt",
    "itemStack Raw itemStack Equals No Nbt",
    "itemStack Raw ItemStack equals no nbt",
    "itemStack Raw ItemStack equals no Nbt",
    "itemStack Raw ItemStack equals No nbt",
    "itemStack Raw ItemStack equals No Nbt",
    "itemStack Raw ItemStack Equals no nbt",
    "itemStack Raw ItemStack Equals no Nbt",
    "itemStack Raw ItemStack Equals No nbt",
    "itemStack Raw ItemStack Equals No Nbt",
    "ItemStack raw itemstack equals no nbt",
    "ItemStack raw itemstack equals no Nbt",
    "ItemStack raw itemstack equals No nbt",
    "ItemStack raw itemstack equals No Nbt",
    "ItemStack raw itemstack Equals no nbt",
    "ItemStack raw itemstack Equals no Nbt",
    "ItemStack raw itemstack Equals No nbt",
    "ItemStack raw itemstack Equals No Nbt",
    "ItemStack raw Itemstack equals no nbt",
    "ItemStack raw Itemstack equals no Nbt",
    "ItemStack raw Itemstack equals No nbt",
    "ItemStack raw Itemstack equals No Nbt",
    "ItemStack raw Itemstack Equals no nbt",
    "ItemStack raw Itemstack Equals no Nbt",
    "ItemStack raw Itemstack Equals No nbt",
    "ItemStack raw Itemstack Equals No Nbt",
    "ItemStack raw itemStack equals no nbt",
    "ItemStack raw itemStack equals no Nbt",
    "ItemStack raw itemStack equals No nbt",
    "ItemStack raw itemStack equals No Nbt",
    "ItemStack raw itemStack Equals no nbt",
    "ItemStack raw itemStack Equals no Nbt",
    "ItemStack raw itemStack Equals No nbt",
    "ItemStack raw itemStack Equals No Nbt",
    "ItemStack raw ItemStack equals no nbt",
    "ItemStack raw ItemStack equals no Nbt",
    "ItemStack raw ItemStack equals No nbt",
    "ItemStack raw ItemStack equals No Nbt",
    "ItemStack raw ItemStack Equals no nbt",
    "ItemStack raw ItemStack Equals no Nbt",
    "ItemStack raw ItemStack Equals No nbt",
    "ItemStack raw ItemStack Equals No Nbt",
    "ItemStack Raw itemstack equals no nbt",
    "ItemStack Raw itemstack equals no Nbt",
    "ItemStack Raw itemstack equals No nbt",
    "ItemStack Raw itemstack equals No Nbt",
    "ItemStack Raw itemstack Equals no nbt",
    "ItemStack Raw itemstack Equals no Nbt",
    "ItemStack Raw itemstack Equals No nbt",
    "ItemStack Raw itemstack Equals No Nbt",
    "ItemStack Raw Itemstack equals no nbt",
    "ItemStack Raw Itemstack equals no Nbt",
    "ItemStack Raw Itemstack equals No nbt",
    "ItemStack Raw Itemstack equals No Nbt",
    "ItemStack Raw Itemstack Equals no nbt",
    "ItemStack Raw Itemstack Equals no Nbt",
    "ItemStack Raw Itemstack Equals No nbt",
    "ItemStack Raw Itemstack Equals No Nbt",
    "ItemStack Raw itemStack equals no nbt",
    "ItemStack Raw itemStack equals no Nbt",
    "ItemStack Raw itemStack equals No nbt",
    "ItemStack Raw itemStack equals No Nbt",
    "ItemStack Raw itemStack Equals no nbt",
    "ItemStack Raw itemStack Equals no Nbt",
    "ItemStack Raw itemStack Equals No nbt",
    "ItemStack Raw itemStack Equals No Nbt",
    "ItemStack Raw ItemStack equals no nbt",
    "ItemStack Raw ItemStack equals no Nbt",
    "ItemStack Raw ItemStack equals No nbt",
    "ItemStack Raw ItemStack equals No Nbt",
    "ItemStack Raw ItemStack Equals no nbt",
    "ItemStack Raw ItemStack Equals no Nbt",
    "ItemStack Raw ItemStack Equals No nbt",
    "ItemStack Raw ItemStack Equals No Nbt",
    "itemstack raw itemstack equals no NBT",
    "itemstack raw itemstack equals No NBT",
    "itemstack raw itemstack Equals no NBT",
    "itemstack raw itemstack Equals No NBT",
    "itemstack raw Itemstack equals no NBT",
    "itemstack raw Itemstack equals No NBT",
    "itemstack raw Itemstack Equals no NBT",
    "itemstack raw Itemstack Equals No NBT",
    "itemstack raw itemStack equals no NBT",
    "itemstack raw itemStack equals No NBT",
    "itemstack raw itemStack Equals no NBT",
    "itemstack raw itemStack Equals No NBT",
    "itemstack raw ItemStack equals no NBT",
    "itemstack raw ItemStack equals No NBT",
    "itemstack raw ItemStack Equals no NBT",
    "itemstack raw ItemStack Equals No NBT",
    "itemstack Raw itemstack equals no NBT",
    "itemstack Raw itemstack equals No NBT",
    "itemstack Raw itemstack Equals no NBT",
    "itemstack Raw itemstack Equals No NBT",
    "itemstack Raw Itemstack equals no NBT",
    "itemstack Raw Itemstack equals No NBT",
    "itemstack Raw Itemstack Equals no NBT",
    "itemstack Raw Itemstack Equals No NBT",
    "itemstack Raw itemStack equals no NBT",
    "itemstack Raw itemStack equals No NBT",
    "itemstack Raw itemStack Equals no NBT",
    "itemstack Raw itemStack Equals No NBT",
    "itemstack Raw ItemStack equals no NBT",
    "itemstack Raw ItemStack equals No NBT",
    "itemstack Raw ItemStack Equals no NBT",
    "itemstack Raw ItemStack Equals No NBT",
    "Itemstack raw itemstack equals no NBT",
    "Itemstack raw itemstack equals No NBT",
    "Itemstack raw itemstack Equals no NBT",
    "Itemstack raw itemstack Equals No NBT",
    "Itemstack raw Itemstack equals no NBT",
    "Itemstack raw Itemstack equals No NBT",
    "Itemstack raw Itemstack Equals no NBT",
    "Itemstack raw Itemstack Equals No NBT",
    "Itemstack raw itemStack equals no NBT",
    "Itemstack raw itemStack equals No NBT",
    "Itemstack raw itemStack Equals no NBT",
    "Itemstack raw itemStack Equals No NBT",
    "Itemstack raw ItemStack equals no NBT",
    "Itemstack raw ItemStack equals No NBT",
    "Itemstack raw ItemStack Equals no NBT",
    "Itemstack raw ItemStack Equals No NBT",
    "Itemstack Raw itemstack equals no NBT",
    "Itemstack Raw itemstack equals No NBT",
    "Itemstack Raw itemstack Equals no NBT",
    "Itemstack Raw itemstack Equals No NBT",
    "Itemstack Raw Itemstack equals no NBT",
    "Itemstack Raw Itemstack equals No NBT",
    "Itemstack Raw Itemstack Equals no NBT",
    "Itemstack Raw Itemstack Equals No NBT",
    "Itemstack Raw itemStack equals no NBT",
    "Itemstack Raw itemStack equals No NBT",
    "Itemstack Raw itemStack Equals no NBT",
    "Itemstack Raw itemStack Equals No NBT",
    "Itemstack Raw ItemStack equals no NBT",
    "Itemstack Raw ItemStack equals No NBT",
    "Itemstack Raw ItemStack Equals no NBT",
    "Itemstack Raw ItemStack Equals No NBT",
    "itemStack raw itemstack equals no NBT",
    "itemStack raw itemstack equals No NBT",
    "itemStack raw itemstack Equals no NBT",
    "itemStack raw itemstack Equals No NBT",
    "itemStack raw Itemstack equals no NBT",
    "itemStack raw Itemstack equals No NBT",
    "itemStack raw Itemstack Equals no NBT",
    "itemStack raw Itemstack Equals No NBT",
    "itemStack raw itemStack equals no NBT",
    "itemStack raw itemStack equals No NBT",
    "itemStack raw itemStack Equals no NBT",
    "itemStack raw itemStack Equals No NBT",
    "itemStack raw ItemStack equals no NBT",
    "itemStack raw ItemStack equals No NBT",
    "itemStack raw ItemStack Equals no NBT",
    "itemStack raw ItemStack Equals No NBT",
    "itemStack Raw itemstack equals no NBT",
    "itemStack Raw itemstack equals No NBT",
    "itemStack Raw itemstack Equals no NBT",
    "itemStack Raw itemstack Equals No NBT",
    "itemStack Raw Itemstack equals no NBT",
    "itemStack Raw Itemstack equals No NBT",
    "itemStack Raw Itemstack Equals no NBT",
    "itemStack Raw Itemstack Equals No NBT",
    "itemStack Raw itemStack equals no NBT",
    "itemStack Raw itemStack equals No NBT",
    "itemStack Raw itemStack Equals no NBT",
    "itemStack Raw itemStack Equals No NBT",
    "itemStack Raw ItemStack equals no NBT",
    "itemStack Raw ItemStack equals No NBT",
    "itemStack Raw ItemStack Equals no NBT",
    "itemStack Raw ItemStack Equals No NBT",
    "ItemStack raw itemstack equals no NBT",
    "ItemStack raw itemstack equals No NBT",
    "ItemStack raw itemstack Equals no NBT",
    "ItemStack raw itemstack Equals No NBT",
    "ItemStack raw Itemstack equals no NBT",
    "ItemStack raw Itemstack equals No NBT",
    "ItemStack raw Itemstack Equals no NBT",
    "ItemStack raw Itemstack Equals No NBT",
    "ItemStack raw itemStack equals no NBT",
    "ItemStack raw itemStack equals No NBT",
    "ItemStack raw itemStack Equals no NBT",
    "ItemStack raw itemStack Equals No NBT",
    "ItemStack raw ItemStack equals no NBT",
    "ItemStack raw ItemStack equals No NBT",
    "ItemStack raw ItemStack Equals no NBT",
    "ItemStack raw ItemStack Equals No NBT",
    "ItemStack Raw itemstack equals no NBT",
    "ItemStack Raw itemstack equals No NBT",
    "ItemStack Raw itemstack Equals no NBT",
    "ItemStack Raw itemstack Equals No NBT",
    "ItemStack Raw Itemstack equals no NBT",
    "ItemStack Raw Itemstack equals No NBT",
    "ItemStack Raw Itemstack Equals no NBT",
    "ItemStack Raw Itemstack Equals No NBT",
    "ItemStack Raw itemStack equals no NBT",
    "ItemStack Raw itemStack equals No NBT",
    "ItemStack Raw itemStack Equals no NBT",
    "ItemStack Raw itemStack Equals No NBT",
    "ItemStack Raw ItemStack equals no NBT",
    "ItemStack Raw ItemStack equals No NBT",
    "ItemStack Raw ItemStack Equals no NBT",
    "ItemStack Raw ItemStack Equals No NBT",
    "raw item equals no nbt",
    "raw item equals no Nbt",
    "raw item equals No nbt",
    "raw item equals No Nbt",
    "raw item Equals no nbt",
    "raw item Equals no Nbt",
    "raw item Equals No nbt",
    "raw item Equals No Nbt",
    "raw Item equals no nbt",
    "raw Item equals no Nbt",
    "raw Item equals No nbt",
    "raw Item equals No Nbt",
    "raw Item Equals no nbt",
    "raw Item Equals no Nbt",
    "raw Item Equals No nbt",
    "raw Item Equals No Nbt",
    "Raw item equals no nbt",
    "Raw item equals no Nbt",
    "Raw item equals No nbt",
    "Raw item equals No Nbt",
    "Raw item Equals no nbt",
    "Raw item Equals no Nbt",
    "Raw item Equals No nbt",
    "Raw item Equals No Nbt",
    "Raw Item equals no nbt",
    "Raw Item equals no Nbt",
    "Raw Item equals No nbt",
    "Raw Item equals No Nbt",
    "Raw Item Equals no nbt",
    "Raw Item Equals no Nbt",
    "Raw Item Equals No nbt",
    "Raw Item Equals No Nbt",
    "raw item equals no NBT",
    "raw item equals No NBT",
    "raw item Equals no NBT",
    "raw item Equals No NBT",
    "raw Item equals no NBT",
    "raw Item equals No NBT",
    "raw Item Equals no NBT",
    "raw Item Equals No NBT",
    "Raw item equals no NBT",
    "Raw item equals No NBT",
    "Raw item Equals no NBT",
    "Raw item Equals No NBT",
    "Raw Item equals no NBT",
    "Raw Item equals No NBT",
    "Raw Item Equals no NBT",
    "Raw Item Equals No NBT",
    "raw itemstack equals no nbt",
    "raw itemstack equals no Nbt",
    "raw itemstack equals No nbt",
    "raw itemstack equals No Nbt",
    "raw itemstack Equals no nbt",
    "raw itemstack Equals no Nbt",
    "raw itemstack Equals No nbt",
    "raw itemstack Equals No Nbt",
    "raw Itemstack equals no nbt",
    "raw Itemstack equals no Nbt",
    "raw Itemstack equals No nbt",
    "raw Itemstack equals No Nbt",
    "raw Itemstack Equals no nbt",
    "raw Itemstack Equals no Nbt",
    "raw Itemstack Equals No nbt",
    "raw Itemstack Equals No Nbt",
    "raw itemStack equals no nbt",
    "raw itemStack equals no Nbt",
    "raw itemStack equals No nbt",
    "raw itemStack equals No Nbt",
    "raw itemStack Equals no nbt",
    "raw itemStack Equals no Nbt",
    "raw itemStack Equals No nbt",
    "raw itemStack Equals No Nbt",
    "raw ItemStack equals no nbt",
    "raw ItemStack equals no Nbt",
    "raw ItemStack equals No nbt",
    "raw ItemStack equals No Nbt",
    "raw ItemStack Equals no nbt",
    "raw ItemStack Equals no Nbt",
    "raw ItemStack Equals No nbt",
    "raw ItemStack Equals No Nbt",
    "Raw itemstack equals no nbt",
    "Raw itemstack equals no Nbt",
    "Raw itemstack equals No nbt",
    "Raw itemstack equals No Nbt",
    "Raw itemstack Equals no nbt",
    "Raw itemstack Equals no Nbt",
    "Raw itemstack Equals No nbt",
    "Raw itemstack Equals No Nbt",
    "Raw Itemstack equals no nbt",
    "Raw Itemstack equals no Nbt",
    "Raw Itemstack equals No nbt",
    "Raw Itemstack equals No Nbt",
    "Raw Itemstack Equals no nbt",
    "Raw Itemstack Equals no Nbt",
    "Raw Itemstack Equals No nbt",
    "Raw Itemstack Equals No Nbt",
    "Raw itemStack equals no nbt",
    "Raw itemStack equals no Nbt",
    "Raw itemStack equals No nbt",
    "Raw itemStack equals No Nbt",
    "Raw itemStack Equals no nbt",
    "Raw itemStack Equals no Nbt",
    "Raw itemStack Equals No nbt",
    "Raw itemStack Equals No Nbt",
    "Raw ItemStack equals no nbt",
    "Raw ItemStack equals no Nbt",
    "Raw ItemStack equals No nbt",
    "Raw ItemStack equals No Nbt",
    "Raw ItemStack Equals no nbt",
    "Raw ItemStack Equals no Nbt",
    "Raw ItemStack Equals No nbt",
    "Raw ItemStack Equals No Nbt",
    "raw itemstack equals no NBT",
    "raw itemstack equals No NBT",
    "raw itemstack Equals no NBT",
    "raw itemstack Equals No NBT",
    "raw Itemstack equals no NBT",
    "raw Itemstack equals No NBT",
    "raw Itemstack Equals no NBT",
    "raw Itemstack Equals No NBT",
    "raw itemStack equals no NBT",
    "raw itemStack equals No NBT",
    "raw itemStack Equals no NBT",
    "raw itemStack Equals No NBT",
    "raw ItemStack equals no NBT",
    "raw ItemStack equals No NBT",
    "raw ItemStack Equals no NBT",
    "raw ItemStack Equals No NBT",
    "Raw itemstack equals no NBT",
    "Raw itemstack equals No NBT",
    "Raw itemstack Equals no NBT",
    "Raw itemstack Equals No NBT",
    "Raw Itemstack equals no NBT",
    "Raw Itemstack equals No NBT",
    "Raw Itemstack Equals no NBT",
    "Raw Itemstack Equals No NBT",
    "Raw itemStack equals no NBT",
    "Raw itemStack equals No NBT",
    "Raw itemStack Equals no NBT",
    "Raw itemStack Equals No NBT",
    "Raw ItemStack equals no NBT",
    "Raw ItemStack equals No NBT",
    "Raw ItemStack Equals no NBT",
    "Raw ItemStack Equals No NBT",
  ];
  static override tooltipInfo =
    "If the raw items of the given stacks are equal, ignoring NBT but including damage value." as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "INFIX" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Function",
            from: {
              type: "Item",
            },
            to: {
              type: "Boolean",
            },
          },
        },
        normalizeSignature
      ),
      function: (item1: Item): TypeLambda<Item, iBoolean> => {
        return (item2: Item): iBoolean => {
          return new iBoolean(
            item1.getUniqueName().valueOf() ===
              item2.getUniqueName().valueOf() &&
              item1.getSize().equals(item2.getSize()).valueOf()
          );
        };
      },
      flipTarget: "OBJECT_ITEMSTACK_ISITEMEQUALNODATA",
    });
  }
}
