import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";

export class OPERATOR_OBJECT_ITEMSTACK_TAG extends BaseOperator<
  Item,
  iArray<iString>
> {
  static override internalName = "integrateddynamics:itemstack_tags" as const;
  static override numericID = 201;
  static override nicknames = [
    "itemstackTag",
    "ItemstackTag",
    "itemstackTagNames",
    "itemstackTags",
    "itemTagNames",
    "item_tag_names",
    "itemstack_tag",
    "itemstack_tag_names",
    "itemstack_tags",
  ];
  static override symbol = "item_tag_names";
  static override interactName = "itemstackTags";
  static override operatorName = "tag" as const;
  static override displayName = "Item Tag Names" as const;
  static override fullDisplayName = "Item Item Tag Names" as const;
  static override stringDisplayNames = [
    "item item tag names",
    "item item tag Names",
    "item item Tag names",
    "item item Tag Names",
    "item Item tag names",
    "item Item tag Names",
    "item Item Tag names",
    "item Item Tag Names",
    "Item item tag names",
    "Item item tag Names",
    "Item item Tag names",
    "Item item Tag Names",
    "Item Item tag names",
    "Item Item tag Names",
    "Item Item Tag names",
    "Item Item Tag Names",
    "item itemstack tag names",
    "item itemstack tag Names",
    "item itemstack Tag names",
    "item itemstack Tag Names",
    "item Itemstack tag names",
    "item Itemstack tag Names",
    "item Itemstack Tag names",
    "item Itemstack Tag Names",
    "item itemStack tag names",
    "item itemStack tag Names",
    "item itemStack Tag names",
    "item itemStack Tag Names",
    "item ItemStack tag names",
    "item ItemStack tag Names",
    "item ItemStack Tag names",
    "item ItemStack Tag Names",
    "Item itemstack tag names",
    "Item itemstack tag Names",
    "Item itemstack Tag names",
    "Item itemstack Tag Names",
    "Item Itemstack tag names",
    "Item Itemstack tag Names",
    "Item Itemstack Tag names",
    "Item Itemstack Tag Names",
    "Item itemStack tag names",
    "Item itemStack tag Names",
    "Item itemStack Tag names",
    "Item itemStack Tag Names",
    "Item ItemStack tag names",
    "Item ItemStack tag Names",
    "Item ItemStack Tag names",
    "Item ItemStack Tag Names",
    "itemstack item tag names",
    "itemstack item tag Names",
    "itemstack item Tag names",
    "itemstack item Tag Names",
    "itemstack Item tag names",
    "itemstack Item tag Names",
    "itemstack Item Tag names",
    "itemstack Item Tag Names",
    "Itemstack item tag names",
    "Itemstack item tag Names",
    "Itemstack item Tag names",
    "Itemstack item Tag Names",
    "Itemstack Item tag names",
    "Itemstack Item tag Names",
    "Itemstack Item Tag names",
    "Itemstack Item Tag Names",
    "itemStack item tag names",
    "itemStack item tag Names",
    "itemStack item Tag names",
    "itemStack item Tag Names",
    "itemStack Item tag names",
    "itemStack Item tag Names",
    "itemStack Item Tag names",
    "itemStack Item Tag Names",
    "ItemStack item tag names",
    "ItemStack item tag Names",
    "ItemStack item Tag names",
    "ItemStack item Tag Names",
    "ItemStack Item tag names",
    "ItemStack Item tag Names",
    "ItemStack Item Tag names",
    "ItemStack Item Tag Names",
    "itemstack itemstack tag names",
    "itemstack itemstack tag Names",
    "itemstack itemstack Tag names",
    "itemstack itemstack Tag Names",
    "itemstack Itemstack tag names",
    "itemstack Itemstack tag Names",
    "itemstack Itemstack Tag names",
    "itemstack Itemstack Tag Names",
    "itemstack itemStack tag names",
    "itemstack itemStack tag Names",
    "itemstack itemStack Tag names",
    "itemstack itemStack Tag Names",
    "itemstack ItemStack tag names",
    "itemstack ItemStack tag Names",
    "itemstack ItemStack Tag names",
    "itemstack ItemStack Tag Names",
    "Itemstack itemstack tag names",
    "Itemstack itemstack tag Names",
    "Itemstack itemstack Tag names",
    "Itemstack itemstack Tag Names",
    "Itemstack Itemstack tag names",
    "Itemstack Itemstack tag Names",
    "Itemstack Itemstack Tag names",
    "Itemstack Itemstack Tag Names",
    "Itemstack itemStack tag names",
    "Itemstack itemStack tag Names",
    "Itemstack itemStack Tag names",
    "Itemstack itemStack Tag Names",
    "Itemstack ItemStack tag names",
    "Itemstack ItemStack tag Names",
    "Itemstack ItemStack Tag names",
    "Itemstack ItemStack Tag Names",
    "itemStack itemstack tag names",
    "itemStack itemstack tag Names",
    "itemStack itemstack Tag names",
    "itemStack itemstack Tag Names",
    "itemStack Itemstack tag names",
    "itemStack Itemstack tag Names",
    "itemStack Itemstack Tag names",
    "itemStack Itemstack Tag Names",
    "itemStack itemStack tag names",
    "itemStack itemStack tag Names",
    "itemStack itemStack Tag names",
    "itemStack itemStack Tag Names",
    "itemStack ItemStack tag names",
    "itemStack ItemStack tag Names",
    "itemStack ItemStack Tag names",
    "itemStack ItemStack Tag Names",
    "ItemStack itemstack tag names",
    "ItemStack itemstack tag Names",
    "ItemStack itemstack Tag names",
    "ItemStack itemstack Tag Names",
    "ItemStack Itemstack tag names",
    "ItemStack Itemstack tag Names",
    "ItemStack Itemstack Tag names",
    "ItemStack Itemstack Tag Names",
    "ItemStack itemStack tag names",
    "ItemStack itemStack tag Names",
    "ItemStack itemStack Tag names",
    "ItemStack itemStack Tag Names",
    "ItemStack ItemStack tag names",
    "ItemStack ItemStack tag Names",
    "ItemStack ItemStack Tag names",
    "ItemStack ItemStack Tag Names",
    "item tag names",
    "item tag Names",
    "item Tag names",
    "item Tag Names",
    "Item tag names",
    "Item tag Names",
    "Item Tag names",
    "Item Tag Names",
    "itemstack tag names",
    "itemstack tag Names",
    "itemstack Tag names",
    "itemstack Tag Names",
    "Itemstack tag names",
    "Itemstack tag Names",
    "Itemstack Tag names",
    "Itemstack Tag Names",
    "itemStack tag names",
    "itemStack tag Names",
    "itemStack Tag names",
    "itemStack Tag Names",
    "ItemStack tag names",
    "ItemStack tag Names",
    "ItemStack Tag names",
    "ItemStack Tag Names",
  ];
  static override tooltipInfo =
    "The Tag names (strings) of the given item" as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: { type: "List", listType: { type: "String" } },
        },
        normalizeSignature
      ),
      function: (item: Item): iArray<iString> => {
        return item.getTagNames();
      },
    });
  }
}
