import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";

export class OPERATOR_OBJECT_FLUIDSTACK_TAG extends BaseOperator<
  Fluid,
  iArray<iString>
> {
  static override internalName = "integrateddynamics:fluidstack_tag" as const;
  static override numericID = 297;
  static override nicknames = [
    "fluidstackTag",
    "FluidstackTag",
    "fluidstackTags",
    "fluidTag",
    "fluid_tag",
    "fluidstack_tag",
    "fluidstack_tags",
  ];
  static override symbol = "fluid_tag_names";
  static override interactName = "fluidstackTags";
  static override operatorName = "tag" as const;
  static override displayName = "Fluid Tag Names" as const;
  static override fullDisplayName = "Fluid Fluid Tag Names" as const;
  static override stringDisplayNames = [
    "fluid fluid tag names",
    "fluid fluid tag Names",
    "fluid fluid Tag names",
    "fluid fluid Tag Names",
    "fluid Fluid tag names",
    "fluid Fluid tag Names",
    "fluid Fluid Tag names",
    "fluid Fluid Tag Names",
    "Fluid fluid tag names",
    "Fluid fluid tag Names",
    "Fluid fluid Tag names",
    "Fluid fluid Tag Names",
    "Fluid Fluid tag names",
    "Fluid Fluid tag Names",
    "Fluid Fluid Tag names",
    "Fluid Fluid Tag Names",
    "fluid fluidstack tag names",
    "fluid fluidstack tag Names",
    "fluid fluidstack Tag names",
    "fluid fluidstack Tag Names",
    "fluid Fluidstack tag names",
    "fluid Fluidstack tag Names",
    "fluid Fluidstack Tag names",
    "fluid Fluidstack Tag Names",
    "fluid fluidStack tag names",
    "fluid fluidStack tag Names",
    "fluid fluidStack Tag names",
    "fluid fluidStack Tag Names",
    "fluid FluidStack tag names",
    "fluid FluidStack tag Names",
    "fluid FluidStack Tag names",
    "fluid FluidStack Tag Names",
    "Fluid fluidstack tag names",
    "Fluid fluidstack tag Names",
    "Fluid fluidstack Tag names",
    "Fluid fluidstack Tag Names",
    "Fluid Fluidstack tag names",
    "Fluid Fluidstack tag Names",
    "Fluid Fluidstack Tag names",
    "Fluid Fluidstack Tag Names",
    "Fluid fluidStack tag names",
    "Fluid fluidStack tag Names",
    "Fluid fluidStack Tag names",
    "Fluid fluidStack Tag Names",
    "Fluid FluidStack tag names",
    "Fluid FluidStack tag Names",
    "Fluid FluidStack Tag names",
    "Fluid FluidStack Tag Names",
    "fluidstack fluid tag names",
    "fluidstack fluid tag Names",
    "fluidstack fluid Tag names",
    "fluidstack fluid Tag Names",
    "fluidstack Fluid tag names",
    "fluidstack Fluid tag Names",
    "fluidstack Fluid Tag names",
    "fluidstack Fluid Tag Names",
    "Fluidstack fluid tag names",
    "Fluidstack fluid tag Names",
    "Fluidstack fluid Tag names",
    "Fluidstack fluid Tag Names",
    "Fluidstack Fluid tag names",
    "Fluidstack Fluid tag Names",
    "Fluidstack Fluid Tag names",
    "Fluidstack Fluid Tag Names",
    "fluidStack fluid tag names",
    "fluidStack fluid tag Names",
    "fluidStack fluid Tag names",
    "fluidStack fluid Tag Names",
    "fluidStack Fluid tag names",
    "fluidStack Fluid tag Names",
    "fluidStack Fluid Tag names",
    "fluidStack Fluid Tag Names",
    "FluidStack fluid tag names",
    "FluidStack fluid tag Names",
    "FluidStack fluid Tag names",
    "FluidStack fluid Tag Names",
    "FluidStack Fluid tag names",
    "FluidStack Fluid tag Names",
    "FluidStack Fluid Tag names",
    "FluidStack Fluid Tag Names",
    "fluidstack fluidstack tag names",
    "fluidstack fluidstack tag Names",
    "fluidstack fluidstack Tag names",
    "fluidstack fluidstack Tag Names",
    "fluidstack Fluidstack tag names",
    "fluidstack Fluidstack tag Names",
    "fluidstack Fluidstack Tag names",
    "fluidstack Fluidstack Tag Names",
    "fluidstack fluidStack tag names",
    "fluidstack fluidStack tag Names",
    "fluidstack fluidStack Tag names",
    "fluidstack fluidStack Tag Names",
    "fluidstack FluidStack tag names",
    "fluidstack FluidStack tag Names",
    "fluidstack FluidStack Tag names",
    "fluidstack FluidStack Tag Names",
    "Fluidstack fluidstack tag names",
    "Fluidstack fluidstack tag Names",
    "Fluidstack fluidstack Tag names",
    "Fluidstack fluidstack Tag Names",
    "Fluidstack Fluidstack tag names",
    "Fluidstack Fluidstack tag Names",
    "Fluidstack Fluidstack Tag names",
    "Fluidstack Fluidstack Tag Names",
    "Fluidstack fluidStack tag names",
    "Fluidstack fluidStack tag Names",
    "Fluidstack fluidStack Tag names",
    "Fluidstack fluidStack Tag Names",
    "Fluidstack FluidStack tag names",
    "Fluidstack FluidStack tag Names",
    "Fluidstack FluidStack Tag names",
    "Fluidstack FluidStack Tag Names",
    "fluidStack fluidstack tag names",
    "fluidStack fluidstack tag Names",
    "fluidStack fluidstack Tag names",
    "fluidStack fluidstack Tag Names",
    "fluidStack Fluidstack tag names",
    "fluidStack Fluidstack tag Names",
    "fluidStack Fluidstack Tag names",
    "fluidStack Fluidstack Tag Names",
    "fluidStack fluidStack tag names",
    "fluidStack fluidStack tag Names",
    "fluidStack fluidStack Tag names",
    "fluidStack fluidStack Tag Names",
    "fluidStack FluidStack tag names",
    "fluidStack FluidStack tag Names",
    "fluidStack FluidStack Tag names",
    "fluidStack FluidStack Tag Names",
    "FluidStack fluidstack tag names",
    "FluidStack fluidstack tag Names",
    "FluidStack fluidstack Tag names",
    "FluidStack fluidstack Tag Names",
    "FluidStack Fluidstack tag names",
    "FluidStack Fluidstack tag Names",
    "FluidStack Fluidstack Tag names",
    "FluidStack Fluidstack Tag Names",
    "FluidStack fluidStack tag names",
    "FluidStack fluidStack tag Names",
    "FluidStack fluidStack Tag names",
    "FluidStack fluidStack Tag Names",
    "FluidStack FluidStack tag names",
    "FluidStack FluidStack tag Names",
    "FluidStack FluidStack Tag names",
    "FluidStack FluidStack Tag Names",
    "fluid tag names",
    "fluid tag Names",
    "fluid Tag names",
    "fluid Tag Names",
    "Fluid tag names",
    "Fluid tag Names",
    "Fluid Tag names",
    "Fluid Tag Names",
    "fluidstack tag names",
    "fluidstack tag Names",
    "fluidstack Tag names",
    "fluidstack Tag Names",
    "Fluidstack tag names",
    "Fluidstack tag Names",
    "Fluidstack Tag names",
    "Fluidstack Tag Names",
    "fluidStack tag names",
    "fluidStack tag Names",
    "fluidStack Tag names",
    "fluidStack Tag Names",
    "FluidStack tag names",
    "FluidStack tag Names",
    "FluidStack Tag names",
    "FluidStack Tag Names",
  ];
  static override kind = "fluidstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: { type: "List", listType: { type: "String" } },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): iArray<iString> => {
        return new iArrayEager(
          fluid
            .getTagNames()
            .valueOf()
            .map((e: iString) => new iString(e.valueOf()))
        );
      },
    });
  }
}
