import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";
import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";

export class OPERATOR_OBJECT_FLUIDSTACK_DATAKEYS extends BaseOperator<
  Fluid,
  iArray<iString>
> {
  static override internalName =
    "integrateddynamics:fluidstack_datakeys" as const;
  static override numericID = 284;
  static override nicknames = [
    "fluidDataKeys",
    "fluidNBTKeys",
    "fluidstackDatakeys",
    "fluidstackDataKeys",
    "fluidStackDataKeys",
    "FluidstackDataKeys",
    "fluidstackFluidstackDatakeys",
    "fluidstackNBTKeys",
    "fluidStackNBTKeys",
    "fluid_data_keys",
    "fluid_n_b_t_keys",
    "fluid_NBT_keys",
    "fluid_stack_data_keys",
    "fluid_stack_n_b_t_keys",
    "fluid_stack_NBT_keys",
    "fluidstack_data_keys",
    "fluidstack_datakeys",
    "fluidstack_n_b_t_keys",
    "fluidstack_NBT_keys",
    "fluidstackFluidstack_datakeys",
  ];
  static override symbol = "data_keys";
  static override interactName = "fluidstackDataKeys";
  static override operatorName = "fluidstack_datakeys" as const;
  static override displayName = "Fluid Data Keys" as const;
  static override fullDisplayName = "Fluid Fluid Data Keys" as const;
  static override stringDisplayNames = [
    "fluid fluid data keys",
    "fluid fluid data Keys",
    "fluid fluid Data keys",
    "fluid fluid Data Keys",
    "fluid Fluid data keys",
    "fluid Fluid data Keys",
    "fluid Fluid Data keys",
    "fluid Fluid Data Keys",
    "Fluid fluid data keys",
    "Fluid fluid data Keys",
    "Fluid fluid Data keys",
    "Fluid fluid Data Keys",
    "Fluid Fluid data keys",
    "Fluid Fluid data Keys",
    "Fluid Fluid Data keys",
    "Fluid Fluid Data Keys",
    "fluid fluidstack data keys",
    "fluid fluidstack data Keys",
    "fluid fluidstack Data keys",
    "fluid fluidstack Data Keys",
    "fluid Fluidstack data keys",
    "fluid Fluidstack data Keys",
    "fluid Fluidstack Data keys",
    "fluid Fluidstack Data Keys",
    "fluid fluidStack data keys",
    "fluid fluidStack data Keys",
    "fluid fluidStack Data keys",
    "fluid fluidStack Data Keys",
    "fluid FluidStack data keys",
    "fluid FluidStack data Keys",
    "fluid FluidStack Data keys",
    "fluid FluidStack Data Keys",
    "Fluid fluidstack data keys",
    "Fluid fluidstack data Keys",
    "Fluid fluidstack Data keys",
    "Fluid fluidstack Data Keys",
    "Fluid Fluidstack data keys",
    "Fluid Fluidstack data Keys",
    "Fluid Fluidstack Data keys",
    "Fluid Fluidstack Data Keys",
    "Fluid fluidStack data keys",
    "Fluid fluidStack data Keys",
    "Fluid fluidStack Data keys",
    "Fluid fluidStack Data Keys",
    "Fluid FluidStack data keys",
    "Fluid FluidStack data Keys",
    "Fluid FluidStack Data keys",
    "Fluid FluidStack Data Keys",
    "fluidstack fluid data keys",
    "fluidstack fluid data Keys",
    "fluidstack fluid Data keys",
    "fluidstack fluid Data Keys",
    "fluidstack Fluid data keys",
    "fluidstack Fluid data Keys",
    "fluidstack Fluid Data keys",
    "fluidstack Fluid Data Keys",
    "Fluidstack fluid data keys",
    "Fluidstack fluid data Keys",
    "Fluidstack fluid Data keys",
    "Fluidstack fluid Data Keys",
    "Fluidstack Fluid data keys",
    "Fluidstack Fluid data Keys",
    "Fluidstack Fluid Data keys",
    "Fluidstack Fluid Data Keys",
    "fluidStack fluid data keys",
    "fluidStack fluid data Keys",
    "fluidStack fluid Data keys",
    "fluidStack fluid Data Keys",
    "fluidStack Fluid data keys",
    "fluidStack Fluid data Keys",
    "fluidStack Fluid Data keys",
    "fluidStack Fluid Data Keys",
    "FluidStack fluid data keys",
    "FluidStack fluid data Keys",
    "FluidStack fluid Data keys",
    "FluidStack fluid Data Keys",
    "FluidStack Fluid data keys",
    "FluidStack Fluid data Keys",
    "FluidStack Fluid Data keys",
    "FluidStack Fluid Data Keys",
    "fluidstack fluidstack data keys",
    "fluidstack fluidstack data Keys",
    "fluidstack fluidstack Data keys",
    "fluidstack fluidstack Data Keys",
    "fluidstack Fluidstack data keys",
    "fluidstack Fluidstack data Keys",
    "fluidstack Fluidstack Data keys",
    "fluidstack Fluidstack Data Keys",
    "fluidstack fluidStack data keys",
    "fluidstack fluidStack data Keys",
    "fluidstack fluidStack Data keys",
    "fluidstack fluidStack Data Keys",
    "fluidstack FluidStack data keys",
    "fluidstack FluidStack data Keys",
    "fluidstack FluidStack Data keys",
    "fluidstack FluidStack Data Keys",
    "Fluidstack fluidstack data keys",
    "Fluidstack fluidstack data Keys",
    "Fluidstack fluidstack Data keys",
    "Fluidstack fluidstack Data Keys",
    "Fluidstack Fluidstack data keys",
    "Fluidstack Fluidstack data Keys",
    "Fluidstack Fluidstack Data keys",
    "Fluidstack Fluidstack Data Keys",
    "Fluidstack fluidStack data keys",
    "Fluidstack fluidStack data Keys",
    "Fluidstack fluidStack Data keys",
    "Fluidstack fluidStack Data Keys",
    "Fluidstack FluidStack data keys",
    "Fluidstack FluidStack data Keys",
    "Fluidstack FluidStack Data keys",
    "Fluidstack FluidStack Data Keys",
    "fluidStack fluidstack data keys",
    "fluidStack fluidstack data Keys",
    "fluidStack fluidstack Data keys",
    "fluidStack fluidstack Data Keys",
    "fluidStack Fluidstack data keys",
    "fluidStack Fluidstack data Keys",
    "fluidStack Fluidstack Data keys",
    "fluidStack Fluidstack Data Keys",
    "fluidStack fluidStack data keys",
    "fluidStack fluidStack data Keys",
    "fluidStack fluidStack Data keys",
    "fluidStack fluidStack Data Keys",
    "fluidStack FluidStack data keys",
    "fluidStack FluidStack data Keys",
    "fluidStack FluidStack Data keys",
    "fluidStack FluidStack Data Keys",
    "FluidStack fluidstack data keys",
    "FluidStack fluidstack data Keys",
    "FluidStack fluidstack Data keys",
    "FluidStack fluidstack Data Keys",
    "FluidStack Fluidstack data keys",
    "FluidStack Fluidstack data Keys",
    "FluidStack Fluidstack Data keys",
    "FluidStack Fluidstack Data Keys",
    "FluidStack fluidStack data keys",
    "FluidStack fluidStack data Keys",
    "FluidStack fluidStack Data keys",
    "FluidStack fluidStack Data Keys",
    "FluidStack FluidStack data keys",
    "FluidStack FluidStack data Keys",
    "FluidStack FluidStack Data keys",
    "FluidStack FluidStack Data Keys",
    "fluid data keys",
    "fluid data Keys",
    "fluid Data keys",
    "fluid Data Keys",
    "Fluid data keys",
    "Fluid data Keys",
    "Fluid Data keys",
    "Fluid Data Keys",
    "fluidstack data keys",
    "fluidstack data Keys",
    "fluidstack Data keys",
    "fluidstack Data Keys",
    "Fluidstack data keys",
    "Fluidstack data Keys",
    "Fluidstack Data keys",
    "Fluidstack Data Keys",
    "fluidStack data keys",
    "fluidStack data Keys",
    "fluidStack Data keys",
    "fluidStack Data Keys",
    "FluidStack data keys",
    "FluidStack data Keys",
    "FluidStack Data keys",
    "FluidStack Data Keys",
  ];
  static override kind = "fluidstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: { type: "List", listType: { type: "String" } },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): iArray<iString> => {
        const nbt = fluid.getNBT();
        if (nbt instanceof CompoundTag) {
          return nbt.getAllKeys();
        }
        return new iArrayEager([]);
      },
    });
  }
}
