import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Tag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/Tag";
import { Fluid } from "lib/IntegratedDynamicsClasses/Fluid";

export class OPERATOR_OBJECT_FLUIDSTACK_DATA extends BaseOperator<
  Fluid,
  Tag<IntegratedValue>
> {
  static override internalName = "integrateddynamics:fluidstack_nbt" as const;
  static override numericID = 281;
  static override nicknames = [
    "fluidData",
    "fluidNBT",
    "fluidstackData",
    "fluidStackData",
    "FluidstackData",
    "fluidstackNbt",
    "fluidStackNBT",
    "fluid_data",
    "fluid_n_b_t",
    "fluid_NBT",
    "fluid_stack_data",
    "fluid_stack_n_b_t",
    "fluid_stack_NBT",
    "fluidstack_data",
    "fluidstack_nbt",
    "fluidstack_NBT",
  ];
  static override symbol = "NBT()";
  static override interactName = "fluidstackNbt";
  static override operatorName = "nbt" as const;
  static override displayName = "Fluid NBT" as const;
  static override fullDisplayName = "Fluid Fluid NBT" as const;
  static override stringDisplayNames = [
    "fluid fluid nbt",
    "fluid fluid Nbt",
    "fluid Fluid nbt",
    "fluid Fluid Nbt",
    "Fluid fluid nbt",
    "Fluid fluid Nbt",
    "Fluid Fluid nbt",
    "Fluid Fluid Nbt",
    "fluid fluid NBT",
    "fluid Fluid NBT",
    "Fluid fluid NBT",
    "Fluid Fluid NBT",
    "fluid fluidstack nbt",
    "fluid fluidstack Nbt",
    "fluid Fluidstack nbt",
    "fluid Fluidstack Nbt",
    "fluid fluidStack nbt",
    "fluid fluidStack Nbt",
    "fluid FluidStack nbt",
    "fluid FluidStack Nbt",
    "Fluid fluidstack nbt",
    "Fluid fluidstack Nbt",
    "Fluid Fluidstack nbt",
    "Fluid Fluidstack Nbt",
    "Fluid fluidStack nbt",
    "Fluid fluidStack Nbt",
    "Fluid FluidStack nbt",
    "Fluid FluidStack Nbt",
    "fluid fluidstack NBT",
    "fluid Fluidstack NBT",
    "fluid fluidStack NBT",
    "fluid FluidStack NBT",
    "Fluid fluidstack NBT",
    "Fluid Fluidstack NBT",
    "Fluid fluidStack NBT",
    "Fluid FluidStack NBT",
    "fluidstack fluid nbt",
    "fluidstack fluid Nbt",
    "fluidstack Fluid nbt",
    "fluidstack Fluid Nbt",
    "Fluidstack fluid nbt",
    "Fluidstack fluid Nbt",
    "Fluidstack Fluid nbt",
    "Fluidstack Fluid Nbt",
    "fluidStack fluid nbt",
    "fluidStack fluid Nbt",
    "fluidStack Fluid nbt",
    "fluidStack Fluid Nbt",
    "FluidStack fluid nbt",
    "FluidStack fluid Nbt",
    "FluidStack Fluid nbt",
    "FluidStack Fluid Nbt",
    "fluidstack fluid NBT",
    "fluidstack Fluid NBT",
    "Fluidstack fluid NBT",
    "Fluidstack Fluid NBT",
    "fluidStack fluid NBT",
    "fluidStack Fluid NBT",
    "FluidStack fluid NBT",
    "FluidStack Fluid NBT",
    "fluidstack fluidstack nbt",
    "fluidstack fluidstack Nbt",
    "fluidstack Fluidstack nbt",
    "fluidstack Fluidstack Nbt",
    "fluidstack fluidStack nbt",
    "fluidstack fluidStack Nbt",
    "fluidstack FluidStack nbt",
    "fluidstack FluidStack Nbt",
    "Fluidstack fluidstack nbt",
    "Fluidstack fluidstack Nbt",
    "Fluidstack Fluidstack nbt",
    "Fluidstack Fluidstack Nbt",
    "Fluidstack fluidStack nbt",
    "Fluidstack fluidStack Nbt",
    "Fluidstack FluidStack nbt",
    "Fluidstack FluidStack Nbt",
    "fluidStack fluidstack nbt",
    "fluidStack fluidstack Nbt",
    "fluidStack Fluidstack nbt",
    "fluidStack Fluidstack Nbt",
    "fluidStack fluidStack nbt",
    "fluidStack fluidStack Nbt",
    "fluidStack FluidStack nbt",
    "fluidStack FluidStack Nbt",
    "FluidStack fluidstack nbt",
    "FluidStack fluidstack Nbt",
    "FluidStack Fluidstack nbt",
    "FluidStack Fluidstack Nbt",
    "FluidStack fluidStack nbt",
    "FluidStack fluidStack Nbt",
    "FluidStack FluidStack nbt",
    "FluidStack FluidStack Nbt",
    "fluidstack fluidstack NBT",
    "fluidstack Fluidstack NBT",
    "fluidstack fluidStack NBT",
    "fluidstack FluidStack NBT",
    "Fluidstack fluidstack NBT",
    "Fluidstack Fluidstack NBT",
    "Fluidstack fluidStack NBT",
    "Fluidstack FluidStack NBT",
    "fluidStack fluidstack NBT",
    "fluidStack Fluidstack NBT",
    "fluidStack fluidStack NBT",
    "fluidStack FluidStack NBT",
    "FluidStack fluidstack NBT",
    "FluidStack Fluidstack NBT",
    "FluidStack fluidStack NBT",
    "FluidStack FluidStack NBT",
    "fluid nbt",
    "fluid Nbt",
    "Fluid nbt",
    "Fluid Nbt",
    "fluid NBT",
    "Fluid NBT",
    "fluidstack nbt",
    "fluidstack Nbt",
    "Fluidstack nbt",
    "Fluidstack Nbt",
    "fluidStack nbt",
    "fluidStack Nbt",
    "FluidStack nbt",
    "FluidStack Nbt",
    "fluidstack NBT",
    "Fluidstack NBT",
    "fluidStack NBT",
    "FluidStack NBT",
  ];
  static override tooltipInfo = "Get the NBT tag of the given fluid." as const;

  static override kind = "fluidstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Fluid",
          },
          to: {
            type: "NBT",
          },
        },
        normalizeSignature
      ),
      function: (fluid: Fluid): Tag<IntegratedValue> => {
        return fluid.getNBT();
      },
    });
  }
}
