import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iBoolean } from "lib/IntegratedDynamicsClasses/typeWrappers/iBoolean";
import { Item } from "lib/IntegratedDynamicsClasses/Item";

export class OPERATOR_OBJECT_ITEMSTACK_ISPLANTABLE extends BaseOperator<
  Item,
  iBoolean
> {
  static override internalName =
    "integrateddynamics:itemstack_is_plantable" as const;
  static override numericID = 123;
  static override nicknames = [
    "itemIsPlantable",
    "itemstackIsPlantable",
    "item_is_plantable",
    "itemstack_is_plantable",
  ];
  static override symbol = "is_plantable";
  static override interactName = "isPlantable";
  static override operatorName = "isplantable" as const;
  static override displayName = "Item Is Plant" as const;
  static override fullDisplayName = "Item Item Is Plant" as const;
  static override stringDisplayNames = [
    "item item is plant",
    "item item is Plant",
    "item item Is plant",
    "item item Is Plant",
    "item Item is plant",
    "item Item is Plant",
    "item Item Is plant",
    "item Item Is Plant",
    "Item item is plant",
    "Item item is Plant",
    "Item item Is plant",
    "Item item Is Plant",
    "Item Item is plant",
    "Item Item is Plant",
    "Item Item Is plant",
    "Item Item Is Plant",
    "item itemstack is plant",
    "item itemstack is Plant",
    "item itemstack Is plant",
    "item itemstack Is Plant",
    "item Itemstack is plant",
    "item Itemstack is Plant",
    "item Itemstack Is plant",
    "item Itemstack Is Plant",
    "item itemStack is plant",
    "item itemStack is Plant",
    "item itemStack Is plant",
    "item itemStack Is Plant",
    "item ItemStack is plant",
    "item ItemStack is Plant",
    "item ItemStack Is plant",
    "item ItemStack Is Plant",
    "Item itemstack is plant",
    "Item itemstack is Plant",
    "Item itemstack Is plant",
    "Item itemstack Is Plant",
    "Item Itemstack is plant",
    "Item Itemstack is Plant",
    "Item Itemstack Is plant",
    "Item Itemstack Is Plant",
    "Item itemStack is plant",
    "Item itemStack is Plant",
    "Item itemStack Is plant",
    "Item itemStack Is Plant",
    "Item ItemStack is plant",
    "Item ItemStack is Plant",
    "Item ItemStack Is plant",
    "Item ItemStack Is Plant",
    "itemstack item is plant",
    "itemstack item is Plant",
    "itemstack item Is plant",
    "itemstack item Is Plant",
    "itemstack Item is plant",
    "itemstack Item is Plant",
    "itemstack Item Is plant",
    "itemstack Item Is Plant",
    "Itemstack item is plant",
    "Itemstack item is Plant",
    "Itemstack item Is plant",
    "Itemstack item Is Plant",
    "Itemstack Item is plant",
    "Itemstack Item is Plant",
    "Itemstack Item Is plant",
    "Itemstack Item Is Plant",
    "itemStack item is plant",
    "itemStack item is Plant",
    "itemStack item Is plant",
    "itemStack item Is Plant",
    "itemStack Item is plant",
    "itemStack Item is Plant",
    "itemStack Item Is plant",
    "itemStack Item Is Plant",
    "ItemStack item is plant",
    "ItemStack item is Plant",
    "ItemStack item Is plant",
    "ItemStack item Is Plant",
    "ItemStack Item is plant",
    "ItemStack Item is Plant",
    "ItemStack Item Is plant",
    "ItemStack Item Is Plant",
    "itemstack itemstack is plant",
    "itemstack itemstack is Plant",
    "itemstack itemstack Is plant",
    "itemstack itemstack Is Plant",
    "itemstack Itemstack is plant",
    "itemstack Itemstack is Plant",
    "itemstack Itemstack Is plant",
    "itemstack Itemstack Is Plant",
    "itemstack itemStack is plant",
    "itemstack itemStack is Plant",
    "itemstack itemStack Is plant",
    "itemstack itemStack Is Plant",
    "itemstack ItemStack is plant",
    "itemstack ItemStack is Plant",
    "itemstack ItemStack Is plant",
    "itemstack ItemStack Is Plant",
    "Itemstack itemstack is plant",
    "Itemstack itemstack is Plant",
    "Itemstack itemstack Is plant",
    "Itemstack itemstack Is Plant",
    "Itemstack Itemstack is plant",
    "Itemstack Itemstack is Plant",
    "Itemstack Itemstack Is plant",
    "Itemstack Itemstack Is Plant",
    "Itemstack itemStack is plant",
    "Itemstack itemStack is Plant",
    "Itemstack itemStack Is plant",
    "Itemstack itemStack Is Plant",
    "Itemstack ItemStack is plant",
    "Itemstack ItemStack is Plant",
    "Itemstack ItemStack Is plant",
    "Itemstack ItemStack Is Plant",
    "itemStack itemstack is plant",
    "itemStack itemstack is Plant",
    "itemStack itemstack Is plant",
    "itemStack itemstack Is Plant",
    "itemStack Itemstack is plant",
    "itemStack Itemstack is Plant",
    "itemStack Itemstack Is plant",
    "itemStack Itemstack Is Plant",
    "itemStack itemStack is plant",
    "itemStack itemStack is Plant",
    "itemStack itemStack Is plant",
    "itemStack itemStack Is Plant",
    "itemStack ItemStack is plant",
    "itemStack ItemStack is Plant",
    "itemStack ItemStack Is plant",
    "itemStack ItemStack Is Plant",
    "ItemStack itemstack is plant",
    "ItemStack itemstack is Plant",
    "ItemStack itemstack Is plant",
    "ItemStack itemstack Is Plant",
    "ItemStack Itemstack is plant",
    "ItemStack Itemstack is Plant",
    "ItemStack Itemstack Is plant",
    "ItemStack Itemstack Is Plant",
    "ItemStack itemStack is plant",
    "ItemStack itemStack is Plant",
    "ItemStack itemStack Is plant",
    "ItemStack itemStack Is Plant",
    "ItemStack ItemStack is plant",
    "ItemStack ItemStack is Plant",
    "ItemStack ItemStack Is plant",
    "ItemStack ItemStack Is Plant",
    "item is plant",
    "item is Plant",
    "item Is plant",
    "item Is Plant",
    "Item is plant",
    "Item is Plant",
    "Item Is plant",
    "Item Is Plant",
    "itemstack is plant",
    "itemstack is Plant",
    "itemstack Is plant",
    "itemstack Is Plant",
    "Itemstack is plant",
    "Itemstack is Plant",
    "Itemstack Is plant",
    "Itemstack Is Plant",
    "itemStack is plant",
    "itemStack is Plant",
    "itemStack Is plant",
    "itemStack Is Plant",
    "ItemStack is plant",
    "ItemStack is Plant",
    "ItemStack Is plant",
    "ItemStack Is Plant",
  ];
  static override tooltipInfo = "If the given item is a plant" as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Boolean",
          },
        },
        normalizeSignature
      ),
      function: (item: Item): iBoolean => {
        return item.isPlantable();
      },
    });
  }
}
