import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iBoolean } from "lib/IntegratedDynamicsClasses/typeWrappers/iBoolean";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { Integer } from "lib/JavaNumberClasses/Integer";

export class OPERATOR_OBJECT_ITEMSTACK_HASINVENTORY extends BaseOperator<
  Item,
  iBoolean
> {
  static override internalName =
    "integrateddynamics:itemstack_hasinventory" as const;
  static override numericID = 133;
  static override nicknames = [
    "hasinventory",
    "hasInventory",
    "itemstackHasinventory",
    "itemstackHasInventory",
    "ItemstackHasinventory",
    "has_inventory",
    "itemstack_has_inventory",
    "itemstack_hasinventory",
  ];
  static override symbol = "has_inventory";
  static override interactName = "itemstackHasInventory";
  static override operatorName = "hasinventory" as const;
  static override displayName = "Item Has Inventory" as const;
  static override fullDisplayName = "Item Item Has Inventory" as const;
  static override stringDisplayNames = [
    "item item has inventory",
    "item item has Inventory",
    "item item Has inventory",
    "item item Has Inventory",
    "item Item has inventory",
    "item Item has Inventory",
    "item Item Has inventory",
    "item Item Has Inventory",
    "Item item has inventory",
    "Item item has Inventory",
    "Item item Has inventory",
    "Item item Has Inventory",
    "Item Item has inventory",
    "Item Item has Inventory",
    "Item Item Has inventory",
    "Item Item Has Inventory",
    "item itemstack has inventory",
    "item itemstack has Inventory",
    "item itemstack Has inventory",
    "item itemstack Has Inventory",
    "item Itemstack has inventory",
    "item Itemstack has Inventory",
    "item Itemstack Has inventory",
    "item Itemstack Has Inventory",
    "item itemStack has inventory",
    "item itemStack has Inventory",
    "item itemStack Has inventory",
    "item itemStack Has Inventory",
    "item ItemStack has inventory",
    "item ItemStack has Inventory",
    "item ItemStack Has inventory",
    "item ItemStack Has Inventory",
    "Item itemstack has inventory",
    "Item itemstack has Inventory",
    "Item itemstack Has inventory",
    "Item itemstack Has Inventory",
    "Item Itemstack has inventory",
    "Item Itemstack has Inventory",
    "Item Itemstack Has inventory",
    "Item Itemstack Has Inventory",
    "Item itemStack has inventory",
    "Item itemStack has Inventory",
    "Item itemStack Has inventory",
    "Item itemStack Has Inventory",
    "Item ItemStack has inventory",
    "Item ItemStack has Inventory",
    "Item ItemStack Has inventory",
    "Item ItemStack Has Inventory",
    "itemstack item has inventory",
    "itemstack item has Inventory",
    "itemstack item Has inventory",
    "itemstack item Has Inventory",
    "itemstack Item has inventory",
    "itemstack Item has Inventory",
    "itemstack Item Has inventory",
    "itemstack Item Has Inventory",
    "Itemstack item has inventory",
    "Itemstack item has Inventory",
    "Itemstack item Has inventory",
    "Itemstack item Has Inventory",
    "Itemstack Item has inventory",
    "Itemstack Item has Inventory",
    "Itemstack Item Has inventory",
    "Itemstack Item Has Inventory",
    "itemStack item has inventory",
    "itemStack item has Inventory",
    "itemStack item Has inventory",
    "itemStack item Has Inventory",
    "itemStack Item has inventory",
    "itemStack Item has Inventory",
    "itemStack Item Has inventory",
    "itemStack Item Has Inventory",
    "ItemStack item has inventory",
    "ItemStack item has Inventory",
    "ItemStack item Has inventory",
    "ItemStack item Has Inventory",
    "ItemStack Item has inventory",
    "ItemStack Item has Inventory",
    "ItemStack Item Has inventory",
    "ItemStack Item Has Inventory",
    "itemstack itemstack has inventory",
    "itemstack itemstack has Inventory",
    "itemstack itemstack Has inventory",
    "itemstack itemstack Has Inventory",
    "itemstack Itemstack has inventory",
    "itemstack Itemstack has Inventory",
    "itemstack Itemstack Has inventory",
    "itemstack Itemstack Has Inventory",
    "itemstack itemStack has inventory",
    "itemstack itemStack has Inventory",
    "itemstack itemStack Has inventory",
    "itemstack itemStack Has Inventory",
    "itemstack ItemStack has inventory",
    "itemstack ItemStack has Inventory",
    "itemstack ItemStack Has inventory",
    "itemstack ItemStack Has Inventory",
    "Itemstack itemstack has inventory",
    "Itemstack itemstack has Inventory",
    "Itemstack itemstack Has inventory",
    "Itemstack itemstack Has Inventory",
    "Itemstack Itemstack has inventory",
    "Itemstack Itemstack has Inventory",
    "Itemstack Itemstack Has inventory",
    "Itemstack Itemstack Has Inventory",
    "Itemstack itemStack has inventory",
    "Itemstack itemStack has Inventory",
    "Itemstack itemStack Has inventory",
    "Itemstack itemStack Has Inventory",
    "Itemstack ItemStack has inventory",
    "Itemstack ItemStack has Inventory",
    "Itemstack ItemStack Has inventory",
    "Itemstack ItemStack Has Inventory",
    "itemStack itemstack has inventory",
    "itemStack itemstack has Inventory",
    "itemStack itemstack Has inventory",
    "itemStack itemstack Has Inventory",
    "itemStack Itemstack has inventory",
    "itemStack Itemstack has Inventory",
    "itemStack Itemstack Has inventory",
    "itemStack Itemstack Has Inventory",
    "itemStack itemStack has inventory",
    "itemStack itemStack has Inventory",
    "itemStack itemStack Has inventory",
    "itemStack itemStack Has Inventory",
    "itemStack ItemStack has inventory",
    "itemStack ItemStack has Inventory",
    "itemStack ItemStack Has inventory",
    "itemStack ItemStack Has Inventory",
    "ItemStack itemstack has inventory",
    "ItemStack itemstack has Inventory",
    "ItemStack itemstack Has inventory",
    "ItemStack itemstack Has Inventory",
    "ItemStack Itemstack has inventory",
    "ItemStack Itemstack has Inventory",
    "ItemStack Itemstack Has inventory",
    "ItemStack Itemstack Has Inventory",
    "ItemStack itemStack has inventory",
    "ItemStack itemStack has Inventory",
    "ItemStack itemStack Has inventory",
    "ItemStack itemStack Has Inventory",
    "ItemStack ItemStack has inventory",
    "ItemStack ItemStack has Inventory",
    "ItemStack ItemStack Has inventory",
    "ItemStack ItemStack Has Inventory",
    "item has inventory",
    "item has Inventory",
    "item Has inventory",
    "item Has Inventory",
    "Item has inventory",
    "Item has Inventory",
    "Item Has inventory",
    "Item Has Inventory",
    "itemstack has inventory",
    "itemstack has Inventory",
    "itemstack Has inventory",
    "itemstack Has Inventory",
    "Itemstack has inventory",
    "Itemstack has Inventory",
    "Itemstack Has inventory",
    "Itemstack Has Inventory",
    "itemStack has inventory",
    "itemStack has Inventory",
    "itemStack Has inventory",
    "itemStack Has Inventory",
    "ItemStack has inventory",
    "ItemStack has Inventory",
    "ItemStack Has inventory",
    "ItemStack Has Inventory",
  ];
  static override tooltipInfo = "If the given item has an inventory" as const;

  static override kind = "itemstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: {
            type: "Boolean",
          },
        },
        normalizeSignature
      ),
      function: (item: Item): iBoolean => {
        return new iBoolean(item.getInventory().size().gt(Integer.ZERO));
      },
    });
  }
}
