import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { iArray } from "lib/IntegratedDynamicsClasses/typeWrappers/iArray";
import { iString } from "lib/IntegratedDynamicsClasses/typeWrappers/iString";
import { Item } from "lib/IntegratedDynamicsClasses/Item";
import { CompoundTag } from "lib/IntegratedDynamicsClasses/NBTFunctions/MinecraftClasses/CompoundTag";
import { iArrayEager } from "lib/IntegratedDynamicsClasses/typeWrappers/iArrayEager";

export class OPERATOR_OBJECT_ITEMSTACK_DATA_KEYS extends BaseOperator<
  Item,
  iArray<iString>
> {
  static override internalName =
    "integrateddynamics:itemstack_datakeys" as const;
  static override numericID = 287;
  static override nicknames = [
    "itemNBTKeys",
    "itemstackDatakeys",
    "itemstackDataKeys",
    "itemStackDataKeys",
    "ItemstackDatakeys",
    "itemstackItemstackDatakeys",
    "item_n_b_t_keys",
    "item_stack_data_keys",
    "itemstack_data_keys",
    "itemstack_datakeys",
    "itemstackItemstack_datakeys",
  ];
  static override symbol = "data_keys";
  static override interactName = "itemStackDataKeys";
  static override operatorName = "itemstack_datakeys" as const;
  static override displayName = "Item Data Keys" as const;
  static override fullDisplayName = "Item Item Data Keys" as const;
  static override stringDisplayNames = [
    "item item data keys",
    "item item data Keys",
    "item item Data keys",
    "item item Data Keys",
    "item Item data keys",
    "item Item data Keys",
    "item Item Data keys",
    "item Item Data Keys",
    "Item item data keys",
    "Item item data Keys",
    "Item item Data keys",
    "Item item Data Keys",
    "Item Item data keys",
    "Item Item data Keys",
    "Item Item Data keys",
    "Item Item Data Keys",
    "item itemstack data keys",
    "item itemstack data Keys",
    "item itemstack Data keys",
    "item itemstack Data Keys",
    "item Itemstack data keys",
    "item Itemstack data Keys",
    "item Itemstack Data keys",
    "item Itemstack Data Keys",
    "item itemStack data keys",
    "item itemStack data Keys",
    "item itemStack Data keys",
    "item itemStack Data Keys",
    "item ItemStack data keys",
    "item ItemStack data Keys",
    "item ItemStack Data keys",
    "item ItemStack Data Keys",
    "Item itemstack data keys",
    "Item itemstack data Keys",
    "Item itemstack Data keys",
    "Item itemstack Data Keys",
    "Item Itemstack data keys",
    "Item Itemstack data Keys",
    "Item Itemstack Data keys",
    "Item Itemstack Data Keys",
    "Item itemStack data keys",
    "Item itemStack data Keys",
    "Item itemStack Data keys",
    "Item itemStack Data Keys",
    "Item ItemStack data keys",
    "Item ItemStack data Keys",
    "Item ItemStack Data keys",
    "Item ItemStack Data Keys",
    "itemstack item data keys",
    "itemstack item data Keys",
    "itemstack item Data keys",
    "itemstack item Data Keys",
    "itemstack Item data keys",
    "itemstack Item data Keys",
    "itemstack Item Data keys",
    "itemstack Item Data Keys",
    "Itemstack item data keys",
    "Itemstack item data Keys",
    "Itemstack item Data keys",
    "Itemstack item Data Keys",
    "Itemstack Item data keys",
    "Itemstack Item data Keys",
    "Itemstack Item Data keys",
    "Itemstack Item Data Keys",
    "itemStack item data keys",
    "itemStack item data Keys",
    "itemStack item Data keys",
    "itemStack item Data Keys",
    "itemStack Item data keys",
    "itemStack Item data Keys",
    "itemStack Item Data keys",
    "itemStack Item Data Keys",
    "ItemStack item data keys",
    "ItemStack item data Keys",
    "ItemStack item Data keys",
    "ItemStack item Data Keys",
    "ItemStack Item data keys",
    "ItemStack Item data Keys",
    "ItemStack Item Data keys",
    "ItemStack Item Data Keys",
    "itemstack itemstack data keys",
    "itemstack itemstack data Keys",
    "itemstack itemstack Data keys",
    "itemstack itemstack Data Keys",
    "itemstack Itemstack data keys",
    "itemstack Itemstack data Keys",
    "itemstack Itemstack Data keys",
    "itemstack Itemstack Data Keys",
    "itemstack itemStack data keys",
    "itemstack itemStack data Keys",
    "itemstack itemStack Data keys",
    "itemstack itemStack Data Keys",
    "itemstack ItemStack data keys",
    "itemstack ItemStack data Keys",
    "itemstack ItemStack Data keys",
    "itemstack ItemStack Data Keys",
    "Itemstack itemstack data keys",
    "Itemstack itemstack data Keys",
    "Itemstack itemstack Data keys",
    "Itemstack itemstack Data Keys",
    "Itemstack Itemstack data keys",
    "Itemstack Itemstack data Keys",
    "Itemstack Itemstack Data keys",
    "Itemstack Itemstack Data Keys",
    "Itemstack itemStack data keys",
    "Itemstack itemStack data Keys",
    "Itemstack itemStack Data keys",
    "Itemstack itemStack Data Keys",
    "Itemstack ItemStack data keys",
    "Itemstack ItemStack data Keys",
    "Itemstack ItemStack Data keys",
    "Itemstack ItemStack Data Keys",
    "itemStack itemstack data keys",
    "itemStack itemstack data Keys",
    "itemStack itemstack Data keys",
    "itemStack itemstack Data Keys",
    "itemStack Itemstack data keys",
    "itemStack Itemstack data Keys",
    "itemStack Itemstack Data keys",
    "itemStack Itemstack Data Keys",
    "itemStack itemStack data keys",
    "itemStack itemStack data Keys",
    "itemStack itemStack Data keys",
    "itemStack itemStack Data Keys",
    "itemStack ItemStack data keys",
    "itemStack ItemStack data Keys",
    "itemStack ItemStack Data keys",
    "itemStack ItemStack Data Keys",
    "ItemStack itemstack data keys",
    "ItemStack itemstack data Keys",
    "ItemStack itemstack Data keys",
    "ItemStack itemstack Data Keys",
    "ItemStack Itemstack data keys",
    "ItemStack Itemstack data Keys",
    "ItemStack Itemstack Data keys",
    "ItemStack Itemstack Data Keys",
    "ItemStack itemStack data keys",
    "ItemStack itemStack data Keys",
    "ItemStack itemStack Data keys",
    "ItemStack itemStack Data Keys",
    "ItemStack ItemStack data keys",
    "ItemStack ItemStack data Keys",
    "ItemStack ItemStack Data keys",
    "ItemStack ItemStack Data Keys",
    "item data keys",
    "item data Keys",
    "item Data keys",
    "item Data Keys",
    "Item data keys",
    "Item data Keys",
    "Item Data keys",
    "Item Data Keys",
    "itemstack data keys",
    "itemstack data Keys",
    "itemstack Data keys",
    "itemstack Data Keys",
    "Itemstack data keys",
    "Itemstack data Keys",
    "Itemstack Data keys",
    "Itemstack Data Keys",
    "itemStack data keys",
    "itemStack data Keys",
    "itemStack Data keys",
    "itemStack Data Keys",
    "ItemStack data keys",
    "ItemStack data Keys",
    "ItemStack Data keys",
    "ItemStack Data Keys",
  ];
  static override kind = "itemstack" as const;
  static override renderPattern = "SUFFIX_1_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Item",
          },
          to: { type: "List", listType: { type: "String" } },
        },
        normalizeSignature
      ),
      function: (item: Item): iArray<iString> => {
        const nbt = item.getNBT();
        if (nbt instanceof CompoundTag) {
          return nbt.getAllKeys();
        }
        return new iArrayEager<iString>([]);
      },
    });
  }
}
