import { BaseOperator } from "lib/IntegratedDynamicsClasses/operators/BaseOperator";
import { ParsedSignature } from "lib/HelperClasses/ParsedSignature";
import { Recipe } from "lib/IntegratedDynamicsClasses/Recipe";
import { Ingredients } from "lib/IntegratedDynamicsClasses/Ingredients";
import { Operator } from "lib/IntegratedDynamicsClasses/operators/Operator";

export class OPERATOR_RECIPE_WITH_INPUT_OUTPUT extends BaseOperator<
  Ingredients,
  Operator<Ingredients, Recipe>
> {
  static override internalName =
    "integrateddynamics:recipe_with_input_output" as const;
  static override numericID = 183;
  static override nicknames = [
    "ingredientsWithInputOutput",
    "recipeWithInputOutput",
    "withInputOutput",
    "ingredients_with_input_output",
    "recipe_with_input_output",
    "recipeWith_input_output",
    "with_input_output",
  ];
  static override symbol = "Recipe.with_io";
  static override interactName = "ingredientsWithInputOutput";
  static override operatorName = "with_input_output" as const;
  static override displayName =
    "Recipe With Input and Output Ingredients" as const;
  static override fullDisplayName =
    "Recipe Recipe With Input and Output Ingredients" as const;
  static override stringDisplayNames = [
    "recipe with input and output ingredients",
    "recipe with input and output Ingredients",
    "recipe with input and Output ingredients",
    "recipe with input and Output Ingredients",
    "recipe with input And output ingredients",
    "recipe with input And output Ingredients",
    "recipe with input And Output ingredients",
    "recipe with input And Output Ingredients",
    "recipe with Input and output ingredients",
    "recipe with Input and output Ingredients",
    "recipe with Input and Output ingredients",
    "recipe with Input and Output Ingredients",
    "recipe with Input And output ingredients",
    "recipe with Input And output Ingredients",
    "recipe with Input And Output ingredients",
    "recipe with Input And Output Ingredients",
    "recipe With input and output ingredients",
    "recipe With input and output Ingredients",
    "recipe With input and Output ingredients",
    "recipe With input and Output Ingredients",
    "recipe With input And output ingredients",
    "recipe With input And output Ingredients",
    "recipe With input And Output ingredients",
    "recipe With input And Output Ingredients",
    "recipe With Input and output ingredients",
    "recipe With Input and output Ingredients",
    "recipe With Input and Output ingredients",
    "recipe With Input and Output Ingredients",
    "recipe With Input And output ingredients",
    "recipe With Input And output Ingredients",
    "recipe With Input And Output ingredients",
    "recipe With Input And Output Ingredients",
    "Recipe with input and output ingredients",
    "Recipe with input and output Ingredients",
    "Recipe with input and Output ingredients",
    "Recipe with input and Output Ingredients",
    "Recipe with input And output ingredients",
    "Recipe with input And output Ingredients",
    "Recipe with input And Output ingredients",
    "Recipe with input And Output Ingredients",
    "Recipe with Input and output ingredients",
    "Recipe with Input and output Ingredients",
    "Recipe with Input and Output ingredients",
    "Recipe with Input and Output Ingredients",
    "Recipe with Input And output ingredients",
    "Recipe with Input And output Ingredients",
    "Recipe with Input And Output ingredients",
    "Recipe with Input And Output Ingredients",
    "Recipe With input and output ingredients",
    "Recipe With input and output Ingredients",
    "Recipe With input and Output ingredients",
    "Recipe With input and Output Ingredients",
    "Recipe With input And output ingredients",
    "Recipe With input And output Ingredients",
    "Recipe With input And Output ingredients",
    "Recipe With input And Output Ingredients",
    "Recipe With Input and output ingredients",
    "Recipe With Input and output Ingredients",
    "Recipe With Input and Output ingredients",
    "Recipe With Input and Output Ingredients",
    "Recipe With Input And output ingredients",
    "Recipe With Input And output Ingredients",
    "Recipe With Input And Output ingredients",
    "Recipe With Input And Output Ingredients",
    "recipe recipe with input and output ingredients",
    "recipe recipe with input and output Ingredients",
    "recipe recipe with input and Output ingredients",
    "recipe recipe with input and Output Ingredients",
    "recipe recipe with input And output ingredients",
    "recipe recipe with input And output Ingredients",
    "recipe recipe with input And Output ingredients",
    "recipe recipe with input And Output Ingredients",
    "recipe recipe with Input and output ingredients",
    "recipe recipe with Input and output Ingredients",
    "recipe recipe with Input and Output ingredients",
    "recipe recipe with Input and Output Ingredients",
    "recipe recipe with Input And output ingredients",
    "recipe recipe with Input And output Ingredients",
    "recipe recipe with Input And Output ingredients",
    "recipe recipe with Input And Output Ingredients",
    "recipe recipe With input and output ingredients",
    "recipe recipe With input and output Ingredients",
    "recipe recipe With input and Output ingredients",
    "recipe recipe With input and Output Ingredients",
    "recipe recipe With input And output ingredients",
    "recipe recipe With input And output Ingredients",
    "recipe recipe With input And Output ingredients",
    "recipe recipe With input And Output Ingredients",
    "recipe recipe With Input and output ingredients",
    "recipe recipe With Input and output Ingredients",
    "recipe recipe With Input and Output ingredients",
    "recipe recipe With Input and Output Ingredients",
    "recipe recipe With Input And output ingredients",
    "recipe recipe With Input And output Ingredients",
    "recipe recipe With Input And Output ingredients",
    "recipe recipe With Input And Output Ingredients",
    "recipe Recipe with input and output ingredients",
    "recipe Recipe with input and output Ingredients",
    "recipe Recipe with input and Output ingredients",
    "recipe Recipe with input and Output Ingredients",
    "recipe Recipe with input And output ingredients",
    "recipe Recipe with input And output Ingredients",
    "recipe Recipe with input And Output ingredients",
    "recipe Recipe with input And Output Ingredients",
    "recipe Recipe with Input and output ingredients",
    "recipe Recipe with Input and output Ingredients",
    "recipe Recipe with Input and Output ingredients",
    "recipe Recipe with Input and Output Ingredients",
    "recipe Recipe with Input And output ingredients",
    "recipe Recipe with Input And output Ingredients",
    "recipe Recipe with Input And Output ingredients",
    "recipe Recipe with Input And Output Ingredients",
    "recipe Recipe With input and output ingredients",
    "recipe Recipe With input and output Ingredients",
    "recipe Recipe With input and Output ingredients",
    "recipe Recipe With input and Output Ingredients",
    "recipe Recipe With input And output ingredients",
    "recipe Recipe With input And output Ingredients",
    "recipe Recipe With input And Output ingredients",
    "recipe Recipe With input And Output Ingredients",
    "recipe Recipe With Input and output ingredients",
    "recipe Recipe With Input and output Ingredients",
    "recipe Recipe With Input and Output ingredients",
    "recipe Recipe With Input and Output Ingredients",
    "recipe Recipe With Input And output ingredients",
    "recipe Recipe With Input And output Ingredients",
    "recipe Recipe With Input And Output ingredients",
    "recipe Recipe With Input And Output Ingredients",
    "Recipe recipe with input and output ingredients",
    "Recipe recipe with input and output Ingredients",
    "Recipe recipe with input and Output ingredients",
    "Recipe recipe with input and Output Ingredients",
    "Recipe recipe with input And output ingredients",
    "Recipe recipe with input And output Ingredients",
    "Recipe recipe with input And Output ingredients",
    "Recipe recipe with input And Output Ingredients",
    "Recipe recipe with Input and output ingredients",
    "Recipe recipe with Input and output Ingredients",
    "Recipe recipe with Input and Output ingredients",
    "Recipe recipe with Input and Output Ingredients",
    "Recipe recipe with Input And output ingredients",
    "Recipe recipe with Input And output Ingredients",
    "Recipe recipe with Input And Output ingredients",
    "Recipe recipe with Input And Output Ingredients",
    "Recipe recipe With input and output ingredients",
    "Recipe recipe With input and output Ingredients",
    "Recipe recipe With input and Output ingredients",
    "Recipe recipe With input and Output Ingredients",
    "Recipe recipe With input And output ingredients",
    "Recipe recipe With input And output Ingredients",
    "Recipe recipe With input And Output ingredients",
    "Recipe recipe With input And Output Ingredients",
    "Recipe recipe With Input and output ingredients",
    "Recipe recipe With Input and output Ingredients",
    "Recipe recipe With Input and Output ingredients",
    "Recipe recipe With Input and Output Ingredients",
    "Recipe recipe With Input And output ingredients",
    "Recipe recipe With Input And output Ingredients",
    "Recipe recipe With Input And Output ingredients",
    "Recipe recipe With Input And Output Ingredients",
    "Recipe Recipe with input and output ingredients",
    "Recipe Recipe with input and output Ingredients",
    "Recipe Recipe with input and Output ingredients",
    "Recipe Recipe with input and Output Ingredients",
    "Recipe Recipe with input And output ingredients",
    "Recipe Recipe with input And output Ingredients",
    "Recipe Recipe with input And Output ingredients",
    "Recipe Recipe with input And Output Ingredients",
    "Recipe Recipe with Input and output ingredients",
    "Recipe Recipe with Input and output Ingredients",
    "Recipe Recipe with Input and Output ingredients",
    "Recipe Recipe with Input and Output Ingredients",
    "Recipe Recipe with Input And output ingredients",
    "Recipe Recipe with Input And output Ingredients",
    "Recipe Recipe with Input And Output ingredients",
    "Recipe Recipe with Input And Output Ingredients",
    "Recipe Recipe With input and output ingredients",
    "Recipe Recipe With input and output Ingredients",
    "Recipe Recipe With input and Output ingredients",
    "Recipe Recipe With input and Output Ingredients",
    "Recipe Recipe With input And output ingredients",
    "Recipe Recipe With input And output Ingredients",
    "Recipe Recipe With input And Output ingredients",
    "Recipe Recipe With input And Output Ingredients",
    "Recipe Recipe With Input and output ingredients",
    "Recipe Recipe With Input and output Ingredients",
    "Recipe Recipe With Input and Output ingredients",
    "Recipe Recipe With Input and Output Ingredients",
    "Recipe Recipe With Input And output ingredients",
    "Recipe Recipe With Input And output Ingredients",
    "Recipe Recipe With Input And Output ingredients",
    "Recipe Recipe With Input And Output Ingredients",
  ];
  static override tooltipInfo =
    "Create a recipe with the first ingredients as input, and the second ingredients as output" as const;

  static override kind = "recipe" as const;
  static override renderPattern = "PREFIX_2_LONG" as const;
  constructor(normalizeSignature = true) {
    super({
      parsedSignature: new ParsedSignature(
        {
          type: "Function",
          from: {
            type: "Ingredients",
          },
          to: {
            type: "Function",
            from: {
              type: "Ingredients",
            },
            to: {
              type: "Recipe",
            },
          },
        },
        normalizeSignature
      ),
      function: (input: Ingredients): TypeLambda<Ingredients, Recipe> => {
        return (output: Ingredients): Recipe => {
          return new Recipe(input, output);
        };
      },
    });
  }
}
