bug:
  - '/### What''s wrong\?/'

enhancement:
  - "/### Describe the suggestion/"

bug/logic-programmer-view:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Logic Programmer View|-\s*\[[xX]\]\s*Logic Programmer View[\s\S]*### What''s wrong\?/'
bug/display-panel-view:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Display Panel View|-\s*\[[xX]\]\s*Display Panel View[\s\S]*### What''s wrong\?/'
bug/reader-view:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Reader View|-\s*\[[xX]\]\s*Reader View[\s\S]*### What''s wrong\?/'
bug/visual-transformer:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Visual Transformer|-\s*\[[xX]\]\s*Visual Transformer[\s\S]*### What''s wrong\?/'
bug/json-transformer:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*JSON Transformer|-\s*\[[xX]\]\s*JSON Transformer[\s\S]*### What''s wrong\?/'
bug/code-line-transformer:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Code Line Transformer|-\s*\[[xX]\]\s*Code Line Transformer[\s\S]*### What''s wrong\?/'
bug/expanded-transformer:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Expanded Transformer|-\s*\[[xX]\]\s*Expanded Transformer[\s\S]*### What''s wrong\?/'
bug/condensed-transformer:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Condensed Transformer|-\s*\[[xX]\]\s*Condensed Transformer[\s\S]*### What''s wrong\?/'
bug/multiple-transformers:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Multiple Transformers|-\s*\[[xX]\]\s*Multiple Transformers[\s\S]*### What''s wrong\?/'
bug/operator-documentation:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Operator Documentation|-\s*\[[xX]\]\s*Operator Documentation[\s\S]*### What''s wrong\?/'
bug/reader-documentation:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Reader Documentation|-\s*\[[xX]\]\s*Reader Documentation[\s\S]*### What''s wrong\?/'
bug/github-actions-ci:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*GitHub Actions|-\s*\[[xX]\]\s*GitHub Actions[\s\S]*### What''s wrong\?/'
bug/local-workflows:
  - '/### What''s wrong\?[\s\S]*-\s*\[[xX]\]\s*Local workflows|-\s*\[[xX]\]\s*Local workflows[\s\S]*### What''s wrong\?/'

enhancement/logic-programmer-view:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Logic Programmer View|-\s*\[[xX]\]\s*Logic Programmer View[\s\S]*### Describe the suggestion/'
enhancement/display-panel-view:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Display Panel View|-\s*\[[xX]\]\s*Display Panel View[\s\S]*### Describe the suggestion/'
enhancement/reader-view:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Reader View|-\s*\[[xX]\]\s*Reader View[\s\S]*### Describe the suggestion/'
enhancement/visual-transformer:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Visual Transformer|-\s*\[[xX]\]\s*Visual Transformer[\s\S]*### Describe the suggestion/'
enhancement/json-transformer:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*JSON Transformer|-\s*\[[xX]\]\s*JSON Transformer[\s\S]*### Describe the suggestion/'
enhancement/code-line-transformer:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Code Line Transformer|-\s*\[[xX]\]\s*Code Line Transformer[\s\S]*### Describe the suggestion/'
enhancement/expanded-transformer:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Expanded Transformer|-\s*\[[xX]\]\s*Expanded Transformer[\s\S]*### Describe the suggestion/'
enhancement/condensed-transformer:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Condensed Transformer|-\s*\[[xX]\]\s*Condensed Transformer[\s\S]*### Describe the suggestion/'
enhancement/multiple-transformers:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Multiple Transformers|-\s*\[[xX]\]\s*Multiple Transformers[\s\S]*### Describe the suggestion/'
enhancement/operator-documentation:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Operator Documentation|-\s*\[[xX]\]\s*Operator Documentation[\s\S]*### Describe the suggestion/'
enhancement/reader-documentation:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Reader Documentation|-\s*\[[xX]\]\s*Reader Documentation[\s\S]*### Describe the suggestion/'
enhancement/github-actions-ci:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*GitHub Actions|-\s*\[[xX]\]\s*GitHub Actions[\s\S]*### Describe the suggestion/'
enhancement/local-workflows:
  - '/### Describe the suggestion[\s\S]*-\s*\[[xX]\]\s*Local workflows|-\s*\[[xX]\]\s*Local workflows[\s\S]*### Describe the suggestion/'
