import {
  ReaderBase,
  type ReaderAspects,
} from "lib/IntegratedDynamicsClasses/readers/ReaderBase";
import { MACHINE_BOOLEAN_ISWORKER } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISWORKER";
import { MACHINE_BOOLEAN_HASWORK } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_HASWORK";
import { MACHINE_BOOLEAN_CANWORK } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_CANWORK";
import { MACHINE_BOOLEAN_ISWORKING } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISWORKING";
import { MACHINE_BOOLEAN_ISTEMPERATURE } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISTEMPERATURE";
import { MACHINE_DOUBLE_TEMPERATURE } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/DOUBLE_TEMPERATURE";
import { MACHINE_DOUBLE_MAXTEMPERATURE } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/DOUBLE_MAXTEMPERATURE";
import { MACHINE_DOUBLE_MINTEMPERATURE } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/DOUBLE_MINTEMPERATURE";
import { MACHINE_DOUBLE_DEFAULTTEMPERATURE } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/DOUBLE_DEFAULTTEMPERATURE";
import { MACHINE_BOOLEAN_ISRECIPEHANDLER } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISRECIPEHANDLER";
import { MACHINE_LIST_GETRECIPES } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/LIST_GETRECIPES";
import { MACHINE_OPERATOR_GETRECIPEBYINPUT } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/OPERATOR_GETRECIPEBYINPUT";
import { MACHINE_OPERATOR_GETRECIPEBYOUTPUT } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/OPERATOR_GETRECIPEBYOUTPUT";
import { MACHINE_OPERATOR_GETRECIPESBYINPUT } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/OPERATOR_GETRECIPESBYINPUT";
import { MACHINE_OPERATOR_GETRECIPESBYOUTPUT } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/OPERATOR_GETRECIPESBYOUTPUT";
import { MACHINE_OPERATOR_GETRECIPEOUTPUT } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/OPERATOR_GETRECIPEOUTPUT";
import { MACHINE_OPERATOR_GETRECIPEINPUTS } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/OPERATOR_GETRECIPEINPUTS";
import { MACHINE_BOOLEAN_ISENERGY } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISENERGY";
import { MACHINE_BOOLEAN_ISENERGYRECEIVER } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISENERGYRECEIVER";
import { MACHINE_BOOLEAN_ISENERGYPROVIDER } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISENERGYPROVIDER";
import { MACHINE_BOOLEAN_CANEXTRACTENERGY } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_CANEXTRACTENERGY";
import { MACHINE_BOOLEAN_CANINSERTENERGY } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_CANINSERTENERGY";
import { MACHINE_BOOLEAN_ISENERGYFULL } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISENERGYFULL";
import { MACHINE_BOOLEAN_ISENERGYEMPTY } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISENERGYEMPTY";
import { MACHINE_BOOLEAN_ISENERGYNONEMPTY } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/BOOLEAN_ISENERGYNONEMPTY";
import { MACHINE_INTEGER_ENERGYSTORED } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/INTEGER_ENERGYSTORED";
import { MACHINE_INTEGER_ENERGYCAPACITY } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/INTEGER_ENERGYCAPACITY";
import { MACHINE_DOUBLE_ENERGYFILLRATIO } from "lib/IntegratedDynamicsClasses/readers/MachineReader/Aspects/DOUBLE_ENERGYFILLRATIO";

export class MachineReader extends ReaderBase {
  static typeName = "MachineReader";
  static shortName = "machine";
  static numericID = 18;

  static aspects: ReaderAspects = {
    BOOLEAN_ISWORKER: MACHINE_BOOLEAN_ISWORKER,
    BOOLEAN_HASWORK: MACHINE_BOOLEAN_HASWORK,
    BOOLEAN_CANWORK: MACHINE_BOOLEAN_CANWORK,
    BOOLEAN_ISWORKING: MACHINE_BOOLEAN_ISWORKING,
    BOOLEAN_ISTEMPERATURE: MACHINE_BOOLEAN_ISTEMPERATURE,
    DOUBLE_TEMPERATURE: MACHINE_DOUBLE_TEMPERATURE,
    DOUBLE_MAXTEMPERATURE: MACHINE_DOUBLE_MAXTEMPERATURE,
    DOUBLE_MINTEMPERATURE: MACHINE_DOUBLE_MINTEMPERATURE,
    DOUBLE_DEFAULTTEMPERATURE: MACHINE_DOUBLE_DEFAULTTEMPERATURE,
    BOOLEAN_ISRECIPEHANDLER: MACHINE_BOOLEAN_ISRECIPEHANDLER,
    LIST_GETRECIPES: MACHINE_LIST_GETRECIPES,
    OPERATOR_GETRECIPEBYINPUT: MACHINE_OPERATOR_GETRECIPEBYINPUT,
    OPERATOR_GETRECIPEBYOUTPUT: MACHINE_OPERATOR_GETRECIPEBYOUTPUT,
    OPERATOR_GETRECIPESBYINPUT: MACHINE_OPERATOR_GETRECIPESBYINPUT,
    OPERATOR_GETRECIPESBYOUTPUT: MACHINE_OPERATOR_GETRECIPESBYOUTPUT,
    OPERATOR_GETRECIPEOUTPUT: MACHINE_OPERATOR_GETRECIPEOUTPUT,
    OPERATOR_GETRECIPEINPUTS: MACHINE_OPERATOR_GETRECIPEINPUTS,
    BOOLEAN_ISENERGY: MACHINE_BOOLEAN_ISENERGY,
    BOOLEAN_ISENERGYRECEIVER: MACHINE_BOOLEAN_ISENERGYRECEIVER,
    BOOLEAN_ISENERGYPROVIDER: MACHINE_BOOLEAN_ISENERGYPROVIDER,
    BOOLEAN_CANEXTRACTENERGY: MACHINE_BOOLEAN_CANEXTRACTENERGY,
    BOOLEAN_CANINSERTENERGY: MACHINE_BOOLEAN_CANINSERTENERGY,
    BOOLEAN_ISENERGYFULL: MACHINE_BOOLEAN_ISENERGYFULL,
    BOOLEAN_ISENERGYEMPTY: MACHINE_BOOLEAN_ISENERGYEMPTY,
    BOOLEAN_ISENERGYNONEMPTY: MACHINE_BOOLEAN_ISENERGYNONEMPTY,
    INTEGER_ENERGYSTORED: MACHINE_INTEGER_ENERGYSTORED,
    INTEGER_ENERGYCAPACITY: MACHINE_INTEGER_ENERGYCAPACITY,
    DOUBLE_ENERGYFILLRATIO: MACHINE_DOUBLE_ENERGYFILLRATIO,
  };
}
